In [102]:
import os

project_folder = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-Personal/Semicon2.0_ML_Project"
)

print(os.path.exists(project_folder))

False

In [103]:
import os

project_folder = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-Personal/Semicon2.0_ML_Project"
)

print(os.path.exists(project_folder))

False

In [104]:
import os
import glob

paths = glob.glob(os.path.expanduser("~/Library/CloudStorage/*"))

for path in paths:
    print(path)

/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY
/Users/shashankyadav/Library/CloudStorage/OneDrive-SharedLibraries-WOXSENUNIVERSITY

In [105]:
import os

project_folder = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semicon2.0_ML_Project"
)

print("Project folder exists:", os.path.exists(project_folder))

Project folder exists: False

In [106]:
import os

onedrive = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY"
)

print("OneDrive exists:", os.path.exists(onedrive))

if os.path.exists(onedrive):
    print("\nFolders/files inside OneDrive:\n")
    for item in os.listdir(onedrive):
        print(item)

OneDrive exists: True

Folders/files inside OneDrive:

25WU0104016_EVS_Case_Study1.docx
Chemistry_Case_Study_Final.docx
Member_6_Innovation_Application_Conclusion 2 1.docx
EVS End-Sem Project (Joel).docx
Book 3.xlsx
outing form 2.docx
Chemistry_Case_Study_Expanded 1.docx
Hospital_Management_ShahankYadav_v2 1.docx
.DS_Store
Chemistry Case Study.docx
Book 2.xlsx
25WU0104009_DT_A2.docx
Icon
CTPS_Assignment_ShahankYadav 1.docx
Member_6_Innovation_Application_Conclusion.docx
Case_Study_Sri_Venkateshwara_Foods.docx
CTPS_Submission_Document_Format.docx
Scans
ELP.data.Docx.docx
Proof Reading Exercises.docx
12th_Marks_Memo_Original_Certificate.pdf
physics_Title_page.docx
Searching_Operations_Report-2.docx
Document 1.docx
Hospital_Management_ShahankYadav_v2.docx
Chemistry Assignment.pdf.docx
Letter of Consent copy 1.docx
Assignment 2 DSA suffix tries  2 2.docx
SIP Report_NanoWeave.docx
Semiconductor_Credit_Risk_ML
outing form.docx
CTPS_Submission_Document_Format 2.docx
Environmental_Sciences_Assignment-II_25WU0104009.docx
CTPS_Submission_Document_Format 2 1.docx
Engineering_Mathematics_Assignment-II_G.Shashank_Yadav 1.docx
Assignment 2 DSA suffix tries  2 1.docx
Chemistry_Case_Study_Expanded.docx
CTPS_Submission_Document_Format 1.docx
Data analyst 2023.xlsx
Woxsen_ELP_Certificate_Final.docx
Letter of Consent copy 1 1.docx
Assignment 2 DSA suffix tries  2.docx
ASSIGNMENT FORMAT.docx
Minutes of Meeting(MOM)_Summary of Meeting.docx
Document 2.docx
Document 3.docx
Banking_OOP_DeepDive_Assignment.docx
Book.xlsx
CTPS_Assignment_ShahankYadav.docx
25WU010400_DT_A2.docx
Minutes of meeting..docx
.Trash
NameG.docx
The Forbidden Files - Game Theory Will Change Your Life_ The Invisible Rules Running Every Interaction.docx
EVS_Assignment_II_Godrej_G_Shashank_Yadav.docx
My Notebook @ WOXSEN UNIVERSITY.url
Assignment 2 DSA suffix tries .docx
Member_6_Innovation_Application_Conclusion 2.docx
EVS_assignment_by_G.Shashank.docx
lettuce_dataset_updated 2.xlsx
WhatsApp Image 2026-07-19 at 11.14.54.docx
25WU0104016_EVS_Case_Study.docx
Book 1.xlsx
Chemistry_Case_Study.docx
Attachments
ELP_Smart_Helmet_Report.docx
Design Thinking_Assignment_25WU0104009.docx
Chemistry_Case_Study_Final 1.docx
Engineering_Mathematics_Assignment-II_G.Shashank_Yadav.docx
Patent Smart helmet.docx
Banking_OOP_DeepDive_Assignment 1.docx
design thinking.docx
Document.docx
outing form 1.docx
IEEE-EMBS15-Maite copy.pdf
Searching_Operations_Report-2 1.docx
.849C9593-D756-4E56-8D6E-42412F2A707B

In [107]:
import os

project_folder = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML"
)

print("Project folder exists:", os.path.exists(project_folder))

Project folder exists: True

In [108]:
import os

rbi_folder = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/01_Raw_Data/RBI"
)

print("RBI folder exists:", os.path.exists(rbi_folder))

if os.path.exists(rbi_folder):
    print("\nFiles inside RBI folder:")
    for file in os.listdir(rbi_folder):
        print(file)

RBI folder exists: True

Files inside RBI folder:
Banking_Stress
.DS_Store
Sectoral_Credit

In [11]:
import pandas as pd
import openpyxl

print("Pandas version:", pd.__version__)
print("OpenPyXL is working!")

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
Pandas version: 2.2.3
OpenPyXL is working!

In [12]:
import os
import glob

rbi_folder = os.path.expanduser(
    "~/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/01_Raw_Data/RBI"
)

files = glob.glob(os.path.join(rbi_folder, "*"))

print("Files found:")
for file in files:
    print(os.path.basename(file))

Files found:
Searching “This Mac”.savedSearch
PR2019SIBC300126.xlsx

In [13]:
import pandas as pd
import os

file_path = os.path.join(
    rbi_folder,
    "PR2019SIBC300126.xlsx"
)

excel_file = pd.ExcelFile(file_path)

print("Sheets in the RBI workbook:")
for sheet in excel_file.sheet_names:
    print("-", sheet)

Sheets in the RBI workbook:
- Statement 1
- Statement 2

In [14]:
statement1 = pd.read_excel(
    file_path,
    sheet_name="Statement 1",
    header=None
)

print(statement1.shape)
display(statement1.head(15))

(59, 10)

,0,1,2,3,4,5,6,7,8,9
0,Statement 1: Deployment of Gross Bank Credit b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(Rs. Crore),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sector,Outstanding as on,NaN,NaN,NaN,NaN,Variation (Year-on-Year),NaN,Variation (Financial Year),NaN
3,NaN,"29.Dec,2023","22.Mar,2024","27.Dec,2024","21.Mar,2025","31.Dec,2025","27.Dec,2024 / 29.Dec,2023","31.Dec,2025 / 27.Dec,2024","27.Dec,2024 / 22.Mar,2024","31.Dec,2025 / 21.Mar,2025"
4,NaN,NaN,NaN,NaN,NaN,NaN,%,%,%,%
5,I. Bank Credit (II + III),15961943.97318,16432163.92671,17743037.471805,18243972.33467,20322515.473019,11.158375,14.537973,7.977486,11.39304
6,II. Food Credit,43138.61,23080.81,56138.69,36531.16,87972.45,30.135602,56.705563,143.226689,140.814828
7,III. Non-food Credit,15918805.36318,16409083.11671,17686898.781805,18207441.17467,20234543.023019,11.106948,14.404132,7.787246,11.13337
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1. Agriculture and Allied Activities,1991030.054014,2071250.995736,2239028.099859,2287060.099496,2509223.947623,12.455766,12.067551,8.100279,9.713949
10,"2. Industry (Micro and Small, Medium and Large)",3622549.688427,3682392.531552,3893504.019162,3985659.551324,4413256.957607,7.479658,13.349233,5.732998,10.728398
11,2.1. Micro and Small,708809.1372,733123.356073,778528.551024,798472.66076,1020006.955188,9.836134,31.017283,6.193391,27.744756
12,2.2. Medium,292703.099367,306424.853962,350738.938445,363245.019249,422440.874062,19.827545,20.443107,14.461648,16.296398
13,2.3. Large,2621037.45186,2642844.321517,2764236.529692,2823941.871316,2970809.128357,5.46345,7.473044,4.593241,5.200789
14,3. Services,4400726.057904,4547236.765609,4905686.40861,5093565.107574,5654178.588306,11.474478,15.257644,7.882801,11.006308

In [15]:
statement2 = pd.read_excel(
    file_path,
    sheet_name="Statement 2",
    header=None
)

print(statement2.shape)
display(statement2.head(30))

(49, 10)

,0,1,2,3,4,5,6,7,8,9
0,Statement 2: Industry-wise Deployment of Gross...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(Rs. Crore),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Industry,Outstanding as on,NaN,NaN,NaN,NaN,Variation (Year-on-Year),NaN,Variation (Financial Year),NaN
3,NaN,"29.Dec,2023","22.Mar,2024","27.Dec,2024","21.Mar,2025","31.Dec,2025","27.Dec,2024 / 29.Dec,2023","31.Dec,2025 / 27.Dec,2024","27.Dec,2024 / 22.Mar,2024","31.Dec,2025 / 21.Mar,2025"
4,NaN,NaN,NaN,NaN,NaN,NaN,%,%,%,%
5,2.1. Mining and Quarrying (incl. Coal),54951.551223,54220.184399,53937.531222,56817.556194,64877.41021,-1.845298,20.282499,-0.521306,14.185499
6,2.2. Food Processing,191448.221037,208862.771555,211984.872981,219524.798106,236769.514999,10.727001,11.691703,1.49481,7.855476
7,2.2.1. Sugar,16773.33012,26383.011251,19889.357612,28521.702093,20369.483407,18.577274,2.413983,-24.613012,-28.582511
8,2.2.2. Edible Oils and Vanaspati,21411.22452,19700.216132,21798.419425,20927.253641,24850.03942,1.808373,13.999272,10.650661,18.744867
9,2.2.3. Tea,5951.700404,5691.947888,6469.750964,5083.83262,5296.050505,8.704245,-18.141355,13.664972,4.174368
10,2.2.4. Others,147311.965994,157087.596283,163827.344979,164992.009752,186253.941666,11.211159,13.689166,4.29044,12.886643
11,2.3. Beverage and Tobacco,28296.718144,31137.471103,30670.671585,35515.454614,37449.940906,8.389501,22.103426,-1.499157,5.446886
12,2.4. Textiles,250039.908722,256047.983577,264055.644259,277267.085246,295290.932592,5.605399,11.829055,3.127406,6.500536
13,2.4.1. Cotton Textiles,96095.302508,99513.087082,98417.450311,107494.595816,108972.184793,2.416505,10.724454,-1.100998,1.37457
14,2.4.2. Jute Textiles,4187.414484,4279.559436,4340.162807,4288.234703,4967.240363,3.647796,14.44825,1.416112,15.834153
15,2.4.3. Man-Made Textiles,45326.936415,45074.468407,48666.982085,49186.259419,51060.19518,7.368788,4.917529,7.970174,3.809877
16,2.4.4. Other Textiles,104430.255313,107180.868652,112631.049056,116297.995308,130291.312256,7.852891,15.679747,5.085031,12.032294
17,2.5. Leather and Leather Products,12130.812768,12587.81048,12804.165584,12979.843088,13717.481536,5.550764,7.13296,1.718767,5.682954
18,2.6. Wood and Wood Products,23384.089826,23838.814976,26601.205325,27825.967375,30312.460447,13.757711,13.951455,11.587784,8.935873
19,2.7. Paper and Paper Products,45499.315347,46426.057126,51507.728766,52847.593915,57587.063252,13.205503,11.802762,10.945732,8.968184
20,"2.8. Petroleum, Coal Products and Nuclear Fuels",131320.147964,132356.302438,139840.446812,154178.5291,194376.266551,6.488189,38.998602,5.654543,26.072202
21,2.9. Chemicals and Chemical Products,246362.78687,249347.615963,263645.364354,267814.870041,302681.532541,7.015093,14.806317,5.734063,13.018942
22,2.9.1. Fertiliser,36025.631492,37569.368771,31828.66992,32011.209754,34473.150021,-11.649932,8.308484,-15.280264,7.690869
23,2.9.2. Drugs and Pharmaceuticals,80079.193899,80832.235579,87820.82797,88524.293888,95547.900813,9.667473,8.798679,8.645799,7.934101
24,2.9.3. Petro Chemicals,25270.270614,25318.154272,27836.103257,28797.461456,36059.47481,10.153562,29.542108,9.945231,25.217547
25,2.9.4. Others,104987.690866,105627.857342,116159.763206,118481.904944,136601.006897,10.641316,17.597525,9.970765,15.292717
26,"2.10. Rubber, Plastic and their Products",87730.293464,90471.783405,98913.76262,103464.613501,108654.13518,12.747557,9.847338,9.331063,5.015745
27,2.11. Glass and Glassware,11347.304138,12090.217792,12507.501312,13442.791875,13759.588948,10.22443,10.010694,3.451414,2.356632
28,2.12. Cement and Cement Products,60243.636652,59756.90776,61541.782561,59752.607309,64558.756362,2.154827,4.902318,2.986893,8.043413
29,2.13. Basic Metal and Metal Product,382539.769297,384447.229472,432756.824709,433501.154395,494161.681728,13.127277,14.189229,12.565989,13.993164

In [16]:
for i, row in statement2.iterrows():
    row_text = " ".join(str(x) for x in row.tolist())
    
    if "Electronics" in row_text or "electronics" in row_text:
        print("Row:", i)
        print(row.tolist())
        print("-" * 100)

Row: 33
['2.14.1. Electronics', 43005.886621, 43395.914093, 50109.432333, 52863.096541, 68839.342157, 16.5176125180298, 37.37801238603389, 15.4703925019589, 30.221925428846223]
----------------------------------------------------------------------------------------------------

In [17]:
import requests

url = "https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx"

response = requests.get(url, timeout=30)

print("Status code:", response.status_code)
print("Page size:", len(response.text))

Status code: 200
Page size: 66383

In [18]:
from bs4 import BeautifulSoup
from urllib.parse import urljoin

soup = BeautifulSoup(response.text, "html.parser")

links = []

for a in soup.find_all("a", href=True):
    href = a["href"]
    text = a.get_text(" ", strip=True)

    if "SIBC" in href.upper() or "SIBC" in text.upper():
        links.append({
            "text": text,
            "url": urljoin(url, href)
        })

print("Number of SIBC links found:", len(links))

for link in links[:20]:
    print(link["text"], "→", link["url"])

Number of SIBC links found: 0

In [19]:
# Show links on the RBI page that look like downloadable files

all_links = []

for a in soup.find_all("a", href=True):
    href = a["href"]
    text = a.get_text(" ", strip=True)

    if any(ext in href.lower() for ext in [".xls", ".xlsx", ".pdf", ".csv"]):
        all_links.append((text, href))

print("Possible downloadable links:", len(all_links))

for text, href in all_links[:30]:
    print("TEXT:", text)
    print("LINK:", href)
    print("-" * 80)

Possible downloadable links: 2
TEXT: RBI’s Vision and Values (652 kb)
LINK: https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
--------------------------------------------------------------------------------
TEXT: Accessibility Statement (133 KB)
LINK: https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf
--------------------------------------------------------------------------------

In [20]:
# Look for references to the sectoral-deployment data in the RBI page source

keywords = [
    "Sectoral",
    "Deployment",
    "SIBC",
    "PR2019",
    "PR1808",
    "Data_Sectoral"
]

for keyword in keywords:
    print(f"\n--- {keyword} ---")
    
    positions = []
    start = 0
    
    while True:
        pos = response.text.lower().find(keyword.lower(), start)
        if pos == -1:
            break
        
        positions.append(pos)
        start = pos + len(keyword)
    
    print("Occurrences:", len(positions))
    
    for pos in positions[:5]:
        print(response.text[max(0, pos-200):pos+500])

--- Sectoral ---
Occurrences: 13
sitional.dtd">

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Data on Sectoral Deployment of Bank Credit | Official Website of Reserve Bank of India </title>
    <meta name="description" content="Data on Sectoral Deployment of Bank Credit  - Reserve Bank of India" />
    <meta name="keyword" content="RBI Data on Sectoral Deployment of Bank Credit" />
    <meta name="author " content="Reserve Bank of India" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<
UA-Compatible" content="IE=edge,chrome=1" />
    <title>Data on Sectoral Deployment of Bank Credit | Official Website of Reserve Bank of India </title>
    <meta name="description" content="Data on Sectoral Deployment of Bank Credit  - Reserve Bank of India" />
    <meta name="keyword" content="RBI Data on Sectoral Deployment of Bank Credit" />
    <meta name="author " content="Reserve Bank of India" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onload="SetTreeStyles()">
    <form method="post" action="./Data_Sectoral_Deployment.aspx" id="form1">
<input type="hidden" name
Website of Reserve Bank of India </title>
    <meta name="description" content="Data on Sectoral Deployment of Bank Credit  - Reserve Bank of India" />
    <meta name="keyword" content="RBI Data on Sectoral Deployment of Bank Credit" />
    <meta name="author " content="Reserve Bank of India" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onload="SetTreeStyles()">
    <form method="post" action="./Data_Sectoral_Deployment.aspx" id="form1">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTEzOTM5OTAwNjkPZBYCAgEPZBYCAgMPFgIeBFRleHQFugw8dHI+PHRoIGNvbHNw
" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onload="SetTreeStyles()">
    <form method="post" action="./Data_Sectoral_Deployment.aspx" id="form1">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTEzOTM5OTAwNjkPZBYCAgEPZBYCAgMPFgIeBFRleHQFugw8dHI+PHRoIGNvbHNwYW49IjQiIGFsaWduPSJsZWZ0Ij5KdWwgMzEsIDIwMjY8L3RoPjwvdHI+PHRyPjx0ZCBzdHlsZT0nd29yZC13cmFwOmJyZWFrLXdvcmQ7d2lkdGg6NDUwOyc+PGEgY2xhc3M9J2xpbmsyJyBocmVmPUJTX1ByZXNzUmVsZWFzZURpc3BsYXkuYXNweD9wcmlkPTYzMjY3PlNlY3RvcmFsIERlcGxveW1lbnQgb2YgQmFuayBDcmVkaXQg4oCTIEp1bmUgMjAyNjwvYT48L3RkPjwvdHI+PHRyPjx0aCBjb2xzcGFuPSI0IiBhbGlnbj0ibGVmd
bs">
                <ul>
                    <li><a href="../Home.aspx">Home</a></li>
                    <li>Statistics</li><li><a href="Statistics.aspx">Data Releases</a></li>
					<li>Data on Sectoral Deployment of Bank Credit</li>
                </ul>
            </div>
            <div class="clear">
            </div>
            <div class="grid_11 omega right_blue_border">
                <div id="annual" class="text1">

                    <h2 class="page_title">
                        Data on Sectoral Deployment of Bank Credit</h2>
                    <div>
                        <table width="100%" border="0" align="center" cellpadding="0" ce

--- Deployment ---
Occurrences: 13
dtd">

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Data on Sectoral Deployment of Bank Credit | Official Website of Reserve Bank of India </title>
    <meta name="description" content="Data on Sectoral Deployment of Bank Credit  - Reserve Bank of India" />
    <meta name="keyword" content="RBI Data on Sectoral Deployment of Bank Credit" />
    <meta name="author " content="Reserve Bank of India" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onlo
ible" content="IE=edge,chrome=1" />
    <title>Data on Sectoral Deployment of Bank Credit | Official Website of Reserve Bank of India </title>
    <meta name="description" content="Data on Sectoral Deployment of Bank Credit  - Reserve Bank of India" />
    <meta name="keyword" content="RBI Data on Sectoral Deployment of Bank Credit" />
    <meta name="author " content="Reserve Bank of India" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onload="SetTreeStyles()">
    <form method="post" action="./Data_Sectoral_Deployment.aspx" id="form1">
<input type="hidden" name="__VIEWS
f Reserve Bank of India </title>
    <meta name="description" content="Data on Sectoral Deployment of Bank Credit  - Reserve Bank of India" />
    <meta name="keyword" content="RBI Data on Sectoral Deployment of Bank Credit" />
    <meta name="author " content="Reserve Bank of India" />
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onload="SetTreeStyles()">
    <form method="post" action="./Data_Sectoral_Deployment.aspx" id="form1">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTEzOTM5OTAwNjkPZBYCAgEPZBYCAgMPFgIeBFRleHQFugw8dHI+PHRoIGNvbHNwYW49IjQiI
="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onload="SetTreeStyles()">
    <form method="post" action="./Data_Sectoral_Deployment.aspx" id="form1">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTEzOTM5OTAwNjkPZBYCAgEPZBYCAgMPFgIeBFRleHQFugw8dHI+PHRoIGNvbHNwYW49IjQiIGFsaWduPSJsZWZ0Ij5KdWwgMzEsIDIwMjY8L3RoPjwvdHI+PHRyPjx0ZCBzdHlsZT0nd29yZC13cmFwOmJyZWFrLXdvcmQ7d2lkdGg6NDUwOyc+PGEgY2xhc3M9J2xpbmsyJyBocmVmPUJTX1ByZXNzUmVsZWFzZURpc3BsYXkuYXNweD9wcmlkPTYzMjY3PlNlY3RvcmFsIERlcGxveW1lbnQgb2YgQmFuayBDcmVkaXQg4oCTIEp1bmUgMjAyNjwvYT48L3RkPjwvdHI+PHRyPjx0aCBjb2xzcGFuPSI0IiBhbGlnbj0ibGVmdCI+SnVuID
             <ul>
                    <li><a href="../Home.aspx">Home</a></li>
                    <li>Statistics</li><li><a href="Statistics.aspx">Data Releases</a></li>
					<li>Data on Sectoral Deployment of Bank Credit</li>
                </ul>
            </div>
            <div class="clear">
            </div>
            <div class="grid_11 omega right_blue_border">
                <div id="annual" class="text1">

                    <h2 class="page_title">
                        Data on Sectoral Deployment of Bank Credit</h2>
                    <div>
                        <table width="100%" border="0" align="center" cellpadding="0" cellspacing

--- SIBC ---
Occurrences: 0

--- PR2019 ---
Occurrences: 0

--- PR1808 ---
Occurrences: 0

--- Data_Sectoral ---
Occurrences: 1
wport" content="width=device-width" />
    <script type="text/javascript" src="/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body onload="SetTreeStyles()">
    <form method="post" action="./Data_Sectoral_Deployment.aspx" id="form1">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwULLTEzOTM5OTAwNjkPZBYCAgEPZBYCAgMPFgIeBFRleHQFugw8dHI+PHRoIGNvbHNwYW49IjQiIGFsaWduPSJsZWZ0Ij5KdWwgMzEsIDIwMjY8L3RoPjwvdHI+PHRyPjx0ZCBzdHlsZT0nd29yZC13cmFwOmJyZWFrLXdvcmQ7d2lkdGg6NDUwOyc+PGEgY2xhc3M9J2xpbmsyJyBocmVmPUJTX1ByZXNzUmVsZWFzZURpc3BsYXkuYXNweD9wcmlkPTYzMjY3PlNlY3RvcmFsIERlcGxveW1lbnQgb2YgQmFuayBDcmVkaXQg4oCTIEp1bmUgMjAyNjwvYT48L3RkPjwvdHI+PHRyPjx0aCBjb2xzcGFuPSI0IiBhbGlnbj0i

In [21]:
import re

pattern = r'BS_PressReleaseDisplay\.aspx\?prid=(\d+)'

pr_ids = re.findall(pattern, response.text)

print("Number of press-release IDs found:", len(pr_ids))
print("First 20 IDs:")

for prid in pr_ids[:20]:
    print(prid)

Number of press-release IDs found: 7
First 20 IDs:
63267
63052
62827
62660
62467
62301
62135

In [22]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

prid = "63267"

press_url = (
    "https://rbi.org.in/Scripts/"
    f"BS_PressReleaseDisplay.aspx?prid={prid}"
)

press_response = requests.get(press_url, timeout=30)

print("Status code:", press_response.status_code)
print("Page size:", len(press_response.text))

Status code: 200
Page size: 113940

In [23]:
press_soup = BeautifulSoup(press_response.text, "html.parser")

excel_links = []

for a in press_soup.find_all("a", href=True):
    href = a["href"]
    text = a.get_text(" ", strip=True)

    if any(ext in href.lower() for ext in [".xls", ".xlsx"]):
        excel_links.append((text, urljoin(press_url, href)))

print("Excel links found:", len(excel_links))

for text, link in excel_links:
    print("TEXT:", text)
    print("LINK:", link)
    print("-" * 80)

Excel links found: 1
TEXT: Statements I and II
LINK: https://rbidocs.rbi.org.in/rdocs/content/docs/SIBCSJ26E31072026E.xlsx
--------------------------------------------------------------------------------

In [24]:
excel_url = excel_links[0][1]

excel_response = requests.get(excel_url, timeout=60)

print("Status code:", excel_response.status_code)
print("File size:", len(excel_response.content), "bytes")

Status code: 200
File size: 29707 bytes

In [25]:
import os

output_file = os.path.join(
    rbi_folder,
    "TEST_RBI_Statements_I_II.xlsx"
)

with open(output_file, "wb") as f:
    f.write(excel_response.content)

print("Saved:", output_file)
print("File exists:", os.path.exists(output_file))
print("File size:", os.path.getsize(output_file), "bytes")

Saved: /Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/RBI/TEST_RBI_Statements_I_II.xlsx
File exists: True
File size: 29707 bytes

In [26]:
test_file = os.path.join(
    rbi_folder,
    "TEST_RBI_Statements_I_II.xlsx"
)

test_excel = pd.ExcelFile(test_file)

print("Sheets:")
for sheet in test_excel.sheet_names:
    print("-", sheet)

Sheets:
- Statement 1
- Statement 2

In [27]:
# Find forms, buttons, and select controls used by the RBI archive

for tag in soup.find_all(["select", "option", "input", "button"]):
    text = tag.get_text(" ", strip=True)
    value = tag.get("value", "")
    name = tag.get("name", "")
    id_ = tag.get("id", "")
    
    if text or value or name or id_:
        print(
            tag.name,
            "| text:", text[:80],
            "| name:", name,
            "| id:", id_,
            "| value:", value[:80]
        )

input | text:  | name: __VIEWSTATE | id: __VIEWSTATE | value: /wEPDwULLTEzOTM5OTAwNjkPZBYCAgEPZBYCAgMPFgIeBFRleHQFugw8dHI+PHRoIGNvbHNwYW49IjQi
input | text:  | name: __VIEWSTATEGENERATOR | id: __VIEWSTATEGENERATOR | value: 6F282F78
input | text:  | name: __EVENTVALIDATION | id: __EVENTVALIDATION | value: /wEdAAv5KU3h25mmthmrtV3Ocq3ElK+XrsQEVyjeDxQ0A4GYXM3IfYFEMdbtkmb6zzJSc2CLrBfuDtX7
input | text:  | name: hdnYear | id: hdnYear | value:
input | text:  | name: UsrFontCntr$txtSearch | id: txtSearch | value:
button | text: Search | name:  | id: btnSearch | value:
input | text:  | name: UsrFontCntr$btn | id: btn | value:

In [28]:
# Find JavaScript references and code related to the archive/year selection

for line in response.text.splitlines():
    line_lower = line.lower()
    
    if any(keyword in line_lower for keyword in [
        "hdnyear",
        "year",
        "archive",
        "pressreleasedisplay"
    ]):
        print(line.strip())

<input type="hidden" name="hdnYear" id="hdnYear" />
<li><a href="/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#HP">Half-yearly Publications</a></li>
<li><a href="/scripts/BS_PressReleaseDisplay.aspx">Press Releases</a></li>
<li><a href="/scripts/Publications.aspx?publication=HalfYearly">Half-Yearly</a></li>
<tr><th colspan="4" align="left">Jul 31, 2026</th></tr><tr><td style='word-wrap:break-word;width:450;'><a class='link2' href=BS_PressReleaseDisplay.aspx?prid=63267>Sectoral Deployment of Bank Credit – June 2026</a></td></tr><tr><th colspan="4" align="left">Jun 30, 2026</th></tr><tr><td style='word-wrap:break-word;width:450;'><a class='link2' href=BS_PressReleaseDisplay.aspx?prid=63052>Sectoral Deployment of Bank Credit – May 2026</a></td></tr><tr><th colspan="4" align="left">May 29, 2026</th></tr><tr><td style='word-wrap:break-word;width:450;'><a class='link2' href=BS_PressReleaseDisplay.aspx?prid=62827>Sectoral Deployment of Bank Credit – April 2026</a></td></tr><tr><th colspan="4" align="left">Apr 30, 2026</th></tr><tr><td style='word-wrap:break-word;width:450;'><a class='link2' href=BS_PressReleaseDisplay.aspx?prid=62660>Sectoral Deployment of Bank Credit – March 2026</a></td></tr><tr><th colspan="4" align="left">Mar 30, 2026</th></tr><tr><td style='word-wrap:break-word;width:450;'><a class='link2' href=BS_PressReleaseDisplay.aspx?prid=62467>Sectoral Deployment of Bank Credit – February 2026</a></td></tr><tr><th colspan="4" align="left">Feb 27, 2026</th></tr><tr><td style='word-wrap:break-word;width:450;'><a class='link2' href=BS_PressReleaseDisplay.aspx?prid=62301>Sectoral Deployment of Bank Credit – January 2026</a></td></tr><tr><th colspan="4" align="left">Jan 30, 2026</th></tr><tr><td style='word-wrap:break-word;width:450;'><a class='link2' href=BS_PressReleaseDisplay.aspx?prid=62135>Sectoral Deployment of Bank Credit – December 2025</a></td></tr>
<div class="grid_1 archives alpha">
<span id="DateSettree_lbltree"><div class="grid_1 archives alpha" id="treeYear"><ul><li><a class="year" href="#" id="2026" onclick='GetYear("2026")'>2026</a></li><li><a class="year" href="#" id="2025" onclick='GetYear("2025")'>2025</a></li><li><a class="year" href="#" id="2024" onclick='GetYear("2024")'>2024</a></li><li><a class="year" href="#" id="2023" onclick='GetYear("2023")'>2023</a></li><li><a class="year" href="#" id="2022" onclick='GetYear("2022")'>2022</a></li><li><a class="year" href="#" id="2021" onclick='GetYear("2021")'>2021</a></li><li><a class="year" href="#" id="2020" onclick='GetYear("2020")'>2020</a></li><li><a class="year" href="#" id="2019" onclick='GetYear("2019")'>2019</a></li><li><a class="year" href="#" id="2018" onclick='GetYear("2018")'>2018</a></li><li><a class="year" href="#" id="2017" onclick='GetYear("2017")'>2017</a></li><h2 class="year"><a href="javascript:void(0);" id="divArchiveMain"  onclick="hideshow('divArchiveSub');" style="cursor: pointer;">Archives</a></h2><div  id="divArchiveSub" style="display: none;"><div class="grid_tree archives alpha" id="treeYear"><ul><li><a class="year" href="#" id="2016" onclick='GetYear("2016")'>2016</a></li><li><a class="year" href="#" id="2015" onclick='GetYear("2015")'>2015</a></li><li><a class="year" href="#" id="2014" onclick='GetYear("2014")'>2014</a></li><li><a class="year" href="#" id="2013" onclick='GetYear("2013")'>2013</a></li><li><a class="year" href="#" id="2012" onclick='GetYear("2012")'>2012</a></li><li><a class="year" href="#" id="2011" onclick='GetYear("2011")'>2011</a></li><li><a class="year" href="#" id="2010" onclick='GetYear("2010")'>2010</a></li></ul></div></div></div></span>
.year a
if($('#treeYear').height()>0){treeheight=$('#treeYear').height();}
else if(url.indexOf("financialeducation")>0 || url.indexOf("commonperson")>0 || url.indexOf("/rekyc/")>0 || url.indexOf("rbi90years")>0 ){
function GetYear(year) {
document.getElementById("hdnYear").value = year;
//Implemented onlick for 'archives' link in tree structure
function hideshow(divArchive) {
if (!document.getElementById(divArchive))
if (document.getElementById(divArchive).style.display == "block")
document.getElementById(divArchive).style.display = "none"
document.getElementById(divArchive).style.display = "block"
var strYear = document.getElementById("hdnYear").value;
if (strYear != "") {
document.getElementById(strYear).setAttribute("class", "year active");
document.getElementById(strYear).style.display = "block";
if (toDay.getFullYear() - 10 > parseInt(strYear)) { document.getElementById("divArchiveSub").style.display = "block" }

In [29]:
# Find archive/year references in the RBI page

html = response.text

for year in range(2010, 2027):
    if str(year) in html:
        print("Found year:", year)

Found year: 2010
Found year: 2011
Found year: 2012
Found year: 2013
Found year: 2014
Found year: 2015
Found year: 2016
Found year: 2017
Found year: 2018
Found year: 2019
Found year: 2020
Found year: 2021
Found year: 2022
Found year: 2023
Found year: 2024
Found year: 2025
Found year: 2026

In [30]:
import os
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from concurrent.futures import ThreadPoolExecutor, as_completed

# Use the 7 RBI release IDs we already discovered
pr_ids = [
    "63267",
    "63052",
    "62827",
    "62660",
    "62467",
    "62301",
    "62135"
]

download_folder = rbi_folder

def download_rbi_file(prid):
    try:
        # Open RBI press release
        press_url = (
            "https://rbi.org.in/Scripts/"
            f"BS_PressReleaseDisplay.aspx?prid={prid}"
        )

        r = requests.get(press_url, timeout=60)
        r.raise_for_status()

        soup = BeautifulSoup(r.text, "html.parser")

        # Find Statements I and II Excel file
        excel_url = None

        for a in soup.find_all("a", href=True):
            href = a["href"]
            text = a.get_text(" ", strip=True)

            if (
                "Statements I and II" in text
                and (".xlsx" in href.lower() or ".xls" in href.lower())
            ):
                excel_url = urljoin(press_url, href)
                break

        if not excel_url:
            return prid, "NO EXCEL LINK"

        # Get filename from URL
        filename = os.path.basename(excel_url.split("?")[0])
        output_path = os.path.join(download_folder, filename)

        # Skip if already downloaded
        if os.path.exists(output_path):
            return prid, f"ALREADY EXISTS: {filename}"

        # Download Excel
        file_response = requests.get(excel_url, timeout=60)
        file_response.raise_for_status()

        with open(output_path, "wb") as f:
            f.write(file_response.content)

        return prid, f"DOWNLOADED: {filename}"

    except Exception as e:
        return prid, f"ERROR: {e}"


print("Starting test batch...\n")

with ThreadPoolExecutor(max_workers=4) as executor:

    futures = [
        executor.submit(download_rbi_file, prid)
        for prid in pr_ids
    ]

    for future in as_completed(futures):
        prid, result = future.result()
        print(prid, "→", result)

print("\nTest batch completed.")

Starting test batch...

63267 → DOWNLOADED: SIBCSJ26E31072026E.xlsx
62827 → DOWNLOADED: SIBCS29052026.xlsx
62660 → DOWNLOADED: SIBCS30042026.xlsx
63052 → DOWNLOADED: SIBCS30062026.xlsx
62135 → ALREADY EXISTS: PR2019SIBC300126.xlsx
62301 → DOWNLOADED: SIBC27022026.xlsx
62467 → DOWNLOADED: SIBC30032026.xlsx

Test batch completed.

In [31]:
# Look for all RBI press-release display links in the current page source

all_pr_links = []

for a in soup.find_all("a", href=True):
    href = a["href"]
    text = a.get_text(" ", strip=True)

    if "BS_PressReleaseDisplay.aspx?prid=" in href:
        all_pr_links.append(
            (text, urljoin(url, href))
        )

print("Total release links found:", len(all_pr_links))

for text, link in all_pr_links:
    print(text, "→", link)

Total release links found: 7
Sectoral Deployment of Bank Credit – June 2026 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63267
Sectoral Deployment of Bank Credit – May 2026 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63052
Sectoral Deployment of Bank Credit – April 2026 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=62827
Sectoral Deployment of Bank Credit – March 2026 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=62660
Sectoral Deployment of Bank Credit – February 2026 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=62467
Sectoral Deployment of Bank Credit – January 2026 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=62301
Sectoral Deployment of Bank Credit – December 2025 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=62135

In [32]:
import os
import pandas as pd

# Target static mirror URL
url = "https://dbie.rbihub.in/banking/bank-credit-by-sector"

print("🔄 Fetching table structure from mirror site...")

try:
    # Read the data grid arrays directly from the pre-rendered HTML code
    tables = pd.read_html(url)
    
    # Isolate the main deployment breakdown matrix grid (usually the first table)
    df = tables[0]
    
    # Save cleanly as a local structured spreadsheet file 
    output_path = os.path.expanduser("~/Desktop/rbi_bank_credit_sectoral_mirror.xlsx")
    df.to_excel(output_path, index=False)
    
    print(f"✅ Success! Sectoral table downloaded to your Desktop: {output_path}")

except Exception as e:
    print(f"❌ Failed to extract tabular fields automatically: {e}")

🔄 Fetching table structure from mirror site...
❌ Failed to extract tabular fields automatically: Missing optional dependency 'html5lib'.  Use pip or conda to install html5lib.

In [33]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import re

# RBI archive page
archive_url = "https://systemhealth.rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx.html"

archive_response = requests.get(archive_url, timeout=60)

print("Status code:", archive_response.status_code)
print("Page size:", len(archive_response.text))

SSLError: HTTPSConnectionPool(host='systemhealth.rbi.org.in', port=443): Max retries exceeded with url: /Scripts/Data_Sectoral_Deployment.aspx.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)')))

In [34]:
import requests

archive_url = "https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx"

archive_response = requests.get(
    archive_url,
    timeout=60
)

print("Status code:", archive_response.status_code)
print("Page size:", len(archive_response.text))

Status code: 200
Page size: 66342

In [35]:
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import re

archive_soup = BeautifulSoup(archive_response.text, "html.parser")

# Find all links that contain year numbers
year_links = []

for a in archive_soup.find_all("a", href=True):
    text = a.get_text(" ", strip=True)
    href = a["href"]

    if re.search(r"\b(2015|2016|2017|2018|2019|2020|2021|2022|2023|2024)\b", text):
        year_links.append(
            (text, urljoin(archive_url, href))
        )

print("Possible historical year links:", len(year_links))

for text, link in year_links:
    print(text, "→", link)

Possible historical year links: 10
2024 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2023 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2022 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2021 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2020 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2019 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2018 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2017 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2016 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx
2015 → https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx

In [36]:
for a in archive_soup.find_all("a", href=True):
    text = a.get_text(" ", strip=True)

    if text in [str(y) for y in range(2015, 2025)]:
        print("YEAR:", text)
        print("HREF:", a["href"])
        print("ONCLICK:", a.get("onclick"))
        print("-" * 80)

YEAR: 2024
HREF: #
ONCLICK: GetYear("2024")
--------------------------------------------------------------------------------
YEAR: 2023
HREF: #
ONCLICK: GetYear("2023")
--------------------------------------------------------------------------------
YEAR: 2022
HREF: #
ONCLICK: GetYear("2022")
--------------------------------------------------------------------------------
YEAR: 2021
HREF: #
ONCLICK: GetYear("2021")
--------------------------------------------------------------------------------
YEAR: 2020
HREF: #
ONCLICK: GetYear("2020")
--------------------------------------------------------------------------------
YEAR: 2019
HREF: #
ONCLICK: GetYear("2019")
--------------------------------------------------------------------------------
YEAR: 2018
HREF: #
ONCLICK: GetYear("2018")
--------------------------------------------------------------------------------
YEAR: 2017
HREF: #
ONCLICK: GetYear("2017")
--------------------------------------------------------------------------------
YEAR: 2016
HREF: #
ONCLICK: GetYear("2016")
--------------------------------------------------------------------------------
YEAR: 2015
HREF: #
ONCLICK: GetYear("2015")
--------------------------------------------------------------------------------

In [37]:
# Find where the RBI page defines GetYear()

for script in archive_soup.find_all("script"):
    script_text = script.get_text()

    if "GetYear" in script_text:
        print(script_text)
        print("\n" + "=" * 100 + "\n")

    function GetYear(year) {

        document.getElementById("hdnYear").value = year;
        document.getElementById("btn").click();

    }

    //Implemented onlick for 'archives' link in tree structure
    function hideshow(divArchive) {
        if (!document.getElementById(divArchive))
            return
        if (document.getElementById(divArchive).style.display == "block")
            document.getElementById(divArchive).style.display = "none"
        else
            document.getElementById(divArchive).style.display = "block"
    }

    function SetTreeStyles() {

        var strYear = document.getElementById("hdnYear").value;
        if (strYear != "") {
            var toDay = new Date();
            document.getElementById(strYear).setAttribute("class", "year active");
            document.getElementById(strYear).style.display = "block";
            if (toDay.getFullYear() - 10 > parseInt(strYear)) { document.getElementById("divArchiveSub").style.display = "block" }
        }
    }


====================================================================================================

In [38]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# Create a session so RBI keeps the same connection/cookies
session = requests.Session()

# Get the RBI archive page first
get_response = session.get(
    archive_url,
    timeout=60
)

get_soup = BeautifulSoup(get_response.text, "html.parser")

# Collect all hidden ASP.NET form fields
post_data = {}

for inp in get_soup.select("input[type=hidden]"):
    name = inp.get("name")
    value = inp.get("value", "")

    if name:
        post_data[name] = value

# Tell RBI which year we want
post_data["hdnYear"] = "2024"

# This is the button that GetYear() clicks
post_data["UsrFontCntr$btn"] = ""

# Submit the form
year_response = session.post(
    archive_url,
    data=post_data,
    timeout=60
)

print("Status code:", year_response.status_code)
print("Page size:", len(year_response.text))

# Parse returned page
year_soup = BeautifulSoup(year_response.text, "html.parser")

# Find press-release links
release_links = []

for a in year_soup.find_all("a", href=True):
    href = a["href"]
    text = a.get_text(" ", strip=True)

    if "BS_PressReleaseDisplay.aspx?prid=" in href:
        release_links.append(
            (text, urljoin(archive_url, href))
        )

print("Press-release links found:", len(release_links))

for text, link in release_links:
    print(text, "→", link)

Status code: 200
Page size: 67454
Press-release links found: 12
Sectoral Deployment of Bank Credit – November 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59430
Sectoral Deployment of Bank Credit – October 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59209
Sectoral Deployment of Bank Credit – September 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59005
Sectoral Deployment of Bank Credit – August 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58785
Sectoral Deployment of Bank Credit – July 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58601
Sectoral Deployment of Bank Credit – June 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58400
Sectoral Deployment of Bank Credit – May 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58178
Sectoral Deployment of Bank Credit – April 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58010
Sectoral Deployment of Bank Credit – March 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57816
Sectoral Deployment of Bank Credit – February 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57589
Sectoral Deployment of Bank Credit – January 2024 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57418
Sectoral Deployment of Bank Credit – December 2023 → https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57223

In [39]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import re
import time

archive_url = "https://rbi.org.in/Scripts/Data_Sectoral_Deployment.aspx"

session = requests.Session()

all_releases = {}

years = list(range(2015, 2025))

for year in years:

    print(f"\nCollecting {year}...")

    # Get fresh page for each year
    response = session.get(
        archive_url,
        timeout=60
    )

    soup = BeautifulSoup(response.text, "html.parser")

    # Collect hidden ASP.NET fields
    post_data = {}

    for inp in soup.select("input[type=hidden]"):
        name = inp.get("name")
        value = inp.get("value", "")

        if name:
            post_data[name] = value

    # Select year
    post_data["hdnYear"] = str(year)
    post_data["UsrFontCntr$btn"] = ""

    # Submit year selection
    response_year = session.post(
        archive_url,
        data=post_data,
        timeout=60
    )

    year_soup = BeautifulSoup(response_year.text, "html.parser")

    releases = []

    for a in year_soup.find_all("a", href=True):

        href = a["href"]
        text = a.get_text(" ", strip=True)

        if "BS_PressReleaseDisplay.aspx?prid=" in href:

            full_url = urljoin(archive_url, href)

            # Extract release ID
            match = re.search(r"prid=(\d+)", full_url)

            if match:
                prid = match.group(1)

                releases.append({
                    "year": year,
                    "title": text,
                    "prid": prid,
                    "url": full_url
                })

    all_releases[year] = releases

    print(f"  Releases found: {len(releases)}")

    for r in releases:
        print(f"    {r['prid']} → {r['title']}")

    time.sleep(0.5)


print("\n" + "=" * 70)
print("COLLECTION SUMMARY")
print("=" * 70)

total = sum(len(v) for v in all_releases.values())

print("Years processed:", len(all_releases))
print("Total releases found:", total)

for year, releases in all_releases.items():
    print(year, "→", len(releases))

Collecting 2015...
  Releases found: 12
    35856 → Sectoral Deployment of Bank Credit – November 2015
    35590 → Sectoral Deployment of Bank Credit – October 2015
    35362 → Sectoral Deployment of Bank Credit – September 2015
    35117 → Sectoral Deployment of Bank Credit – August 2015
    34876 → Sectoral Deployment of Bank Credit – July 2015
    34600 → Sectoral Deployment of Bank Credit – June 2015
    34329 → Sectoral Deployment of Bank Credit – May 2015
    34060 → Sectoral Deployment of Bank Credit – April 2015
    33834 → Sectoral Deployment of Bank Credit – March  2015
    33594 → Sectoral Deployment of Bank Credit – February 2015
    33350 → Sectoral Deployment of Bank Credit – January 2015
    33149 → Sectoral Deployment of Bank Credit – December 2014

Collecting 2016...
  Releases found: 12
    39102 → Sectoral Deployment of Bank Credit – November 2016
    38753 → Sectoral Deployment of Bank Credit – October 2016
    38458 → Sectoral Deployment of Bank Credit – September 2016
    38204 → Sectoral Deployment of Bank Credit – August 2016
    37935 → Sectoral Deployment of Bank Credit – July 2016
    37645 → Sectoral Deployment of Bank Credit – June 2016
    37374 → Sectoral Deployment of Bank Credit – May 2016
    37103 → Sectoral Deployment of Bank Credit – April 2016
    36858 → Sectoral Deployment of Bank Credit – March 2016
    36634 → Sectoral Deployment of Bank Credit – February 2016
    36360 → Sectoral Deployment of Bank Credit – January 2016
    36109 → Sectoral Deployment of Bank Credit –December 2015

Collecting 2017...
  Releases found: 13
    42710 → Sectoral Deployment of Bank Credit – November 2017
    42427 → Sectoral Deployment of Bank Credit – October 2017
    42123 → Sectoral Deployment of Bank Credit – September 2017
    41822 → Sectoral Deployment of Bank Credit – August 2017
    41527 → Sectoral Deployment of Bank Credit – July 2017
    41229 → Sectoral Deployment of Bank Credit – June 2017
    40926 → Sectoral Deployment of Bank Credit – Revised Data for April 2017
    40923 → Sectoral Deployment of Bank Credit – May 2017
    40667 → Sectoral Deployment of Bank Credit – April 2017
    40321 → Sectoral Deployment of Bank Credit – March 2017
    40019 → Sectoral Deployment of Bank Credit – February 2017
    39692 → Sectoral Deployment of Bank Credit – January 2017
    39420 → Sectoral Deployment of Bank Credit – December 2016

Collecting 2018...
  Releases found: 12
    45861 → Sectoral Deployment of Bank Credit – November 2018
    45616 → Sectoral Deployment of Bank Credit – October 2018
    45374 → Sectoral Deployment of Bank Credit – September 2018
    45094 → Sectoral Deployment of Bank Credit – August 2018
    44877 → Sectoral Deployment of Bank Credit – July 2018
    44625 → Sectoral Deployment of Bank Credit – June 2018
    44351 → Sectoral Deployment of Bank Credit – May 2018
    44074 → Sectoral Deployment of Bank Credit – April 2018
    43790 → Sectoral Deployment of Bank Credit – March 2018
    43517 → Sectoral Deployment of Bank Credit – February 2018
    43258 → Sectoral Deployment of Bank Credit – January 2018
    43013 → Sectoral Deployment of Bank Credit – December 2017

Collecting 2019...
  Releases found: 12
    49011 → Sectoral Deployment of Bank Credit - November 2019
    48751 → Sectoral Deployment of Bank Credit – October 2019
    48522 → Sectoral Deployment of Bank Credit – September 2019
    48277 → Sectoral Deployment of Bank Credit – August 2019
    48033 → Sectoral Deployment of Bank Credit – July 2019
    47750 → Sectoral Deployment of Bank Credit – June 2019
    47443 → Sectoral Deployment of Bank Credit – May 2019
    47185 → Sectoral Deployment of Bank Credit – April 2019
    46928 → Sectoral Deployment of Bank Credit – March 2019
    46676 → Sectoral Deployment of Bank Credit – February 2019
    46421 → Sectoral Deployment of Bank Credit – January 2019 (Revised on March 08, 2019)
    46162 → Sectoral Deployment of Bank Credit – December 2018

Collecting 2020...
  Releases found: 12
    50891 → Sectoral Deployment of Bank Credit – November 2020
    50726 → Sectoral Deployment of Bank Credit – October 2020
    50595 → Sectoral Deployment of Bank Credit – September 2020
    50442 → Sectoral Deployment of Bank Credit – August 2020
    50293 → Sectoral Deployment of Bank Credit – July 2020
    50152 → Sectoral Deployment of Bank Credit – June 2020
    50023 → Sectoral Deployment of Bank Credit – May 2020
    49875 → Sectoral Deployment of Bank Credit – April 2020
    49750 → Sectoral Deployment of Bank Credit – March 2020
    49611 → Sectoral Deployment of Bank Credit – February 2020
    49453 → Sectoral Deployment of Bank Credit-January 2020
    49296 → Sectoral Deployment of Bank Credit - December 2019

Collecting 2021...
  Releases found: 12
    53012 → Sectoral Deployment of Bank Credit – November 2021
    52646 → Sectoral Deployment of Bank Credit – October 2021
    52483 → Sectoral Deployment of Bank Credit – September 2021
    52325 → Sectoral Deployment of Bank Credit – August 2021
    52149 → Sectoral Deployment of Bank Credit – July 2021
    51979 → Sectoral Deployment of Bank Credit – June 2021
    51823 → Sectoral Deployment of Bank Credit – May 2021
    51658 → Sectoral Deployment of Bank Credit – April 2021
    51507 → Sectoral Deployment of Bank Credit – March 2021
    51359 → Sectoral Deployment of Bank Credit – February 2021
    51195 → Sectoral Deployment of Bank Credit – January 2021
    51043 → Sectoral Deployment of Bank Credit – December 2020

Collecting 2022...
  Releases found: 12
    54963 → Sectoral Deployment of Bank Credit – November 2022
    54779 → Sectoral Deployment of Bank Credit – October 2022
    54615 → Sectoral Deployment of Bank Credit – September 2022
    54476 → Sectoral Deployment of Bank Credit – August 2022
    54289 → Sectoral Deployment of Bank Credit – July 2022
    54119 → Sectoral Deployment of Bank Credit – June 2022
    53942 → Sectoral Deployment of Bank Credit – May 2022
    53783 → Sectoral Deployment of Bank Credit – April 2022
    53631 → Sectoral Deployment of Bank Credit – March 2022
    53491 → Sectoral Deployment of Bank Credit – February 2022
    53345 → Sectoral Deployment of Bank Credit – January 2022
    53197 → Sectoral Deployment of Bank Credit – December 2021

Collecting 2023...
  Releases found: 12
    57027 → Sectoral Deployment of Bank Credit – November 2023
    56821 → Sectoral Deployment of Bank Credit – October 2023
    56659 → Sectoral Deployment of Bank Credit – September 2023
    56463 → Sectoral Deployment of Bank Credit – August 2023
    56292 → Sectoral Deployment of Bank Credit – July 2023
    56126 → Sectoral Deployment of Bank Credit – June 2023
    55952 → Sectoral Deployment of Bank Credit – May 2023
    55760 → Sectoral Deployment of Bank Credit – April 2023
    55589 → Sectoral Deployment of Bank Credit – March 2023
    55439 → Sectoral Deployment of Bank Credit – February 2023
    55299 → Sectoral Deployment of Bank Credit – January 2023
    55137 → Sectoral Deployment of Bank Credit – December 2022

Collecting 2024...
  Releases found: 12
    59430 → Sectoral Deployment of Bank Credit – November 2024
    59209 → Sectoral Deployment of Bank Credit – October 2024
    59005 → Sectoral Deployment of Bank Credit – September 2024
    58785 → Sectoral Deployment of Bank Credit – August 2024
    58601 → Sectoral Deployment of Bank Credit – July 2024
    58400 → Sectoral Deployment of Bank Credit – June 2024
    58178 → Sectoral Deployment of Bank Credit – May 2024
    58010 → Sectoral Deployment of Bank Credit – April 2024
    57816 → Sectoral Deployment of Bank Credit – March 2024
    57589 → Sectoral Deployment of Bank Credit – February 2024
    57418 → Sectoral Deployment of Bank Credit – January 2024
    57223 → Sectoral Deployment of Bank Credit – December 2023

======================================================================
COLLECTION SUMMARY
======================================================================
Years processed: 10
Total releases found: 121
2015 → 12
2016 → 12
2017 → 13
2018 → 12
2019 → 12
2020 → 12
2021 → 12
2022 → 12
2023 → 12
2024 → 12

In [40]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import re

# Test with the first 5 releases
test_releases = []

for year in sorted(all_releases.keys()):
    for release in all_releases[year]:
        test_releases.append(release)

        if len(test_releases) == 5:
            break

    if len(test_releases) == 5:
        break


print("Testing Excel discovery on:")
for r in test_releases:
    print(r["prid"], "→", r["title"])


def find_excel_links(release_url):
    
    response = session.get(
        release_url,
        timeout=60
    )
    
    soup = BeautifulSoup(response.text, "html.parser")
    
    excel_links = []
    
    for a in soup.find_all("a", href=True):
        
        href = a["href"]
        text = a.get_text(" ", strip=True)
        
        full_url = urljoin(release_url, href)
        
        if (
            ".xlsx" in full_url.lower()
            or ".xls" in full_url.lower()
        ):
            excel_links.append({
                "text": text,
                "url": full_url
            })
    
    return excel_links


print("\n" + "=" * 70)
print("EXCEL DISCOVERY TEST")
print("=" * 70)

for r in test_releases:
    
    links = find_excel_links(r["url"])
    
    print(f"\n{r['prid']} → {r['title']}")
    print("Excel links found:", len(links))
    
    for link in links:
        print("  TEXT:", link["text"])
        print("  URL :", link["url"])

Testing Excel discovery on:
35856 → Sectoral Deployment of Bank Credit – November 2015
35590 → Sectoral Deployment of Bank Credit – October 2015
35362 → Sectoral Deployment of Bank Credit – September 2015
35117 → Sectoral Deployment of Bank Credit – August 2015
34876 → Sectoral Deployment of Bank Credit – July 2015

======================================================================
EXCEL DISCOVERY TEST
======================================================================

35856 → Sectoral Deployment of Bank Credit – November 2015
Excel links found: 1
  TEXT: Statements I and II
  URL : http://rbidocs.rbi.org.in/rdocs/content/docs/PR1539SD311215.xls

35590 → Sectoral Deployment of Bank Credit – October 2015
Excel links found: 1
  TEXT: Statements I and II
  URL : http://rbidocs.rbi.org.in/rdocs/content/docs/PR1273S1115.xls

35362 → Sectoral Deployment of Bank Credit – September 2015
Excel links found: 1
  TEXT: Statements I and II
  URL : http://rbidocs.rbi.org.in/rdocs/content/docs/PR10423010AS.xls

35117 → Sectoral Deployment of Bank Credit – August 2015
Excel links found: 1
  TEXT: Statements I and II
  URL : http://rbidocs.rbi.org.in/rdocs/content/docs/IPR8000915FST.xls

34876 → Sectoral Deployment of Bank Credit – July 2015
Excel links found: 1
  TEXT: Statements I and II
  URL : http://rbidocs.rbi.org.in/rdocs/content/docs/IEPR559020915_SD1.xls

In [41]:
import os
import re
import time
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, urlparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ============================================================
# CONFIGURATION
# ============================================================

RBI_FOLDER = (
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/"
    "RBI"
)

os.makedirs(RBI_FOLDER, exist_ok=True)

# Number of simultaneous downloads
MAX_WORKERS = 8

# ============================================================
# SESSION CONFIGURATION
# ============================================================

def create_session():

    s = requests.Session()

    retry = Retry(
        total=3,
        connect=3,
        read=3,
        backoff_factor=1,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"]
    )

    adapter = HTTPAdapter(
        max_retries=retry,
        pool_connections=MAX_WORKERS,
        pool_maxsize=MAX_WORKERS
    )

    s.mount("https://", adapter)
    s.mount("http://", adapter)

    s.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X) "
            "AppleWebKit/605.1.15 Safari/605.1.15"
        )
    })

    return s


# ============================================================
# FIND EXCEL FILE
# ============================================================

def find_excel_link(release):

    session_local = create_session()

    try:

        response = session_local.get(
            release["url"],
            timeout=60
        )

        response.raise_for_status()

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        candidates = []

        for a in soup.find_all("a", href=True):

            href = a["href"]
            text = a.get_text(" ", strip=True)

            full_url = urljoin(
                release["url"],
                href
            )

            lower_url = full_url.lower()

            # Prefer the Statements I and II link
            if (
                ".xlsx" in lower_url
                or ".xls" in lower_url
            ):

                score = 0

                if "statement" in text.lower():
                    score += 10

                if "statements i and ii" in text.lower():
                    score += 20

                candidates.append(
                    (score, text, full_url)
                )

        if not candidates:

            return {
                **release,
                "excel_url": None,
                "status": "NO_EXCEL_LINK"
            }

        # Highest score first
        candidates.sort(
            key=lambda x: x[0],
            reverse=True
        )

        _, text, excel_url = candidates[0]

        return {
            **release,
            "excel_url": excel_url,
            "excel_text": text,
            "status": "EXCEL_FOUND"
        }

    except Exception as e:

        return {
            **release,
            "excel_url": None,
            "status": f"DISCOVERY_ERROR: {e}"
        }


# ============================================================
# DOWNLOAD FILE
# ============================================================

def download_file(item):

    excel_url = item["excel_url"]

    if not excel_url:

        return {
            **item,
            "download_status": "NO_URL"
        }

    try:

        # Extract filename from URL
        parsed = urlparse(excel_url)

        filename = os.path.basename(
            parsed.path
        )

        # Clean filename if necessary
        filename = re.sub(
            r'[<>:"/\\|?*]',
            "_",
            filename
        )

        if not filename:
            filename = f"RBI_{item['prid']}.xls"

        filepath = os.path.join(
            RBI_FOLDER,
            filename
        )

        # Skip existing files
        if os.path.exists(filepath):

            return {
                **item,
                "filename": filename,
                "filepath": filepath,
                "download_status": "ALREADY_EXISTS"
            }

        session_local = create_session()

        response = session_local.get(
            excel_url,
            timeout=120,
            allow_redirects=True
        )

        response.raise_for_status()

        # Basic validation
        content = response.content

        if len(content) < 1000:

            return {
                **item,
                "filename": filename,
                "download_status": "SUSPICIOUS_SMALL_FILE",
                "size": len(content)
            }

        with open(filepath, "wb") as f:
            f.write(content)

        return {
            **item,
            "filename": filename,
            "filepath": filepath,
            "download_status": "DOWNLOADED",
            "size": len(content)
        }

    except Exception as e:

        return {
            **item,
            "download_status": f"DOWNLOAD_ERROR: {e}"
        }


# ============================================================
# STEP 1 — DISCOVER EXCEL LINKS
# ============================================================

print("=" * 80)
print("STEP 1 — DISCOVERING RBI EXCEL FILES")
print("=" * 80)

release_list = []

for year in sorted(all_releases.keys()):

    for release in all_releases[year]:

        release_list.append(release)


print("Total RBI releases:", len(release_list))
print()

excel_items = []

with ThreadPoolExecutor(
    max_workers=MAX_WORKERS
) as executor:

    futures = {
        executor.submit(
            find_excel_link,
            release
        ): release
        for release in release_list
    }

    completed = 0

    for future in as_completed(futures):

        result = future.result()

        excel_items.append(result)

        completed += 1

        print(
            f"[{completed}/{len(release_list)}] "
            f"{result['prid']} → {result['status']}"
        )


# ============================================================
# SORT RESULTS
# ============================================================

excel_items.sort(
    key=lambda x: (
        x.get("year", 0),
        x.get("prid", "")
    )
)

found = [
    x for x in excel_items
    if x["status"] == "EXCEL_FOUND"
]

not_found = [
    x for x in excel_items
    if x["status"] != "EXCEL_FOUND"
]


print()
print("=" * 80)
print("EXCEL DISCOVERY SUMMARY")
print("=" * 80)

print("Total releases:", len(excel_items))
print("Excel files found:", len(found))
print("Excel files NOT found:", len(not_found))


if not_found:

    print("\nFiles requiring investigation:")

    for x in not_found:

        print(
            x["year"],
            x["prid"],
            x["title"],
            "→",
            x["status"]
        )


# ============================================================
# STEP 2 — DOWNLOAD
# ============================================================

print()
print("=" * 80)
print("STEP 2 — DOWNLOADING RBI EXCEL FILES")
print("=" * 80)

download_results = []

with ThreadPoolExecutor(
    max_workers=MAX_WORKERS
) as executor:

    futures = {
        executor.submit(
            download_file,
            item
        ): item
        for item in found
    }

    completed = 0

    for future in as_completed(futures):

        result = future.result()

        download_results.append(result)

        completed += 1

        print(
            f"[{completed}/{len(found)}] "
            f"{result['prid']} → "
            f"{result['download_status']}"
        )


# ============================================================
# FINAL SUMMARY
# ============================================================

downloaded = [
    x for x in download_results
    if x["download_status"] == "DOWNLOADED"
]

existing = [
    x for x in download_results
    if x["download_status"] == "ALREADY_EXISTS"
]

errors = [
    x for x in download_results
    if x["download_status"] not in [
        "DOWNLOADED",
        "ALREADY_EXISTS"
    ]
]


print()
print("=" * 80)
print("FINAL RBI DOWNLOAD SUMMARY")
print("=" * 80)

print("Total releases:", len(release_list))
print("Excel files found:", len(found))
print("Downloaded now:", len(downloaded))
print("Already existed:", len(existing))
print("Errors:", len(errors))

print()
print("RBI raw-data folder:")
print(RBI_FOLDER)

print()
print("Collection complete.")

================================================================================
STEP 1 — DISCOVERING RBI EXCEL FILES
================================================================================
Total RBI releases: 121

[1/121] 34329 → EXCEL_FOUND
[2/121] 35117 → EXCEL_FOUND
[3/121] 35590 → EXCEL_FOUND
[4/121] 34060 → EXCEL_FOUND
[5/121] 34600 → EXCEL_FOUND
[6/121] 34876 → EXCEL_FOUND
[7/121] 35362 → EXCEL_FOUND
[8/121] 35856 → EXCEL_FOUND
[9/121] 33834 → EXCEL_FOUND
[10/121] 33594 → EXCEL_FOUND
[11/121] 33149 → EXCEL_FOUND
[12/121] 38458 → EXCEL_FOUND
[13/121] 38753 → EXCEL_FOUND
[14/121] 33350 → EXCEL_FOUND
[15/121] 39102 → EXCEL_FOUND
[16/121] 38204 → EXCEL_FOUND
[17/121] 37645 → EXCEL_FOUND
[18/121] 37103 → EXCEL_FOUND
[19/121] 36858 → EXCEL_FOUND
[20/121] 37935 → EXCEL_FOUND
[21/121] 36360 → EXCEL_FOUND
[22/121] 36109 → EXCEL_FOUND
[23/121] 36634 → EXCEL_FOUND
[24/121] 42710 → EXCEL_FOUND
[25/121] 41822 → EXCEL_FOUND
[26/121] 42427 → EXCEL_FOUND
[27/121] 41229 → EXCEL_FOUND
[28/121] 41527 → EXCEL_FOUND
[29/121] 42123 → EXCEL_FOUND
[30/121] 40926 → EXCEL_FOUND
[31/121] 37374 → EXCEL_FOUND
[32/121] 40667 → EXCEL_FOUND
[33/121] 40321 → EXCEL_FOUND
[34/121] 40923 → EXCEL_FOUND
[35/121] 45861 → EXCEL_FOUND
[36/121] 40019 → EXCEL_FOUND
[37/121] 39420 → EXCEL_FOUND
[38/121] 39692 → EXCEL_FOUND
[39/121] 45616 → EXCEL_FOUND
[40/121] 44877 → EXCEL_FOUND
[41/121] 43790 → EXCEL_FOUND
[42/121] 44351 → EXCEL_FOUND
[43/121] 44074 → EXCEL_FOUND
[44/121] 43517 → EXCEL_FOUND
[45/121] 43258 → EXCEL_FOUND
[46/121] 48751 → EXCEL_FOUND
[47/121] 49011 → EXCEL_FOUND
[48/121] 48522 → EXCEL_FOUND
[49/121] 43013 → EXCEL_FOUND
[50/121] 48277 → EXCEL_FOUND
[51/121] 45374 → EXCEL_FOUND
[52/121] 45094 → EXCEL_FOUND
[53/121] 47750 → EXCEL_FOUND
[54/121] 48033 → EXCEL_FOUND
[55/121] 44625 → EXCEL_FOUND
[56/121] 47443 → EXCEL_FOUND
[57/121] 46421 → EXCEL_FOUND
[58/121] 46676 → EXCEL_FOUND
[59/121] 46928 → EXCEL_FOUND
[60/121] 50891 → EXCEL_FOUND
[61/121] 50726 → EXCEL_FOUND
[62/121] 46162 → EXCEL_FOUND
[63/121] 50595 → EXCEL_FOUND
[64/121] 50442 → EXCEL_FOUND
[65/121] 50152 → EXCEL_FOUND
[66/121] 50023 → EXCEL_FOUND
[67/121] 47185 → EXCEL_FOUND
[68/121] 50293 → EXCEL_FOUND
[69/121] 49875 → EXCEL_FOUND
[70/121] 49750 → EXCEL_FOUND
[71/121] 49611 → EXCEL_FOUND
[72/121] 53012 → EXCEL_FOUND
[73/121] 52483 → EXCEL_FOUND
[74/121] 52325 → EXCEL_FOUND
[75/121] 52646 → EXCEL_FOUND
[76/121] 49296 → EXCEL_FOUND
[77/121] 51979 → EXCEL_FOUND
[78/121] 51195 → EXCEL_FOUND
[79/121] 51359 → EXCEL_FOUND
[80/121] 51823 → EXCEL_FOUND
[81/121] 51658 → EXCEL_FOUND
[82/121] 51507 → EXCEL_FOUND
[83/121] 51043 → EXCEL_FOUND
[84/121] 49453 → EXCEL_FOUND
[85/121] 54476 → EXCEL_FOUND
[86/121] 54779 → EXCEL_FOUND
[87/121] 52149 → EXCEL_FOUND
[88/121] 54615 → EXCEL_FOUND
[89/121] 54963 → EXCEL_FOUND
[90/121] 54289 → EXCEL_FOUND
[91/121] 54119 → EXCEL_FOUND
[92/121] 53942 → EXCEL_FOUND
[93/121] 53631 → EXCEL_FOUND
[94/121] 53491 → EXCEL_FOUND
[95/121] 53345 → EXCEL_FOUND
[96/121] 53783 → EXCEL_FOUND
[97/121] 53197 → EXCEL_FOUND
[98/121] 57027 → EXCEL_FOUND
[99/121] 56821 → EXCEL_FOUND
[100/121] 56659 → EXCEL_FOUND
[101/121] 56463 → EXCEL_FOUND
[102/121] 56292 → EXCEL_FOUND
[103/121] 56126 → EXCEL_FOUND
[104/121] 55952 → EXCEL_FOUND
[105/121] 55760 → EXCEL_FOUND
[106/121] 55439 → EXCEL_FOUND
[107/121] 55589 → EXCEL_FOUND
[108/121] 55299 → EXCEL_FOUND
[109/121] 59209 → EXCEL_FOUND
[110/121] 55137 → EXCEL_FOUND
[111/121] 58785 → EXCEL_FOUND
[112/121] 59430 → EXCEL_FOUND
[113/121] 59005 → EXCEL_FOUND
[114/121] 58178 → EXCEL_FOUND
[115/121] 58400 → EXCEL_FOUND
[116/121] 57816 → EXCEL_FOUND
[117/121] 58010 → EXCEL_FOUND
[118/121] 57589 → EXCEL_FOUND
[119/121] 57418 → EXCEL_FOUND
[120/121] 57223 → EXCEL_FOUND
[121/121] 58601 → EXCEL_FOUND

================================================================================
EXCEL DISCOVERY SUMMARY
================================================================================
Total releases: 121
Excel files found: 121
Excel files NOT found: 0

================================================================================
STEP 2 — DOWNLOADING RBI EXCEL FILES
================================================================================
[1/121] 34600 → DOWNLOADED
[2/121] 33834 → DOWNLOADED
[3/121] 34329 → DOWNLOADED
[4/121] 33594 → DOWNLOADED
[5/121] 33350 → DOWNLOADED
[6/121] 34060 → DOWNLOADED
[7/121] 33149 → DOWNLOADED
[8/121] 36360 → DOWNLOADED
[9/121] 35117 → DOWNLOADED
[10/121] 35590 → DOWNLOADED
[11/121] 35856 → DOWNLOADED
[12/121] 36109 → DOWNLOADED
[13/121] 36634 → DOWNLOADED
[14/121] 35362 → DOWNLOADED
[15/121] 37374 → DOWNLOADED
[16/121] 37103 → DOWNLOADED
[17/121] 36858 → DOWNLOADED
[18/121] 38458 → DOWNLOADED
[19/121] 37645 → DOWNLOADED
[20/121] 38204 → DOWNLOADED
[21/121] 39102 → DOWNLOADED
[22/121] 40019 → DOWNLOADED
[23/121] 40321 → DOWNLOADED
[24/121] 39420 → DOWNLOADED
[25/121] 38753 → DOWNLOADED
[26/121] 34876 → DOWNLOADED
[27/121] 40923 → DOWNLOADED
[28/121] 40926 → DOWNLOADED
[29/121] 40667 → DOWNLOADED
[30/121] 41527 → DOWNLOADED
[31/121] 41229 → DOWNLOADED
[32/121] 41822 → DOWNLOADED
[33/121] 42123 → DOWNLOADED
[34/121] 37935 → DOWNLOADED
[35/121] 42710 → DOWNLOADED
[36/121] 43258 → DOWNLOADED
[37/121] 43013 → DOWNLOADED
[38/121] 43517 → DOWNLOADED
[39/121] 43790 → DOWNLOADED
[40/121] 44074 → DOWNLOADED
[41/121] 44351 → DOWNLOADED
[42/121] 44625 → DOWNLOADED
[43/121] 45094 → DOWNLOADED
[44/121] 44877 → DOWNLOADED
[45/121] 39692 → DOWNLOADED
[46/121] 45616 → DOWNLOADED
[47/121] 45374 → DOWNLOADED
[48/121] 45861 → DOWNLOADED
[49/121] 46162 → DOWNLOADED
[50/121] 46421 → DOWNLOADED
[51/121] 46676 → DOWNLOADED
[52/121] 47750 → DOWNLOADED
[53/121] 47443 → DOWNLOADED
[54/121] 47185 → DOWNLOADED
[55/121] 46928 → DOWNLOADED
[56/121] 48277 → DOWNLOADED
[57/121] 48033 → DOWNLOADED
[58/121] 48522 → DOWNLOADED
[59/121] 48751 → DOWNLOADED
[60/121] 42427 → DOWNLOADED
[61/121] 49611 → DOWNLOADED
[62/121] 49011 → DOWNLOADED
[63/121] 49453 → DOWNLOADED
[64/121] 49875 → DOWNLOADED
[65/121] 50023 → DOWNLOADED
[66/121] 50152 → DOWNLOADED
[67/121] 50293 → DOWNLOADED
[68/121] 50442 → DOWNLOADED
[69/121] 50595 → DOWNLOADED
[70/121] 50891 → DOWNLOADED
[71/121] 50726 → DOWNLOADED
[72/121] 51043 → DOWNLOADED
[73/121] 51195 → DOWNLOADED
[74/121] 51359 → DOWNLOADED
[75/121] 51507 → DOWNLOADED
[76/121] 51823 → DOWNLOADED
[77/121] 51658 → DOWNLOADED
[78/121] 51979 → DOWNLOADED
[79/121] 52149 → DOWNLOADED
[80/121] 52325 → DOWNLOADED
[81/121] 52483 → DOWNLOADED
[82/121] 52646 → DOWNLOADED
[83/121] 53012 → DOWNLOADED
[84/121] 53197 → DOWNLOADED
[85/121] 53345 → DOWNLOADED
[86/121] 53942 → DOWNLOADED
[87/121] 49296 → DOWNLOADED
[88/121] 53783 → DOWNLOADED
[89/121] 49750 → DOWNLOADED
[90/121] 54119 → DOWNLOADED
[91/121] 54289 → DOWNLOADED
[92/121] 54476 → DOWNLOADED
[93/121] 54615 → DOWNLOADED
[94/121] 54779 → DOWNLOADED
[95/121] 54963 → DOWNLOADED
[96/121] 55137 → DOWNLOADED
[97/121] 55299 → DOWNLOADED
[98/121] 55439 → DOWNLOADED
[99/121] 55589 → DOWNLOADED
[100/121] 55760 → DOWNLOADED
[101/121] 55952 → DOWNLOADED
[102/121] 56463 → DOWNLOADED
[103/121] 56292 → DOWNLOADED
[104/121] 56126 → DOWNLOADED
[105/121] 56821 → DOWNLOADED
[106/121] 56659 → DOWNLOADED
[107/121] 57027 → DOWNLOADED
[108/121] 57223 → DOWNLOADED
[109/121] 57418 → DOWNLOADED
[110/121] 58178 → DOWNLOADED
[111/121] 53631 → DOWNLOADED
[112/121] 53491 → DOWNLOADED
[113/121] 58400 → DOWNLOADED
[114/121] 58601 → DOWNLOADED
[115/121] 59005 → DOWNLOADED
[116/121] 58785 → DOWNLOADED
[117/121] 59209 → DOWNLOADED
[118/121] 59430 → DOWNLOADED
[119/121] 58010 → DOWNLOADED
[120/121] 57589 → DOWNLOADED
[121/121] 57816 → DOWNLOADED

================================================================================
FINAL RBI DOWNLOAD SUMMARY
================================================================================
Total releases: 121
Excel files found: 121
Downloaded now: 121
Already existed: 0
Errors: 0

RBI raw-data folder:
/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/RBI

Collection complete.

In [42]:
from pathlib import Path

pdf_path = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/ISM_Projects/"
    "ISM_Approved_Projects_Feb2026.pdf"
)

print("File exists:", pdf_path.exists())

if pdf_path.exists():
    print("File size:", pdf_path.stat().st_size, "bytes")

File exists: True
File size: 517783 bytes

In [43]:
import pdfplumber
from pathlib import Path

pdf_path = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/ISM_Projects/"
    "ISM_Approved_Projects_Feb2026.pdf"
)

print("Opening PDF...")

with pdfplumber.open(pdf_path) as pdf:

    print("Number of pages:", len(pdf.pages))

    for i, page in enumerate(pdf.pages):

        text = page.extract_text()

        print("\n" + "=" * 80)
        print("PAGE", i + 1)
        print("=" * 80)

        if text:
            print(text[:5000])
        else:
            print("No text extracted from this page.")

ModuleNotFoundError: No module named 'pdfplumber'

In [44]:
%pip install pdfplumber

Collecting pdfplumber
  Using cached pdfplumber-0.11.10-py3-none-any.whl.metadata (43 kB)
Collecting pdfminer.six==20260107 (from pdfplumber)
  Using cached pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting Pillow>=12.2.0 (from pdfplumber)
  Downloading pillow-12.3.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.1 kB)
Collecting pypdfium2>=5.9.0 (from pdfplumber)
  Using cached pypdfium2-5.13.0-py3-none-macosx_13_0_arm64.whl.metadata (66 kB)
Requirement already satisfied: charset-normalizer>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from pdfminer.six==20260107->pdfplumber) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from pdfminer.six==20260107->pdfplumber) (44.0.1)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.21)
Using cached pdfplumber-0.11.10-py3-none-any.whl (60 kB)
Using cached pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
Downloading pillow-12.3.0-cp313-cp313-macosx_11_0_arm64.whl (4.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 2.2 MB/s eta 0:00:00 MB/s eta 0:00:01:01
Using cached pypdfium2-5.13.0-py3-none-macosx_13_0_arm64.whl (3.5 MB)
Installing collected packages: pypdfium2, Pillow, pdfminer.six, pdfplumber
  Attempting uninstall: Pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pdfplumber] 1/4 [Pillow]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pillow<12,>=7.1.0, but you have pillow 12.3.0 which is incompatible.
Successfully installed Pillow-12.3.0 pdfminer.six-20260107 pdfplumber-0.11.10 pypdfium2-5.13.0
Note: you may need to restart the kernel to use updated packages.

In [45]:
import pdfplumber

print("pdfplumber installed successfully")
print("Version:", pdfplumber.__version__)

pdfplumber installed successfully
Version: 0.11.10

In [46]:
import pdfplumber
from pathlib import Path

pdf_path = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/ISM_Projects/"
    "ISM_Approved_Projects_Feb2026.pdf"
)

with pdfplumber.open(pdf_path) as pdf:

    print("Number of pages:", len(pdf.pages))

    for i, page in enumerate(pdf.pages):

        print("\n" + "=" * 80)
        print(f"PAGE {i + 1}")
        print("=" * 80)

        # Extract text
        text = page.extract_text()

        if text:
            print(text[:7000])
        else:
            print("No text extracted.")

        # Check for tables
        tables = page.extract_tables()

        print("\nTables detected:", len(tables))

        for j, table in enumerate(tables):

            print(f"\n--- TABLE {j + 1} ---")

            for row in table[:15]:
                print(row)

Number of pages: 9

================================================================================
PAGE 1
================================================================================
India Semiconductor Mission 2.0
A Major Push in Budget 2026 towards Semiconductor Self-Reliance
February 7, 2026
Key Takeaways
• Union Budget 2026–27 allocates ₹1,000 crore for India Semiconductor Mission (ISM)
2.0.
• As of December 2025, 10 ISM projects worth ₹1.60 lakh crore approved across six
states.
• India’s semiconductor market projected to reach $100–110 billion by 2030.
Introduction
The Union Budget 2026–27 marked a decisive moment for India’s technology ambitions with the
announcement of India Semiconductor Mission 2.0. The new phase signals a clear policy push to
deepen domestic semiconductor capabilities at a time when chips underpin every critical digital and
industrial system. ISM 2.0 will focus on producing semiconductor equipment and materials in India,
designing full stack Indian semiconductor intellectual property, and fortifying both domestic and global
supply chains. A provision of Rs. 1,000 crore has been made for ISM 2.0 for FY 2026–27, with a strong
emphasis on industry led research and training centres to drive technology development and create a
future ready skilled workforce.

Tables detected: 0

================================================================================
PAGE 2
================================================================================
Semiconductors are the backbone of modern electronics, powering computers, mobile devices,
telecommunications, automobiles, defence systems and artificial intelligence. India has made steady
progress in consolidating earlier investments into a full-stack value chain of its semiconductor
ecosystem under ISM 1.0, expanding design capabilities and advancing fabrication, assembly and
testing infrastructure across the country. This momentum reflects the broader vision of Aatmanirbhar
Bharat and India’s transition from policy formulation to production readiness. Building on these gains,
ISM 2.0 seeks to consolidate India’s position as a reliable and competitive participant in the global
semiconductor network.
Sectoral Outlook: India’s Semiconductor Ecosystem
India is steadily emerging as a global
semiconductor hub. Large scale
investments, expanding manufacturing
capacity, and platforms such as SEMICON
India 2025 reflect growing global
confidence in India’s semiconductor
journey. The domestic chip market is
witnessing rapid growth. As per industry
estimates, the size of the Indian
semiconductor market was about $38 Bn in
2023, $45-$50 billion in 2024-2025 and is
expected to reach $100-$110 Bn by 2030.
This expansion is anchored in the national
vision of Make in India and Make for the
World, positioning India as both a
manufacturing base and a global supplier.
The foundation of this growth was laid with
the approval of India Semiconductor Mission 1.0 by the Union Cabinet in December 2021. The
Mission is supported by an incentive framework of ₹76,000 crore, offering fiscal support of up to 50
per cent for silicon fabs, compound semiconductor facilities, assembly and testing units, and chip
design. As of December 2025, 10 projects with a total investment of ₹1.60 lakh crore have been
approved across 6 states. These include silicon fabrication units, silicon carbide fabs, advanced and
memory packaging facilities, and specialised assembly and testing infrastructure. Together, they are
shaping a resilient domestic semiconductor ecosystem.
By 2029, India is expected to achieve the capability to design and manufacture chips required for
nearly 70–75 per cent of domestic applications. Advancing on this foundation, the next phase
under Semicon 2.0 will focus on advanced manufacturing, with a clearly defined roadmap to achieve 3-
nanometre and 2-nanometre technology nodes. By 2035, India aims to be among the top
semiconductor nations globally.

Tables detected: 1

--- TABLE 1 ---
['By 2029, India is expected to achieve the capability to design and manufacture chips required for']
['nearly 70–75 per cent of domestic applications. Advancing on this foundation, the next phase']
['under Semicon 2.0 will focus on advanced manufacturing, with a clearly defined roadmap to achieve 3-']
['nanometre and 2-nanometre technology nodes. By 2035, India aims to be among the top']
['semiconductor nations globally.']

================================================================================
PAGE 3
================================================================================
Approved Semiconductor Manufacturing Projects
1. Micron Technology Inc. is establishing semiconductor manufacturing facility in Gujarat with
an investment of Rs.22,516 crore. Micron’s facility in India will enable assembly and test
manufacturing for both DRAM and NAND products and address demand from domestic and
international markets. The production capacity is around 14 million units per week.
2. Tata Electronics Private Limited (TEPL) is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 91,526 crore. The fab facility will be set up in
technology partnership with PSMC, Taiwan. The production capacity of the project would be
around 50,000 wafer starts per month (WSPM).
3. Tata Electronics Private Limited (TEPL) is establishing semiconductor manufacturing
facility in Assam with an investment of Rs.27,120 crores. The facility will use indigenous
semiconductor packaging technologies with a production capacity of 48 million units per day.
4. CG Power and Industrial Solutions Limited is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 7,584 crore. The facility will be set up as a joint
venture partnership with Renesas Electronics America Inc., USA, and STARS Microelectronic,
Thailand.
5. Kaynes Technology India Limited (KTIL) is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 3,307 crores. The facility will have the capacity to
produce more than 6.33 million chips per day.
6. Vama Sundari Investments (Delhi) Private Limited (VSIPL) is establishing semiconductor
manufacturing facility in Uttar Pradesh with an investment of Rs 3,706 crores. The production
capacity would be around 20K wafers per month/36 million chips per month.
7. 3D Glass Solutions Inc. (3DGS) is establishing semiconductor manufacturing facility in Odisha
with an investment of Rs. 1,943 crores. The Proposed installed capacity for glass panel substrate
production, assembly and Heterogeneous Integration (3DHI) is around 5800 panels per month,
4.20 million units per month, and 1100 units per months respectively.
8. SiCSem Private Limited is establishing semiconductor manufacturing facility in Odisha with
an investment of Rs. 2,066 crores. The production capacity is 5,000 wafers/month, and the
packaging capacity is 8 million units/month.
9. Continental Device India Private Limited (CDIL) is expanding its semiconductor
manufacturing facility in Punjab, with an investment of Rs. 117 crores. The facility will
manufacture high-power discrete semiconductor devices. The production capacity will be
around 158.38 million units/annum
10. Advanced System in Package Technologies Private Limited (ASIP) is establishing
semiconductor manufacturing facility in Andhra Pradesh, with an investment of Rs. 480 crores.
The production capacity of the facility would be around 96 million units/annum.

Tables detected: 0

================================================================================
PAGE 4
================================================================================
These facilities are expected to meet the growing chip requirements of key sectors such as consumer
appliances, industrial electronics, automobiles, telecommunications, aerospace, and power electronics.
Notably, several approved proposals are leveraging indigenous technologies for the assembly, testing,
and packaging of semiconductor chips. This shift reflects India’s move towards deeper technological
capability and reduced dependence on external systems, strengthening its position in the global
semiconductor value chain.
Schemes under ISM
• Semiconductor Fabs Scheme: Provides up to 50 per cent fiscal support for setting up
semiconductor wafer fabrication units, covering advanced and mature technology nodes.
• Display Fabs Scheme: Offers up to 50 per cent financial support to establish AMOLED
and LCD display fabrication units in India.
• Compound Semiconductors and ATMP/OSAT Scheme: Supports compound
semiconductor and chip assembly, testing and packaging units with up to 50 per cent capital
assistance.
• Design Linked Incentive Scheme: With an outlay of ₹1,000 crore, supports chip design
startups and MSMEs through R&D support and incentives of up to ₹15 crore per company.
Anticipated Impact of Semiconductor Programme in 2026–27
India’s semiconductor programme has been recalibrated in response to intensifying global competition
and the concentration of advanced chip technologies among a limited number of players. Several
countries with established semiconductor ecosystems are offering aggressive incentives, making it
necessary for India to refine its approach. The modified programme therefore focuses on strengthening
financial support for investments across semiconductor manufacturing, display fabrication, and the
design ecosystem.
For 2026–27, the Modified Programme for Development of Semiconductor and Display Manufacturing
Ecosystem in India has a total financial outlay of ₹8,000 crore. The programme aims to accelerate
capital investment, generate high quality employment, and expand domestic capabilities across
fabrication, packaging, and chip design. The projected outcomes for the year are outlined below.

Tables detected: 0

================================================================================
PAGE 5
================================================================================
Projected Targets under ISM for 2026–27:
Scheme Key Indicator Projected Target
Modified Scheme for Semiconductor
Investment during the year ₹4,000 crore
Fabs (Fabs to be Supported – 1)
Employment generated 1,500 persons
Modified Scheme for Compound
Semiconductors, Silicon Photonics,
Sensors, Discrete Fabs and Assembly,
Investment by units during
Testing, Marking, and Packaging ₹11,000 crore
the year
(ATMP)/ Outsourced Semiconductor
Assembly and Test (OSAT) (Units to be
Supported – 9)
Employment generated by
3,000 persons
supported units
Design Linked Incentive Scheme (Design Semiconductor IP cores to
10
companies to be supported – 30) be developed
Semiconductor design
200 persons
manpower employed
Together, these outcomes reflect a strong push towards scaling domestic manufacturing, deepening
design capabilities, and creating a skilled workforce to support India’s long term semiconductor
ambitions.
Why the India Semiconductor Mission Matters
Semiconductors have become critical to the functioning of modern economies. Though rarely visible in
everyday life, microprocessors quietly power systems that keep societies running. As highlighted in
the Economic Survey 2025–26, they form the backbone of energy networks, financial markets and
telecommunications. They enable manufacturing units, hospitals, transport systems and satellites. A
reliable supply of semiconductors is therefore essential for economic stability and continuity across
sectors.
Recent global disruptions have underscored this dependence. The COVID-19 pandemic exposed serious
weaknesses in semiconductor supply chains, with shortages affecting more than 169 industries
worldwide. Production delays and rising costs followed, slowing economic activity across countries.
These shocks revealed the risks of relying on a narrow set of suppliers. Today, the semiconductor
industry is dominated by a few countries, including Taiwan, South Korea, Japan, China and the United
States. Taiwan alone produces over 60 per cent of the world’s semiconductors and nearly 90 per cent of
the most advanced chips, leaving global supply chains vulnerable to external shocks and geopolitical
tensions.

Tables detected: 1

--- TABLE 1 ---
['Scheme', 'Key Indicator', 'Projected Target']
['Modified Scheme for Semiconductor\nFabs (Fabs to be Supported – 1)', 'Investment during the year', '₹4,000 crore']
[None, 'Employment generated', '1,500 persons']
['Modified Scheme for Compound\nSemiconductors, Silicon Photonics,\nSensors, Discrete Fabs and Assembly,\nTesting, Marking, and Packaging\n(ATMP)/ Outsourced Semiconductor\nAssembly and Test (OSAT) (Units to be\nSupported – 9)', 'Investment by units during\nthe year', '₹11,000 crore']
[None, 'Employment generated by\nsupported units', '3,000 persons']
['Design Linked Incentive Scheme (Design\ncompanies to be supported – 30)', 'Semiconductor IP cores to\nbe developed', '10']
[None, 'Semiconductor design\nmanpower employed', '200 persons']

================================================================================
PAGE 6
================================================================================
In response, major economies are recalibrating their strategies. The United States, the European Union,
Japan and South Korea have launched national initiatives to strengthen domestic chip manufacturing
and diversify supply chains. India is positioning itself within this global shift as a trusted and reliable
partner. The India Semiconductor Mission responds directly to this moment. By building domestic
capacity across design, manufacturing and innovation, ISM represents a critical step towards self-
sufficiency and technological sovereignty, while strengthening India’s role in a more resilient global
semiconductor ecosystem.
At the core of this strategy lies a strong focus on semiconductor design and talent development, which
together form the foundation of technological self-reliance.
Strengthening India’s Semiconductor Design Ecosystem
Since its launch in December 2021, the Design Linked Incentive Scheme has played a pivotal role in
transitioning from capacity creation to technological depth in India. The scheme focuses on nurturing
domestic innovation, supporting early-stage companies, and creating the foundation for a vibrant fabless
ecosystem. It has also helped bridge the gap between academic research and industry application,
strengthening India’s position in the global design landscape.
Key Achievements under the DLI Scheme (as of January 2026):
• The programme currently supports 24 semiconductor design startups across the country.
• Startups under the scheme have attracted nearly ₹430 crore in venture capital funding,
reflecting growing investor confidence in India’s design ecosystem.
• Advanced Electronic Design Automation (EDA), the national chip design platform, has
enabled access to high end design tools, with approximately 2.25 crore tool hours recorded.
• Around 67,000 students and over 1,000 start up engineers are actively using these tools for chip
design and development.
• In academia, 122 designs have been taped out, with 56 chips fabricated at 180 nm at the
Semiconductor Laboratory in Mohali.
• Startups have completed 16 tape outs, resulting in six chips fabricated at advanced foundry
nodes, including technologies as advanced as 12 nm.
• Academic institutions have filed 75 patents, while startups have filed 10 patents, indicating a
growing culture of innovation and intellectual property creation.
Looking ahead, the programme is set to scale further, with a target of enabling at least 50 fabless
semiconductor companies in the next phase, reinforcing India’s ambition to emerge as a global hub for
semiconductor design and innovation.

Tables detected: 3

--- TABLE 1 ---
['• Startups under the scheme have attracted nearly ₹430 crore in venture capital funding,']
['reflecting growing investor confidence in India’s design ecosystem.']

--- TABLE 2 ---
['• Around 67,000 students and over 1,000 start up engineers are actively using these tools for chip']
['design and development.']

--- TABLE 3 ---
['• Startups have completed 16 tape outs, resulting in six chips fabricated at advanced foundry']
['nodes, including technologies as advanced as 12 nm.']

================================================================================
PAGE 7
================================================================================
Advancing Indigenous Microprocessors and Core Semiconductor Technologies
Microprocessors form the foundational layer of modern digital infrastructure, powering devices and
systems across telecommunications, mobility, healthcare, industry, defence, and space. Recognising
their strategic importance, India has made focused investments to build sovereign capabilities in
advanced processor design as a core pillar of semiconductor self-reliance.
A key milestone in this journey is the launch of DHRUV64, a fully indigenous 64-bit microprocessor
developed by C-DAC under the Microprocessor Development Programme (MDP). Built on modern
architectural principles, DHRUV64 delivers improved efficiency, multitasking capability, and
reliability, enabling its deployment across sectors such as 5G infrastructure, automotive electronics,
industrial automation, consumer devices, and the Internet of Things (IoT). Its development provides
India with a secure, homegrown processor platform, reducing long-term dependence on imported
chips—particularly significant given that India consumes nearly 20 per cent of global microprocessor
output.
DHRUV64 builds on a growing portfolio of indigenous processors, including SHAKTI, AJIT,
VIKRAM, and THEJAS, collectively forming the foundation of an Indian processor ecosystem.
Developed under the Digital India RISC-V (DIR-V) Programme, these processors leverage the open-
source RISC-V architecture, eliminating licence costs and enabling collaborative innovation across
academia, startups, and industry. The rollout of DHRUV64, alongside the ongoing development of
DHANUSH and DHANUSH+ System on Chips variants, strengthens India’s R&D ecosystem,
accelerates product prototyping, and expands opportunities for domestic design talent.
Together, these initiatives position microprocessors not merely as components, but as strategic enablers
of India’s digital sovereignty—supporting innovation, securing critical infrastructure, and anchoring
the country’s long-term ambitions in the global semiconductor value chain.
Development of Semiconductor Talent Pipeline
A strong semiconductor ecosystem depends as much on people as on infrastructure. India has therefore
adopted a comprehensive approach to build a large, skilled and industry ready talent base across design,
manufacturing and advanced packaging. The emphasis is on early exposure to chip technologies,
practical training, and continuous upskilling aligned with evolving industry requirements.
• Chips to Start up Programme: The Chips to Start up programme enables access to the latest
electronic design automation tools across 397 universities and startups. Using these tools, chip
designers from more than 46 universities have designed and fabricated 56 chips at the
Semiconductor Laboratory in Mohali.
• Academic Programmes under All India Council for Technical Education (AICTE):
Specialised academic programmes have been introduced to integrate semiconductor education
into mainstream engineering. These include a B Tech in Electronics Engineering with focus on
VLSI design, a diploma in integrated circuit manufacturing, and a minor degree in Electronics

Tables detected: 1

--- TABLE 1 ---
['• Academic Programmes under All India Council for Technical Education (AICTE):']
['Specialised academic programmes have been introduced to integrate semiconductor education']
['into mainstream engineering. These include a B Tech in Electronics Engineering with focus on']

In [47]:
import pdfplumber
from pathlib import Path

pdf_path = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/ISM_Projects/"
    "ISM_Approved_Projects_Feb2026.pdf"
)

with pdfplumber.open(pdf_path) as pdf:

    for page_number, page in enumerate(pdf.pages, start=1):

        text = page.extract_text() or ""

        print("\n" + "=" * 100)
        print(f"PAGE {page_number}")
        print("=" * 100)

        # Show lines containing likely project/table keywords
        lines = text.splitlines()

        for line in lines:

            if any(keyword in line.lower() for keyword in [
                "semiconductor",
                "project",
                "investment",
                "capacity",
                "micron",
                "kaynes",
                "tata",
                "cg power",
                "renesas"
            ]):

                print(line)

====================================================================================================
PAGE 1
====================================================================================================
India Semiconductor Mission 2.0
A Major Push in Budget 2026 towards Semiconductor Self-Reliance
• Union Budget 2026–27 allocates ₹1,000 crore for India Semiconductor Mission (ISM)
• As of December 2025, 10 ISM projects worth ₹1.60 lakh crore approved across six
• India’s semiconductor market projected to reach $100–110 billion by 2030.
announcement of India Semiconductor Mission 2.0. The new phase signals a clear policy push to
deepen domestic semiconductor capabilities at a time when chips underpin every critical digital and
industrial system. ISM 2.0 will focus on producing semiconductor equipment and materials in India,
designing full stack Indian semiconductor intellectual property, and fortifying both domestic and global

====================================================================================================
PAGE 2
====================================================================================================
Semiconductors are the backbone of modern electronics, powering computers, mobile devices,
progress in consolidating earlier investments into a full-stack value chain of its semiconductor
semiconductor network.
Sectoral Outlook: India’s Semiconductor Ecosystem
semiconductor hub. Large scale
investments, expanding manufacturing
capacity, and platforms such as SEMICON
confidence in India’s semiconductor
semiconductor market was about $38 Bn in
the approval of India Semiconductor Mission 1.0 by the Union Cabinet in December 2021. The
per cent for silicon fabs, compound semiconductor facilities, assembly and testing units, and chip
design. As of December 2025, 10 projects with a total investment of ₹1.60 lakh crore have been
shaping a resilient domestic semiconductor ecosystem.
semiconductor nations globally.

====================================================================================================
PAGE 3
====================================================================================================
Approved Semiconductor Manufacturing Projects
1. Micron Technology Inc. is establishing semiconductor manufacturing facility in Gujarat with
an investment of Rs.22,516 crore. Micron’s facility in India will enable assembly and test
international markets. The production capacity is around 14 million units per week.
2. Tata Electronics Private Limited (TEPL) is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 91,526 crore. The fab facility will be set up in
technology partnership with PSMC, Taiwan. The production capacity of the project would be
3. Tata Electronics Private Limited (TEPL) is establishing semiconductor manufacturing
facility in Assam with an investment of Rs.27,120 crores. The facility will use indigenous
semiconductor packaging technologies with a production capacity of 48 million units per day.
4. CG Power and Industrial Solutions Limited is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 7,584 crore. The facility will be set up as a joint
venture partnership with Renesas Electronics America Inc., USA, and STARS Microelectronic,
5. Kaynes Technology India Limited (KTIL) is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 3,307 crores. The facility will have the capacity to
6. Vama Sundari Investments (Delhi) Private Limited (VSIPL) is establishing semiconductor
manufacturing facility in Uttar Pradesh with an investment of Rs 3,706 crores. The production
capacity would be around 20K wafers per month/36 million chips per month.
7. 3D Glass Solutions Inc. (3DGS) is establishing semiconductor manufacturing facility in Odisha
with an investment of Rs. 1,943 crores. The Proposed installed capacity for glass panel substrate
8. SiCSem Private Limited is establishing semiconductor manufacturing facility in Odisha with
an investment of Rs. 2,066 crores. The production capacity is 5,000 wafers/month, and the
packaging capacity is 8 million units/month.
9. Continental Device India Private Limited (CDIL) is expanding its semiconductor
manufacturing facility in Punjab, with an investment of Rs. 117 crores. The facility will
manufacture high-power discrete semiconductor devices. The production capacity will be
semiconductor manufacturing facility in Andhra Pradesh, with an investment of Rs. 480 crores.
The production capacity of the facility would be around 96 million units/annum.

====================================================================================================
PAGE 4
====================================================================================================
and packaging of semiconductor chips. This shift reflects India’s move towards deeper technological
semiconductor value chain.
• Semiconductor Fabs Scheme: Provides up to 50 per cent fiscal support for setting up
semiconductor wafer fabrication units, covering advanced and mature technology nodes.
• Compound Semiconductors and ATMP/OSAT Scheme: Supports compound
semiconductor and chip assembly, testing and packaging units with up to 50 per cent capital
Anticipated Impact of Semiconductor Programme in 2026–27
India’s semiconductor programme has been recalibrated in response to intensifying global competition
countries with established semiconductor ecosystems are offering aggressive incentives, making it
financial support for investments across semiconductor manufacturing, display fabrication, and the
For 2026–27, the Modified Programme for Development of Semiconductor and Display Manufacturing
capital investment, generate high quality employment, and expand domestic capabilities across
fabrication, packaging, and chip design. The projected outcomes for the year are outlined below.

====================================================================================================
PAGE 5
====================================================================================================
Projected Targets under ISM for 2026–27:
Scheme Key Indicator Projected Target
Modified Scheme for Semiconductor
Investment during the year ₹4,000 crore
Semiconductors, Silicon Photonics,
Investment by units during
(ATMP)/ Outsourced Semiconductor
Design Linked Incentive Scheme (Design Semiconductor IP cores to
Semiconductor design
design capabilities, and creating a skilled workforce to support India’s long term semiconductor
Why the India Semiconductor Mission Matters
Semiconductors have become critical to the functioning of modern economies. Though rarely visible in
reliable supply of semiconductors is therefore essential for economic stability and continuity across
weaknesses in semiconductor supply chains, with shortages affecting more than 169 industries
These shocks revealed the risks of relying on a narrow set of suppliers. Today, the semiconductor
States. Taiwan alone produces over 60 per cent of the world’s semiconductors and nearly 90 per cent of

====================================================================================================
PAGE 6
====================================================================================================
partner. The India Semiconductor Mission responds directly to this moment. By building domestic
capacity across design, manufacturing and innovation, ISM represents a critical step towards self-
semiconductor ecosystem.
At the core of this strategy lies a strong focus on semiconductor design and talent development, which
Strengthening India’s Semiconductor Design Ecosystem
transitioning from capacity creation to technological depth in India. The scheme focuses on nurturing
• The programme currently supports 24 semiconductor design startups across the country.
Semiconductor Laboratory in Mohali.
semiconductor companies in the next phase, reinforcing India’s ambition to emerge as a global hub for
semiconductor design and innovation.

====================================================================================================
PAGE 7
====================================================================================================
Advancing Indigenous Microprocessors and Core Semiconductor Technologies
their strategic importance, India has made focused investments to build sovereign capabilities in
advanced processor design as a core pillar of semiconductor self-reliance.
the country’s long-term ambitions in the global semiconductor value chain.
Development of Semiconductor Talent Pipeline
A strong semiconductor ecosystem depends as much on people as on infrastructure. India has therefore
Semiconductor Laboratory in Mohali.
Specialised academic programmes have been introduced to integrate semiconductor education

====================================================================================================
PAGE 8
====================================================================================================
Lab at NIELIT Calicut supports large scale training in semiconductor technologies. The
reskilling and upskilling in emerging technologies, including semiconductors. Courses are
Together, these initiatives are creating a robust and future ready semiconductor workforce, positioning
India Semiconductor Mission 2.0 marks a decisive shift from ecosystem creation to ecosystem
skills, ISM 2.0 positions semiconductors as a strategic national capability—central to economic
2026–27 provides the momentum required to accelerate execution, crowd in private investment, and
scale domestic capacity across the full semiconductor value chain.
Looking ahead, ISM 2.0 lays the foundation for India to emerge as a trusted hub for semiconductor
ambition to be among the world’s leading semiconductor nations in the coming decade.

====================================================================================================
PAGE 9
====================================================================================================

In [48]:
import pdfplumber
from pathlib import Path

pdf_path = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/ISM_Projects/"
    "ISM_Approved_Projects_Feb2026.pdf"
)

with pdfplumber.open(pdf_path) as pdf:

    page = pdf.pages[2]   # Page 3

    print("=" * 120)
    print("RAW PAGE 3 TEXT")
    print("=" * 120)

    text = page.extract_text(
        x_tolerance=2,
        y_tolerance=3
    )

    print(text)

========================================================================================================================
RAW PAGE 3 TEXT
========================================================================================================================
Approved Semiconductor Manufacturing Projects
1. Micron Technology Inc. is establishing semiconductor manufacturing facility in Gujarat with
an investment of Rs.22,516 crore. Micron’s facility in India will enable assembly and test
manufacturing for both DRAM and NAND products and address demand from domestic and
international markets. The production capacity is around 14 million units per week.
2. Tata Electronics Private Limited (TEPL) is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 91,526 crore. The fab facility will be set up in
technology partnership with PSMC, Taiwan. The production capacity of the project would be
around 50,000 wafer starts per month (WSPM).
3. Tata Electronics Private Limited (TEPL) is establishing semiconductor manufacturing
facility in Assam with an investment of Rs.27,120 crores. The facility will use indigenous
semiconductor packaging technologies with a production capacity of 48 million units per day.
4. CG Power and Industrial Solutions Limited is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 7,584 crore. The facility will be set up as a joint
venture partnership with Renesas Electronics America Inc., USA, and STARS Microelectronic,
Thailand.
5. Kaynes Technology India Limited (KTIL) is establishing semiconductor manufacturing
facility in Gujarat with an investment of Rs. 3,307 crores. The facility will have the capacity to
produce more than 6.33 million chips per day.
6. Vama Sundari Investments (Delhi) Private Limited (VSIPL) is establishing semiconductor
manufacturing facility in Uttar Pradesh with an investment of Rs 3,706 crores. The production
capacity would be around 20K wafers per month/36 million chips per month.
7. 3D Glass Solutions Inc. (3DGS) is establishing semiconductor manufacturing facility in Odisha
with an investment of Rs. 1,943 crores. The Proposed installed capacity for glass panel substrate
production, assembly and Heterogeneous Integration (3DHI) is around 5800 panels per month,
4.20 million units per month, and 1100 units per months respectively.
8. SiCSem Private Limited is establishing semiconductor manufacturing facility in Odisha with
an investment of Rs. 2,066 crores. The production capacity is 5,000 wafers/month, and the
packaging capacity is 8 million units/month.
9. Continental Device India Private Limited (CDIL) is expanding its semiconductor
manufacturing facility in Punjab, with an investment of Rs. 117 crores. The facility will
manufacture high-power discrete semiconductor devices. The production capacity will be
around 158.38 million units/annum
10. Advanced System in Package Technologies Private Limited (ASIP) is establishing
semiconductor manufacturing facility in Andhra Pradesh, with an investment of Rs. 480 crores.
The production capacity of the facility would be around 96 million units/annum.

In [49]:
with pdfplumber.open(pdf_path) as pdf:

    page = pdf.pages[2]

    words = page.extract_words(
        x_tolerance=2,
        y_tolerance=3,
        keep_blank_chars=False
    )

    print("Total words:", len(words))
    print()

    for word in words:
        print(
            f"x={word['x0']:.1f} | "
            f"y={word['top']:.1f} | "
            f"{word['text']}"
        )

Total words: 412

x=178.1 | y=77.9 | Approved
x=232.3 | y=77.9 | Semiconductor
x=312.4 | y=77.9 | Manufacturing
x=393.4 | y=77.9 | Projects
x=77.5 | y=103.9 | 1.
x=95.5 | y=103.9 | Micron
x=133.8 | y=103.9 | Technology
x=191.5 | y=103.9 | Inc.
x=212.1 | y=103.9 | is
x=222.6 | y=103.9 | establishing
x=278.3 | y=103.9 | semiconductor
x=346.0 | y=103.9 | manufacturing
x=413.5 | y=103.9 | facility
x=447.7 | y=103.9 | in
x=459.5 | y=103.9 | Gujarat
x=495.7 | y=103.9 | with
x=95.5 | y=116.9 | an
x=110.8 | y=116.9 | investment
x=163.8 | y=116.9 | of
x=177.8 | y=116.9 | Rs.22,516
x=227.0 | y=116.9 | crore.
x=257.2 | y=116.9 | Micron’s
x=302.2 | y=116.9 | facility
x=337.9 | y=116.9 | in
x=351.1 | y=116.9 | India
x=378.4 | y=116.9 | will
x=400.1 | y=116.9 | enable
x=433.8 | y=116.9 | assembly
x=479.6 | y=116.9 | and
x=500.3 | y=116.9 | test
x=95.5 | y=129.7 | manufacturing
x=163.5 | y=129.7 | for
x=180.0 | y=129.7 | both
x=203.2 | y=129.7 | DRAM
x=239.9 | y=129.7 | and
x=259.4 | y=129.7 | NAND
x=294.9 | y=129.7 | products
x=336.4 | y=129.7 | and
x=355.8 | y=129.7 | address
x=392.6 | y=129.7 | demand
x=431.0 | y=129.7 | from
x=456.3 | y=129.7 | domestic
x=499.5 | y=129.7 | and
x=95.5 | y=142.4 | international
x=154.1 | y=142.4 | markets.
x=194.3 | y=142.4 | The
x=214.3 | y=142.4 | production
x=264.5 | y=142.4 | capacity
x=304.0 | y=142.4 | is
x=314.1 | y=142.4 | around
x=347.3 | y=142.4 | 14
x=361.0 | y=142.4 | million
x=395.3 | y=142.4 | units
x=419.5 | y=142.4 | per
x=436.5 | y=142.4 | week.
x=77.5 | y=162.7 | 2.
x=95.5 | y=162.7 | Tata
x=124.3 | y=162.7 | Electronics
x=183.5 | y=162.7 | Private
x=224.5 | y=162.7 | Limited
x=268.2 | y=162.7 | (TEPL)
x=306.9 | y=162.7 | is
x=320.9 | y=162.7 | establishing
x=379.9 | y=162.7 | semiconductor
x=451.6 | y=162.7 | manufacturing
x=95.5 | y=175.9 | facility
x=130.8 | y=175.9 | in
x=143.3 | y=175.9 | Gujarat
x=180.3 | y=175.9 | with
x=203.7 | y=175.9 | an
x=218.2 | y=175.9 | investment
x=270.5 | y=175.9 | of
x=283.7 | y=175.9 | Rs.
x=301.9 | y=175.9 | 91,526
x=336.2 | y=175.9 | crore.
x=365.9 | y=175.9 | The
x=386.9 | y=175.9 | fab
x=405.1 | y=175.9 | facility
x=440.1 | y=175.9 | will
x=461.1 | y=175.9 | be
x=475.6 | y=175.9 | set
x=491.8 | y=175.9 | up
x=506.8 | y=175.9 | in
x=95.5 | y=188.4 | technology
x=148.0 | y=188.4 | partnership
x=201.0 | y=188.4 | with
x=224.0 | y=188.4 | PSMC,
x=259.4 | y=188.4 | Taiwan.
x=298.6 | y=188.4 | The
x=319.4 | y=188.4 | production
x=370.1 | y=188.4 | capacity
x=410.3 | y=188.4 | of
x=423.0 | y=188.4 | the
x=440.0 | y=188.4 | project
x=474.0 | y=188.4 | would
x=505.0 | y=188.4 | be
x=95.5 | y=201.2 | around
x=129.0 | y=201.2 | 50,000
x=162.0 | y=201.2 | wafer
x=189.8 | y=201.2 | starts
x=215.8 | y=201.2 | per
x=232.6 | y=201.2 | month
x=263.3 | y=201.2 | (WSPM).
x=77.5 | y=221.7 | 3.
x=95.5 | y=221.7 | Tata
x=124.3 | y=221.7 | Electronics
x=183.5 | y=221.7 | Private
x=224.5 | y=221.7 | Limited
x=268.2 | y=221.7 | (TEPL)
x=306.9 | y=221.7 | is
x=320.9 | y=221.7 | establishing
x=379.9 | y=221.7 | semiconductor
x=451.6 | y=221.7 | manufacturing
x=95.5 | y=234.7 | facility
x=131.5 | y=234.7 | in
x=144.8 | y=234.7 | Assam
x=179.2 | y=234.7 | with
x=203.5 | y=234.7 | an
x=218.5 | y=234.7 | investment
x=271.5 | y=234.7 | of
x=285.2 | y=234.7 | Rs.27,120
x=334.4 | y=234.7 | crores.
x=368.6 | y=234.7 | The
x=390.1 | y=234.7 | facility
x=426.1 | y=234.7 | will
x=447.8 | y=234.7 | use
x=467.1 | y=234.7 | indigenous
x=95.5 | y=247.5 | semiconductor
x=163.3 | y=247.5 | packaging
x=211.3 | y=247.5 | technologies
x=269.5 | y=247.5 | with
x=291.8 | y=247.5 | a
x=299.5 | y=247.5 | production
x=349.7 | y=247.5 | capacity
x=389.2 | y=247.5 | of
x=401.2 | y=247.5 | 48
x=415.0 | y=247.5 | million
x=449.2 | y=247.5 | units
x=473.3 | y=247.5 | per
x=490.2 | y=247.5 | day.
x=77.5 | y=268.0 | 4.
x=95.5 | y=268.0 | CG
x=116.5 | y=268.0 | Power
x=151.2 | y=268.0 | and
x=173.5 | y=268.0 | Industrial
x=225.2 | y=268.0 | Solutions
x=273.1 | y=268.0 | Limited
x=313.1 | y=268.0 | is
x=324.9 | y=268.0 | establishing
x=381.8 | y=268.0 | semiconductor
x=451.3 | y=268.0 | manufacturing
x=95.5 | y=280.9 | facility
x=130.3 | y=280.9 | in
x=142.3 | y=280.9 | Gujarat
x=178.7 | y=280.9 | with
x=201.7 | y=280.9 | an
x=215.7 | y=280.9 | investment
x=267.2 | y=280.9 | of
x=279.9 | y=280.9 | Rs.
x=297.7 | y=280.9 | 7,584
x=325.9 | y=280.9 | crore.
x=354.4 | y=280.9 | The
x=375.1 | y=280.9 | facility
x=409.6 | y=280.9 | will
x=430.0 | y=280.9 | be
x=444.0 | y=280.9 | set
x=459.8 | y=280.9 | up
x=474.0 | y=280.9 | as
x=486.7 | y=280.9 | a
x=495.0 | y=280.9 | joint
x=95.5 | y=293.7 | venture
x=131.5 | y=293.7 | partnership
x=183.5 | y=293.7 | with
x=205.7 | y=293.7 | Renesas
x=244.5 | y=293.7 | Electronics
x=296.7 | y=293.7 | America
x=337.4 | y=293.7 | Inc.,
x=359.4 | y=293.7 | USA,
x=386.9 | y=293.7 | and
x=405.6 | y=293.7 | STARS
x=442.6 | y=293.7 | Microelectronic,
x=95.5 | y=306.5 | Thailand.
x=77.5 | y=326.7 | 5.
x=95.5 | y=326.7 | Kaynes
x=136.5 | y=326.7 | Technology
x=197.0 | y=326.7 | India
x=228.0 | y=326.7 | Limited
x=271.2 | y=326.7 | (KTIL)
x=308.6 | y=326.7 | is
x=321.9 | y=326.7 | establishing
x=380.3 | y=326.7 | semiconductor
x=451.3 | y=326.7 | manufacturing
x=95.5 | y=340.0 | facility
x=129.8 | y=340.0 | in
x=141.3 | y=340.0 | Gujarat
x=177.0 | y=340.0 | with
x=199.5 | y=340.0 | an
x=212.7 | y=340.0 | investment
x=264.0 | y=340.0 | of
x=276.0 | y=340.0 | Rs.
x=293.2 | y=340.0 | 3,307
x=320.7 | y=340.0 | crores.
x=353.2 | y=340.0 | The
x=373.2 | y=340.0 | facility
x=407.1 | y=340.0 | will
x=427.1 | y=340.0 | have
x=450.9 | y=340.0 | the
x=467.1 | y=340.0 | capacity
x=506.8 | y=340.0 | to
x=95.5 | y=352.7 | produce
x=134.0 | y=352.7 | more
x=159.3 | y=352.7 | than
x=181.0 | y=352.7 | 6.33
x=203.0 | y=352.7 | million
x=237.3 | y=352.7 | chips
x=263.3 | y=352.7 | per
x=280.3 | y=352.7 | day.
x=77.5 | y=373.0 | 6.
x=95.5 | y=373.0 | Vama
x=127.0 | y=373.0 | Sundari
x=168.2 | y=373.0 | Investments
x=228.4 | y=373.0 | (Delhi)
x=263.8 | y=373.0 | Private
x=301.3 | y=373.0 | Limited
x=341.8 | y=373.0 | (VSIPL)
x=384.4 | y=373.0 | is
x=394.9 | y=373.0 | establishing
x=450.6 | y=373.0 | semiconductor
x=95.5 | y=386.2 | manufacturing
x=162.8 | y=386.2 | facility
x=197.0 | y=386.2 | in
x=208.5 | y=386.2 | Uttar
x=234.2 | y=386.2 | Pradesh
x=272.2 | y=386.2 | with
x=294.7 | y=386.2 | an
x=308.1 | y=386.2 | investment
x=359.6 | y=386.2 | of
x=371.9 | y=386.2 | Rs
x=386.6 | y=386.2 | 3,706
x=414.3 | y=386.2 | crores.
x=447.3 | y=386.2 | The
x=467.5 | y=386.2 | production
x=95.5 | y=399.0 | capacity
x=135.0 | y=399.0 | would
x=165.3 | y=399.0 | be
x=178.5 | y=399.0 | around
x=211.8 | y=399.0 | 20K
x=233.5 | y=399.0 | wafers
x=265.5 | y=399.0 | per
x=282.2 | y=399.0 | month/36
x=327.0 | y=399.0 | million
x=361.5 | y=399.0 | chips
x=387.5 | y=399.0 | per
x=404.5 | y=399.0 | month.
x=77.5 | y=419.2 | 7.
x=95.5 | y=419.2 | 3D
x=111.3 | y=419.2 | Glass
x=139.1 | y=419.2 | Solutions
x=184.8 | y=419.2 | Inc.
x=205.0 | y=419.2 | (3DGS)
x=243.1 | y=419.2 | is
x=252.4 | y=419.2 | establishing
x=307.1 | y=419.2 | semiconductor
x=374.1 | y=419.2 | manufacturing
x=440.3 | y=419.2 | facility
x=473.6 | y=419.2 | in
x=484.3 | y=419.2 | Odisha
x=95.5 | y=432.5 | with
x=117.5 | y=432.5 | an
x=130.5 | y=432.5 | investment
x=181.3 | y=432.5 | of
x=192.8 | y=432.5 | Rs.
x=209.5 | y=432.5 | 1,943
x=236.8 | y=432.5 | crores.
x=268.7 | y=432.5 | The
x=288.5 | y=432.5 | Proposed
x=331.7 | y=432.5 | installed
x=371.4 | y=432.5 | capacity
x=410.4 | y=432.5 | for
x=425.9 | y=432.5 | glass
x=450.1 | y=432.5 | panel
x=476.4 | y=432.5 | substrate
x=95.5 | y=445.0 | production,
x=149.0 | y=445.0 | assembly
x=193.0 | y=445.0 | and
x=212.0 | y=445.0 | Heterogeneous
x=281.0 | y=445.0 | Integration
x=332.2 | y=445.0 | (3DHI)
x=367.4 | y=445.0 | is
x=377.6 | y=445.0 | around
x=411.4 | y=445.0 | 5800
x=436.4 | y=445.0 | panels
x=467.6 | y=445.0 | per
x=484.8 | y=445.0 | month,
x=95.5 | y=457.7 | 4.20
x=117.5 | y=457.7 | million
x=151.8 | y=457.7 | units
x=176.1 | y=457.7 | per
x=193.0 | y=457.7 | month,
x=226.5 | y=457.7 | and
x=245.3 | y=457.7 | 1100
x=270.0 | y=457.7 | units
x=294.1 | y=457.7 | per
x=311.0 | y=457.7 | months
x=346.1 | y=457.7 | respectively.
x=77.5 | y=478.0 | 8.
x=95.5 | y=478.0 | SiCSem
x=136.2 | y=478.0 | Private
x=173.7 | y=478.0 | Limited
x=213.6 | y=478.0 | is
x=224.1 | y=478.0 | establishing
x=279.8 | y=478.0 | semiconductor
x=347.8 | y=478.0 | manufacturing
x=415.3 | y=478.0 | facility
x=449.5 | y=478.0 | in
x=461.2 | y=478.0 | Odisha
x=495.7 | y=478.0 | with
x=95.5 | y=491.3 | an
x=110.5 | y=491.3 | investment
x=163.3 | y=491.3 | of
x=176.8 | y=491.3 | Rs.
x=195.5 | y=491.3 | 2,066
x=224.5 | y=491.3 | crores.
x=258.7 | y=491.3 | The
x=280.2 | y=491.3 | production
x=332.1 | y=491.3 | capacity
x=373.1 | y=491.3 | is
x=384.9 | y=491.3 | 5,000
x=414.1 | y=491.3 | wafers/month,
x=481.6 | y=491.3 | and
x=501.8 | y=491.3 | the
x=95.5 | y=504.0 | packaging
x=143.5 | y=504.0 | capacity
x=183.0 | y=504.0 | is
x=193.0 | y=504.0 | 8
x=201.3 | y=504.0 | million
x=235.5 | y=504.0 | units/month.
x=77.5 | y=524.3 | 9.
x=95.5 | y=524.3 | Continental
x=160.0 | y=524.3 | Device
x=200.2 | y=524.3 | India
x=233.9 | y=524.3 | Private
x=277.1 | y=524.3 | Limited
x=323.1 | y=524.3 | (CDIL)
x=360.6 | y=524.3 | is
x=376.6 | y=524.3 | expanding
x=431.4 | y=524.3 | its
x=450.6 | y=524.3 | semiconductor
x=95.5 | y=537.5 | manufacturing
x=165.0 | y=537.5 | facility
x=201.5 | y=537.5 | in
x=215.2 | y=537.5 | Punjab,
x=253.7 | y=537.5 | with
x=278.7 | y=537.5 | an
x=294.4 | y=537.5 | investment
x=348.1 | y=537.5 | of
x=362.6 | y=537.5 | Rs.
x=382.1 | y=537.5 | 117
x=403.8 | y=537.5 | crores.
x=439.1 | y=537.5 | The
x=461.5 | y=537.5 | facility
x=498.0 | y=537.5 | will
x=95.5 | y=550.3 | manufacture
x=156.3 | y=550.3 | high-power
x=212.8 | y=550.3 | discrete
x=252.5 | y=550.3 | semiconductor
x=323.0 | y=550.3 | devices.
x=364.0 | y=550.3 | The
x=387.0 | y=550.3 | production
x=439.9 | y=550.3 | capacity
x=482.4 | y=550.3 | will
x=505.1 | y=550.3 | be
x=95.5 | y=563.0 | around
x=129.0 | y=563.0 | 158.38
x=162.0 | y=563.0 | million
x=196.3 | y=563.0 | units/annum
x=77.5 | y=583.3 | 10.
x=95.5 | y=583.3 | Advanced
x=150.7 | y=583.3 | System
x=192.2 | y=583.3 | in
x=209.4 | y=583.3 | Package
x=256.4 | y=583.3 | Technologies
x=325.4 | y=583.3 | Private
x=367.6 | y=583.3 | Limited
x=412.8 | y=583.3 | (ASIP)
x=447.9 | y=583.3 | is
x=463.2 | y=583.3 | establishing
x=95.5 | y=596.8 | semiconductor
x=163.3 | y=596.8 | manufacturing
x=230.0 | y=596.8 | facility
x=263.7 | y=596.8 | in
x=275.0 | y=596.8 | Andhra
x=311.0 | y=596.8 | Pradesh,
x=351.1 | y=596.8 | with
x=373.4 | y=596.8 | an
x=386.6 | y=596.8 | investment
x=437.6 | y=596.8 | of
x=449.6 | y=596.8 | Rs.
x=466.6 | y=596.8 | 480
x=485.9 | y=596.8 | crores.
x=95.5 | y=610.1 | The
x=115.5 | y=610.1 | production
x=166.0 | y=610.1 | capacity
x=205.3 | y=610.1 | of
x=217.3 | y=610.1 | the
x=233.5 | y=610.1 | facility
x=267.3 | y=610.1 | would
x=297.5 | y=610.1 | be
x=310.7 | y=610.1 | around
x=344.0 | y=610.1 | 96
x=357.5 | y=610.1 | million
x=391.7 | y=610.1 | units/annum.

In [51]:
from pathlib import Path
import pdfplumber

pdf_path = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/ISM_Projects/"
    "ISM_Approved_Projects_Feb2026.pdf"
)

output_path = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/ISM_Projects/"
    "ISM_Approved_Projects_Page3_Raw.txt"
)

with pdfplumber.open(pdf_path) as pdf:
    page3_text = pdf.pages[2].extract_text(
        x_tolerance=2,
        y_tolerance=3
    )

output_path.write_text(page3_text, encoding="utf-8")

print("Saved:", output_path)
print("File exists:", output_path.exists())
print("File size:", output_path.stat().st_size, "bytes")

Saved: /Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/Semiconductor/ISM_Projects/ISM_Approved_Projects_Page3_Raw.txt
File exists: True
File size: 2900 bytes

In [ ]:
BANKING STRESS DATA COLLECTION — RBI

In [52]:
import requests
from bs4 import BeautifulSoup

url = "https://www.rbi.org.in/Scripts/AnnualReportPublications.aspx"

response = requests.get(
    url,
    timeout=60,
    headers={
        "User-Agent": "Mozilla/5.0"
    }
)

print("Status code:", response.status_code)
print("Page size:", len(response.text))

soup = BeautifulSoup(response.text, "html.parser")

print("\nPage title:")
print(soup.title.get_text(strip=True) if soup.title else "No title")

print("\nLinks containing NPA / banking / financial stability:")
count = 0

for a in soup.find_all("a", href=True):
    text = a.get_text(" ", strip=True)
    href = a["href"]

    combined = (text + " " + href).lower()

    if any(keyword in combined for keyword in [
        "npa",
        "financial stability",
        "banking",
        "bank",
        "financial stability report",
        "trend and progress"
    ]):
        print(text, "→", href)
        count += 1

print("\nRelevant links found:", count)

Status code: 200
Page size: 89994

Page title:
Annual Report | Official Website of Reserve Bank of India

Links containing NPA / banking / financial stability:
College of Agricultural Banking → https://cab.rbi.org.in
Reserve Bank Staff College → /scripts/rbsc.aspx
VI. Regulation, Supervision and Financial Stability → AnnualReportPublications.aspx?Id=1466
XII. The Reserve Bank’s Accounts for 2025-26 → AnnualReportPublications.aspx?Id=1472
Bank Holidays → /Scripts/HolidayMatrixDisplay.aspx
Banking Glossary → https://shabdavali.rbi.org.in/
Instagram → https://instagram.com/reservebankofindia
LinkedIn → https://www.linkedin.com/company/reservebankofindia

Relevant links found: 8

In [53]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

base_url = "https://www.rbi.org.in/"
url = "https://www.rbi.org.in/Scripts/AnnualReportPublications.aspx?Id=1466"

response = requests.get(
    url,
    timeout=60,
    headers={"User-Agent": "Mozilla/5.0"}
)

print("Status code:", response.status_code)
print("Page size:", len(response.text))

soup = BeautifulSoup(response.text, "html.parser")

print("\nPAGE TITLE:")
print(soup.title.get_text(" ", strip=True) if soup.title else "No title")

print("\n" + "="*90)
print("LINKS FOUND")
print("="*90)

for a in soup.find_all("a", href=True):
    text = a.get_text(" ", strip=True)
    href = urljoin(base_url, a["href"])

    if text:
        print(f"{text} → {href}")

Status code: 200
Page size: 174261

PAGE TITLE:
Annual Report | Official Website of Reserve Bank of India

==========================================================================================
LINKS FOUND
==========================================================================================
Skip to main content → https://www.rbi.org.in/#mainsection
Not Pressed → javascript:__doPostBack('UsrFontCntr$LinkBtnSpace','')
Not Pressed → javascript:__doPostBack('UsrFontCntr$LinkBtnFontIncrease','')
Pressed → javascript:__doPostBack('UsrFontCntr$LinkBtnFontRegular','')
Not Pressed → javascript:__doPostBack('UsrFontCntr$LinkBtnFontDecrease','')
Not Pressed → javascript:__doPostBack('UsrFontCntr$LinkBtnAccessibilty','')
Pressed → javascript:__doPostBack('UsrFontCntr$LinkBtnUndoAccessibilty','')
Not Pressed → javascript:__doPostBack('UsrFontCntr$LinkBtnGreyScale','')
हिंदी → https://www.rbi.org.in/
Home → https://rbi.org.in/home.aspx
About Us ▼ → https://www.rbi.org.in/
About Us → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx
Organisation & Functions ▶ → https://www.rbi.org.in/
Organisation Structure → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=OrganizationStructure.htm
Departments → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=Depts.htm
Offices → https://www.rbi.org.in/Regionaloffices.aspx
Training Establishment ▶ → https://www.rbi.org.in/
College of Agricultural Banking → https://cab.rbi.org.in
Reserve Bank Staff College → https://www.rbi.org.in/scripts/rbsc.aspx
College of Supervisors → https://cos.rbi.org.in/
RBI's Functions and Working → https://www.rbi.org.in/scripts/OccasionalPublications.aspx?head=RBI%27s%20Functions%20and%20Working
Governors → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=PastGovernors.htm
Deputy Governors → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=deputygovernors.htm
Executive Directors → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=ExecutiveDirectors.htm
Media Kit → https://www.rbi.org.in/AboutUsDisplay.aspx?pg=mediakit.htm
Communication Policy of RBI → https://www.rbi.org.in/CommunicationPolicy.aspx
Sources of Information ▶ → https://www.rbi.org.in/
Annual Publications → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#AP
Half-yearly Publications → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#HP
Quarterly Publications → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#QP
Monthly Publications → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#MP
Weekly Publications → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#WP
Occasional Publications → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#OP
SDDS → https://www.rbi.org.in/scripts/SDDSview.aspx
NSDP → https://www.rbi.org.in/scripts/BS_NSDPDisplay.aspx
Data Releases → https://www.rbi.org.in/scripts/Statistics.aspx
Publications available on Subscription → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#PS
General Information → https://www.rbi.org.in/scripts/AboutUsDisplay.aspx?pg=AllPublications.htm#GI
RBI History → https://www.rbi.org.in/scripts/Project1.aspx
Museum ▶ → https://www.rbi.org.in/
The RBI Museum → https://therbimuseum.rbi.org.in/
RBI Monetary Museum → https://www.rbi.org.in/scripts/ic_museum.aspx
Notification ▼ → https://www.rbi.org.in/
Notifications → https://www.rbi.org.in/scripts/NotificationUser.aspx
Master Directions → https://www.rbi.org.in/scripts/BS_ViewMasterDirections.aspx
Master Circulars → https://www.rbi.org.in/scripts/BS_ViewMasterCirculardetails.aspx
Amendment Directions → https://www.rbi.org.in/scripts/Fs_AmendmentDirections.aspx
Draft Notifications/Guidelines ▶ → https://www.rbi.org.in/
Draft Notifications/Guidelines → https://www.rbi.org.in/scripts/DraftNotificationsGuildelines.aspx
Draft Directions (RE-wise) → https://www.rbi.org.in/scripts/BS_ViewREwiseDraftDirections.aspx
Index To RBI Circulars → https://www.rbi.org.in/scripts/BS_CircularIndexDisplay.aspx
Standalone Circulars → https://www.rbi.org.in/scripts/BS_ViewListofstandalonecirculars.aspx
Circulars Withdrawn → https://www.rbi.org.in/scripts/NotificationUserWithdrawnCircular.aspx
Press Releases → https://www.rbi.org.in/scripts/BS_PressReleaseDisplay.aspx
Speeches & Media Interactions ▼ → https://www.rbi.org.in/
Speeches → https://www.rbi.org.in/scripts/BS_ViewSpeeches.aspx
Media Interactions → https://www.rbi.org.in/scripts/BS_ViewInterviews.aspx
Memorial Lectures → https://www.rbi.org.in/scripts/Lectures.aspx
Podcasts → https://www.rbi.org.in/scripts/BS_ViewPodcast.aspx
Publications ▼ → https://www.rbi.org.in/
Biennial → https://www.rbi.org.in/scripts/Publications.aspx?publication=Biennial
Annual → https://www.rbi.org.in/scripts/Publications.aspx?publication=Annual
Half-Yearly → https://www.rbi.org.in/scripts/Publications.aspx?publication=HalfYearly
Quarterly → https://www.rbi.org.in/scripts/Publications.aspx?publication=Quarterly
Bi-monthly → https://www.rbi.org.in/scripts/Publications.aspx?publication=Bimonthly
Monthly → https://www.rbi.org.in/scripts/Publications.aspx?publication=Monthly
Weekly → https://www.rbi.org.in/scripts/Publications.aspx?publication=Weekly
Occasional → https://www.rbi.org.in/scripts/Publications.aspx?publication=Occasional
Reports → https://www.rbi.org.in/scripts/Publications.aspx?publication=Reports
Working Papers → https://www.rbi.org.in/scripts/OccasionalPublications.aspx?head=Working Papers
Legal Framework ▼ → https://www.rbi.org.in/
Act → https://www.rbi.org.in/scripts/Act.aspx
Rules → https://www.rbi.org.in/scripts/Rules.aspx
Regulations → https://www.rbi.org.in/scripts/Regulations.aspx
Schemes → https://www.rbi.org.in/scripts/Schemes.aspx
Research ▼ → https://www.rbi.org.in/
External Research Schemes → https://www.rbi.org.in/Scripts/ExternalResearchSchemes.aspx
RBI Occasional Papers → https://www.rbi.org.in/Scripts/OccasionalPapers.aspx
Working Papers → https://www.rbi.org.in/Scripts/OccasionalPublications.aspx?head=Working%20Papers
RBI Bulletin → https://www.rbi.org.in/Scripts/BS_ViewBulletin.aspx
History → https://www.rbi.org.in/Scripts/Project1.aspx
DRG Studies → https://www.rbi.org.in/Scripts/Occas_DRG_Studies.aspx
KLEMS → https://www.rbi.org.in/Scripts/KLEMS.aspx
State Statistics and Finances → https://www.rbi.org.in/Scripts/StateStatisticsFinances.aspx
Statistics ▼ → https://www.rbi.org.in/
Data Releases → https://www.rbi.org.in/scripts/Statistics.aspx
Database on Indian Economy → https://data.rbi.org.in
Public Debt Statistics → https://www.rbi.org.in/scripts/FS_PDS.aspx
Regulatory Reporting ▼ → https://www.rbi.org.in/
List of Returns → https://www.rbi.org.in/scripts/BS_Listofallreturns.aspx
Data Definition → https://www.rbi.org.in/scripts/DataDefinition.aspx
Validation rules/ Taxonomy → https://www.rbi.org.in/scripts/ValidationRules.aspx
List of RBI Reporting Portals → https://www.rbi.org.in/scripts/ReportingPlaform.aspx
FAQs of RBI Reporting Portals → https://www.rbi.org.in/scripts/ReportingFAQ.aspx
Home → https://www.rbi.org.in/home.aspx
Publications → https://www.rbi.org.in/publications.aspx
Annual → https://www.rbi.org.in/publications.aspx
Annual Report Of The RBI → https://www.rbi.org.in/AnnualReportMainDisplay.aspx
VI. Regulation, Supervision and Financial Stability → https://www.rbi.org.in/AnnualReportPublications.aspx?year=2012
Section 2 → https://www.rbi.org.in/#SE2
Section 3 → https://www.rbi.org.in/#SE3
Section 4 → https://www.rbi.org.in/#SE4
Section 5 → https://www.rbi.org.in/#SE5
last section → https://www.rbi.org.in/#SE6
1 → https://www.rbi.org.in/#F1
2 → https://www.rbi.org.in/#F2
Box VI.1 → https://www.rbi.org.in/#BOVI1
3 → https://www.rbi.org.in/#F3
Table → https://www.rbi.org.in/#BOVIT1
4 → https://www.rbi.org.in/#F4
Box VI.2 → https://www.rbi.org.in/#BOVIT2
5 → https://www.rbi.org.in/#F5
Table VI.1 → https://www.rbi.org.in/#TVI1
6 → https://www.rbi.org.in/#F6
7 → https://www.rbi.org.in/#F7
8 → https://www.rbi.org.in/#F8
Table VI.2 → https://www.rbi.org.in/#TVI2
Table VI.3 → https://www.rbi.org.in/#TVI3
9 → https://www.rbi.org.in/#F9
Table VI.2 → https://www.rbi.org.in/#TVI2
10 → https://www.rbi.org.in/#F10
Box VI.3 → https://www.rbi.org.in/#BOVI3
11 → https://www.rbi.org.in/#F11
Table VI.4 → https://www.rbi.org.in/#TVI4
12 → https://www.rbi.org.in/#F12
press release dated April 9, 2025 → https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60190
Index → https://www.rbi.org.in/Scripts/AnnualReportPublications.aspx?year=2026
2026 → https://www.rbi.org.in/
2025 → https://www.rbi.org.in/
2024 → https://www.rbi.org.in/
2023 → https://www.rbi.org.in/
2022 → https://www.rbi.org.in/
2021 → https://www.rbi.org.in/
2020 → https://www.rbi.org.in/
2019 → https://www.rbi.org.in/
2018 → https://www.rbi.org.in/
2017 → https://www.rbi.org.in/
Archives → javascript:void(0);
2016 → https://www.rbi.org.in/
2015 → https://www.rbi.org.in/
2014 → https://www.rbi.org.in/
2013 → https://www.rbi.org.in/
2012 → https://www.rbi.org.in/
2011 → https://www.rbi.org.in/
2010 → https://www.rbi.org.in/
2009 → https://www.rbi.org.in/
2008 → https://www.rbi.org.in/
2007 → https://www.rbi.org.in/
2006 → https://www.rbi.org.in/
2005 → https://www.rbi.org.in/
2004 → https://www.rbi.org.in/
2003 → https://www.rbi.org.in/
2002 → https://www.rbi.org.in/
2001 → https://www.rbi.org.in/
2000 → https://www.rbi.org.in/
1999 → https://www.rbi.org.in/
1998 → https://www.rbi.org.in/
1997 → https://www.rbi.org.in/
1996 → https://www.rbi.org.in/
1995 → https://www.rbi.org.in/
1994 → https://www.rbi.org.in/
1993 → https://www.rbi.org.in/
1992 → https://www.rbi.org.in/
1991 → https://www.rbi.org.in/
1990 → https://www.rbi.org.in/
Top → https://www.rbi.org.in/#top
Back to previous page → javascript:history.back()
Bank Holidays → https://www.rbi.org.in/Scripts/HolidayMatrixDisplay.aspx
Banking Glossary → https://shabdavali.rbi.org.in/
Citizen's Charter → https://www.rbi.org.in/Scripts/CitiChart.aspx
Complaints → https://www.rbi.org.in/Scripts/Complaints.aspx
Contact Us → https://www.rbi.org.in/Scripts/contactus.aspx
COVID-19 Measures → https://www.rbi.org.in/scripts/bs_viewcontent.aspx?Id=3894
E-LMS → https://ncfe.org.in/e-lms
Events → https://www.rbi.org.in/Scripts/EventsDisplay.aspx
FAQs → https://www.rbi.org.in/Scripts/FAQDisplay.aspx
Financial Education → https://www.rbi.org.in/FinancialEducation/
Forms → https://www.rbi.org.in/Scripts/BS_ViewForms.aspx
IFSC/MICR Codes → https://www.rbi.org.in/Scripts/IFSCMICRDetails.aspx
Important Websites → https://www.rbi.org.in/Scripts/OtherLinks.aspx
Opportunities @ RBI → https://opportunities.rbi.org.in/scripts/index.aspx
RBI Clarifications → https://www.rbi.org.in/Scripts/rbi_clarification.aspx
RBI Kehta Hai → https://rbikehtahai.rbi.org.in/
RBI’s Vision and Values (652 kb) → https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
Right to Information Act → https://www.rbi.org.in/Scripts/Righttoinfoact.aspx
Tenders → https://www.rbi.org.in/Scripts/BS_ViewTenders.aspx
RSS → https://www.rbi.org.in/Scripts/rss.aspx
Twitter → https://twitter.com/RBI
YouTube → https://www.youtube.com/channel/UCIfCOl43tunZVNYafeC4RQA
Instagram → https://instagram.com/reservebankofindia
Facebook → https://www.facebook.com/RBIsays
LinkedIn → https://www.linkedin.com/company/reservebankofindia
Sitemap → https://www.rbi.org.in/Scripts/sitemap.aspx
Disclaimer → https://www.rbi.org.in/Scripts/Disclaimer.aspx
Web Information Manager → https://www.rbi.org.in/scripts/wim.aspx
Accessibility Statement (133 KB) → https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf
Screen Reader and Accessibility Help → https://www.rbi.org.in/scripts/ScreenReader.aspx

In [54]:
import pandas as pd
from io import StringIO

tables = pd.read_html(StringIO(response.text))

print("Number of tables found:", len(tables))

for i, table in enumerate(tables):
    print("\n" + "="*100)
    print(f"TABLE {i}")
    print("="*100)
    print("Shape:", table.shape)
    print(table.head(10).to_string())

Number of tables found: 11

====================================================================================================
TABLE 0
====================================================================================================
Shape: (19, 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0                                                     1
0  Box VI.1 Regulatory Communication - A Paradigm Shift From the regulatory perspective, the Reserve Bank implements a robust framework designed to establish and maintain a stable financial system. With growing complexity of the banking and financial system and widening of the regulatory parameter, regulatory instructions increased progressively, leading to compliance burden for REs and difficulty in access for stakeholders. To improve ease of access and maintain optimal number of Master Directions (MDs), the Reserve Bank recently undertook a major exercise for consolidating its regulatory instructions into MDs, which encompass all current regulatory measures/requirements. The consolidation exercise was done on an ‘as-is’ basis, i.e., without review of any regulatory instructions. Separate MDs were prepared based on the applicability to each type of REs, on each area of regulatory instructions. More than 11,000 circulars/instructions were screened and consolidated into 244 MDs, organised around 30 functions/areas of regulatory instructions across 11 types of REs (Table). Routine and administrative instructions like inclusion in the Second Schedule of the Reserve Bank of India Act were classified as standalone circulars and aggregated in one place on the website for ease of reference. In consultation with NABARD, regulatory instructions issued to RRBs, state co-operative banks and central co-operative banks were also consolidated. Following the consolidation, 9,445 circulars (including master circulars/MDs) were repealed in the area of regulation. Draft MDs were uploaded on the Reserve Bank’s website for public comments, and more than 770 comments were received from various stakeholders. Relevant suggestions like drafting errors, duplication of instructions, minor omissions, etc., were considered before releasing the consolidated final MDs on the website on November 28, 2025. The consolidation and consequent repeal of circulars is expected to significantly improve the accessibility of regulatory instructions for REs, thereby reducing their compliance cost, as well as to improve the clarity on applicability of each regulatory instruction to each type of RE. The exercise received widespread coverage in the media, with majority response pointing out to the ease of access of these regulations and the need to continue with regulatory reforms enabling achievement of India’s developmental goals. Table: Master Directions Post Consolidation Exercise Regulated Entity Number of Master Directions 1. Commercial Banks 32 2. Small Finance Banks 30 3. Payments Banks 17 4. Local Area Banks 25 5. Regional Rural Banks 22 6. Urban Co-operative Banks 26 7. Rural Co-operative Banks 25 8. All India Financial Institutions 19 9. Non-Banking Financial Companies 35 10. Asset Reconstruction Companies 4 11. Credit Information Companies 2 Digital Banking Channels Authorisation# 7 Total 244 #: Seven new RE-wise MDs on Digital Banking Channels Authorisation were issued. Source: RBI. Post the consolidation exercise, Department of Regulation has constituted a Regulatory Review Cell with a mandate to ensure structured and systematic review of regulations in a time bound manner. The internal review of regulations, through the channel of the Advisory Group on Regulation, has commenced with the review of Master Directions issued for a functional area in the quarter ended March 2026. Source: RBI.                                                   NaN
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Table: Master Directions Post Consolidation Exercise  Table: Master Directions Post Consolidation Exercise
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Regulated Entity                           Number of Master Directions
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1. Commercial Banks                                                    32

In [55]:
keywords = [
    "NPA",
    "GNPA",
    "NNPA",
    "capital adequacy",
    "CRAR",
    "gross non-performing",
    "net non-performing"
]

print("\n\nTABLES RELEVANT TO BANKING STRESS")
print("="*100)

for i, table in enumerate(tables):
    text = table.to_string().lower()

    if any(keyword.lower() in text for keyword in keywords):
        print(f"\n>>> TABLE {i}")
        print(table.to_string(index=False))

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [56]:
# Only display links relevant to banking stress / NPA / financial stability

keywords = [
    "NPA",
    "Non-Performing",
    "Financial Stability",
    "Asset Quality",
    "Gross NPA",
    "Net NPA",
    "Banking",
    "Capital Adequacy",
    "Stress Test",
    "Provisioning"
]

relevant_links = []

for link in links:
    text = link.get_text(" ", strip=True)
    href = link.get("href", "")

    if any(k.lower() in text.lower() for k in keywords):
        relevant_links.append((text, href))

print("Relevant links:", len(relevant_links))

for text, href in relevant_links:
    print(f"{text} → {href}")

AttributeError: 'dict' object has no attribute 'get_text'

In [57]:
# Inspect the structure of links first
print(type(links))
print(type(links[0]))
print(links[0])

<class 'list'>
<class 'dict'>
{'text': 'Statements I and II', 'url': 'http://rbidocs.rbi.org.in/rdocs/content/docs/IEPR559020915_SD1.xls'}

In [58]:
keywords = [
    "NPA",
    "non-performing",
    "non performing",
    "financial stability",
    "banking",
    "asset quality",
    "stress",
    "capital adequacy",
    "provisioning"
]

relevant_links = []

for link in links:
    text = str(link.get("text", "")).strip()
    href = str(link.get("href", "")).strip()

    combined = f"{text} {href}".lower()

    if any(k.lower() in combined for k in keywords):
        relevant_links.append({
            "text": text,
            "href": href
        })

print("=" * 80)
print("RELEVANT RBI LINKS")
print("=" * 80)

for item in relevant_links:
    print(f"{item['text']} → {item['href']}")

print("\nTotal relevant links:", len(relevant_links))

================================================================================
RELEVANT RBI LINKS
================================================================================

Total relevant links: 0

In [59]:
from bs4 import BeautifulSoup
import requests

url = "https://www.rbi.org.in/AnnualReportMainDisplay.aspx"

response = requests.get(url, timeout=30)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

keywords = [
    "NPA",
    "non-performing",
    "financial stability",
    "banking",
    "asset quality",
    "stress",
    "capital adequacy",
    "provision",
    "gross NPA",
    "GNPA",
    "NNPA"
]

relevant_links = []

for a in soup.find_all("a"):
    text = a.get_text(" ", strip=True)
    href = a.get("href", "")

    combined = (text + " " + href).lower()

    if any(k.lower() in combined for k in keywords):
        relevant_links.append({
            "text": text,
            "href": href
        })

print("=" * 80)
print("RELEVANT RBI LINKS")
print("=" * 80)

print("Total relevant links:", len(relevant_links))

for i, link in enumerate(relevant_links, 1):
    print(f"\n{i}. {link['text']}")
    print("   ", link["href"])

================================================================================
RELEVANT RBI LINKS
================================================================================
Total relevant links: 2

1. College of Agricultural Banking
    https://cab.rbi.org.in

2. Banking Glossary
    https://shabdavali.rbi.org.in/

In [60]:
file_path = "RBI_Credit_Data_2019_2026.xlsx"

excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

FileNotFoundError: [Errno 2] No such file or directory: 'RBI_Credit_Data_2019_2026.xlsx'

In [61]:
print(df_clean.dtypes)

NameError: name 'df_clean' is not defined

In [62]:
import os

raw_dir = "../01_Raw_Data"

for root, dirs, files in os.walk(raw_dir):
    level = root.replace(raw_dir, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")
    
    for file in files:
        print(f"{indent}    └── {file}")

01_Raw_Data/
    └── .DS_Store
    Electronics/
        └── .DS_Store
        Imports/
        Exports/
        Production/
    RBI/
        └── .DS_Store
        Banking_Stress/
        Sectoral_Credit/
            └── PR45830062021.xlsx
            └── PR3142SD310518.xlsx
            └── SDBC28022022.xlsx
            └── PR3543EN300617R.xlsx
            └── PR519SD31082018.xlsx
            └── SIBCS29052026.xlsx
            └── PRSD28022023.xlsx
            └── SE27112020_SA1.xlsx
            └── PR101529012021.xlsx
            └── PR826ST30092019.xlsx
            └── PR784SDBC31082021.xlsx
            └── 1371PR30112023.xlsx
            └── PR242429052020.xlsx
            └── PR615SD30072021.xlsx
            └── PR3420SD290618.xlsx
            └── PR791SD30082022.xlsx
            └── SIBC1968PR29022024.xlsx
            └── PR1080SD01112016_A.xls
            └── PR2316AN310316_I.xls
            └── PR1260ST30112018.xlsx
            └── PR2827SD31052019.xlsx
            └── PR621SD29072022.xlsx
            └── IEPR26829072016.xls
            └── .DS_Store
            └── PR2586SD28032018.xlsx
            └── PR133SDBC29042022.xlsx
            └── PR2063SD08032019_ST.xlsx
            └── PR842SD31082023.xlsx
            └── PR82530092016.xls
            └── PR1016ST31102018.xlsx
            └── PR299SD31072019.xlsx
            └── PR1013SD28092023.xlsx
            └── PR3287SD05062017.xlsx
            └── PR2541280416_AN.xls
            └── SIBC28032024.xlsx
            └── SIBCS30042026.xlsx
            └── PRSD31032023.xlsx
            └── STATE290515.xls
            └── IEPR305730062016.xls
            └── SDBC30082020.xlsx
            └── SDBC30092020.xlsx
            └── SIBCPR1773310124.xlsx
            └── PR142SDC30042021.xlsx
            └── PR2159SDB31032020.xlsx
            └── PRSD30112022.xlsx
            └── Searching “This Mac”.savedSearch
            └── PR208131012018.xlsx
            └── SECDEPOL30062020.xlsx
            └── SIBCPR1611E29112024.xlsx
            └── PR2858SD27042018.xlsx
            └── PR444SDBC30062022.xlsx
            └── PR1936SDBC31032022.xlsx
            └── PRSD28042023.xlsx
            └── PR89229092017.xlsx
            └── PR676SD31072023.xlsx
            └── PR1375S301116.xls
            └── PR177929122017.xlsx
            └── PR1209SD31102023.xlsx
            └── PR3544SD30062017.xlsx
            └── SIBC30032026.xlsx
            └── IEPR1623SD022015_S1.xls
            └── PR502SD30062023.xlsx
            └── PR558AN31082016.xls
            └── IEPR1826SD022015_S1.xls
            └── Sectoral30092021.xlsx
            └── IEPR2308SD300415.xls
            └── PR1999SDB28022020.xlsx
            └── PR2569SD30042019.xlsx
            └── PR581SIBC28062024.xlsx
            └── PR119131102017.xlsx
            └── SIBCS30062026.xlsx
            └── PR149530112017.xlsx
            └── PR413SIBC31052024.xlsx
            └── PR1300SDB29112019.xlsx
            └── SDBC31122021.xlsx
            └── PRSD31012023.xlsx
            └── PR596EN31082017.xlsx
            └── PR3081SD28062019.xlsx
            └── SDBC31012022.xlsx
            └── SDC31032021FL_S1.xlsx
            └── PR1273S1115.xls
            └── PR285SDBC31052022.xlsx
            └── SIBCSJ26E31072026E.xlsx
            └── SDBC29102020.xlsx
            └── SDBC30112021.xlsx
            └── TEST_RBI_Statements_I_II.xlsx
            └── SDBC29102021.xlsx
            └── PR1805ST31012019.xlsx
            └── PR10423010AS.xls
            └── IEPR2069AS0315.xls
            └── SIBC27022026.xlsx
            └── SIBCPR183231122024.xlsx
            └── PR2298SD30042020.xlsx
            └── Industry_Wise_Deployment_Gross_Bank_Credit_2019_2026.xlsx
            └── PRSD30092022.xlsx
            └── SIBC30082024.xlsx
            └── SIBC30092024.xlsx
            └── PR1724S30122016.xls
            └── IPR8000915FST.xls
            └── SIBCPR1573291223.xlsx
            └── PR2320SD2932019.xlsx
            └── PR12531072020.xlsx
            └── IEPR11010715_SDB.xls
            └── IEPR559020915_SD1.xls
            └── SIBC30042024.xlsx
            └── PR1502ST31122018.xlsx
            └── PR2312SD28022017_A.xls
            └── PR310SD31052023.xlsx
            └── PR581SD30082019.xlsx
            └── PR116826022021_S1.xlsx
            └── PR1792290116.xls
            └── PR2786310516_AN.xls
            └── PR283310715_ST12.xls
            └── PR2041S310117.xls
            └── PR293SDBC31052021.xlsx
            └── PR1539SD311215.xls
            └── PR2326ST28022018.xlsx
            └── PRSD30122022.xlsx
            └── PR1559SDB31122019.xlsx
            └── PR1842SDB31012020.xlsx
            └── PR299SD31072017.xlsx
            └── PR267SD310718.xlsx
            └── PR865ST31122020_S1.xlsx
            └── PR2639SD31032017_A.xlsx
            └── SIBC31102024.xlsx
            └── PR2019SIBC300126.xlsx
            └── PR803SIBC31072024.xlsx
            └── PRSD31102022.xlsx
            └── PR1070SD31102019.xlsx
            └── RBI_Industry_Wise_Gross_Bank_Credit_1997_2007.xlsx.xlsx
            └── PR2941SD28042017.xlsx
            └── PR736SDBC28092018.xlsx
            └── PR2043A290216_I.xls
    Semiconductor/
        └── .DS_Store
        Semiconductor_Investment/
        ISM_Projects/
            └── ISM_Approved_Projects_Page3_Raw.txt
            └── ISM_Approved_Projects_Feb2026.pdf
        Semiconductor_Capacity/
        Policy/
    Industrial_Production/
        └── .DS_Store
    Macroeconomic/
    Policy_Semicon/
    Interest_Rates/

In [63]:
import pandas as pd
import os

iip_path = "../01_Raw_Data/Industrial_Production/dataset_2026-08-23T06_37_33.117873440Z_DEFAULT_INTEGRATION_IMF.STA_IIP_13.0.0.csv"

iip = pd.read_csv(iip_path)

print("===== IIP RAW DATA INSPECTION =====")
print("Shape:", iip.shape)

print("\nColumns:")
print(iip.columns.tolist())

print("\nFirst 10 rows:")
display(iip.head(10))

print("\nData types:")
print(iip.dtypes)

print("\nMissing values:")
print(iip.isna().sum())

/var/folders/s4/j9yxhlyd4hbc5z2flkkn328c0000gn/T/ipykernel_11886/474808999.py:6: DtypeWarning: Columns (21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  iip = pd.read_csv(iip_path)

===== IIP RAW DATA INSPECTION =====
Shape: (135603, 437)

Columns:
['DATASET', 'SERIES_CODE', 'OBS_MEASURE', 'COUNTRY', 'BOP_ACCOUNTING_ENTRY', 'INDICATOR', 'UNIT', 'FREQUENCY', 'SCALE', 'DECIMALS_DISPLAYED', 'INSTR_ASSET', 'FUNCTIONAL_CAT', 'INT_ACC_ITEM', 'SECTOR', 'ACCOUNTING_ENTRY', 'ACCOUNTS', 'FLOW_STOCK_ENTRY', 'FI_MATURITY', 'VALUATION', 'AL_TYPE', 'BOP_TYPE', 'OVERLAP', 'FR_ADJ', 'IFS_FLAG', 'BPM6_BASIS_START_DATE', 'DOI', 'FULL_DESCRIPTION', 'PUBLISHER', 'DEPARTMENT', 'AUTHOR', 'CONTACT_POINT', 'TOPIC', 'TOPIC_DATASET', 'KEYWORDS', 'KEYWORDS_DATASET', 'LANGUAGE', 'PUBLICATION_DATE', 'UPDATE_DATE', 'METHODOLOGY', 'METHODOLOGY_NOTES', 'SHORT_SOURCE_CITATION', 'FULL_SOURCE_CITATION', 'LICENSE', 'SUGGESTED_CITATION', 'KEY_INDICATOR', 'SERIES_NAME', '1948', '1948-Q1', '1948-Q2', '1948-Q3', '1948-Q4', '1949', '1949-Q1', '1949-Q2', '1949-Q3', '1949-Q4', '1950', '1950-Q1', '1950-Q2', '1950-Q3', '1950-Q4', '1951', '1951-Q1', '1951-Q2', '1951-Q3', '1951-Q4', '1952', '1952-Q1', '1952-Q2', '1952-Q3', '1952-Q4', '1953', '1953-Q1', '1953-Q2', '1953-Q3', '1953-Q4', '1954', '1954-Q1', '1954-Q2', '1954-Q3', '1954-Q4', '1955', '1955-Q1', '1955-Q2', '1955-Q3', '1955-Q4', '1956', '1956-Q1', '1956-Q2', '1956-Q3', '1956-Q4', '1957', '1957-Q1', '1957-Q2', '1957-Q3', '1957-Q4', '1958', '1958-Q1', '1958-Q2', '1958-Q3', '1958-Q4', '1959', '1959-Q1', '1959-Q2', '1959-Q3', '1959-Q4', '1960', '1960-Q1', '1960-Q2', '1960-Q3', '1960-Q4', '1961', '1961-Q1', '1961-Q2', '1961-Q3', '1961-Q4', '1962', '1962-Q1', '1962-Q2', '1962-Q3', '1962-Q4', '1963', '1963-Q1', '1963-Q2', '1963-Q3', '1963-Q4', '1964', '1964-Q1', '1964-Q2', '1964-Q3', '1964-Q4', '1965', '1965-Q1', '1965-Q2', '1965-Q3', '1965-Q4', '1966', '1966-Q1', '1966-Q2', '1966-Q3', '1966-Q4', '1967', '1967-Q1', '1967-Q2', '1967-Q3', '1967-Q4', '1968', '1968-Q1', '1968-Q2', '1968-Q3', '1968-Q4', '1969', '1969-Q1', '1969-Q2', '1969-Q3', '1969-Q4', '1970', '1970-Q1', '1970-Q2', '1970-Q3', '1970-Q4', '1971', '1971-Q1', '1971-Q2', '1971-Q3', '1971-Q4', '1972', '1972-Q1', '1972-Q2', '1972-Q3', '1972-Q4', '1973', '1973-Q1', '1973-Q2', '1973-Q3', '1973-Q4', '1974', '1974-Q1', '1974-Q2', '1974-Q3', '1974-Q4', '1975', '1975-Q1', '1975-Q2', '1975-Q3', '1975-Q4', '1976', '1976-Q1', '1976-Q2', '1976-Q3', '1976-Q4', '1977', '1977-Q1', '1977-Q2', '1977-Q3', '1977-Q4', '1978', '1978-Q1', '1978-Q2', '1978-Q3', '1978-Q4', '1979', '1979-Q1', '1979-Q2', '1979-Q3', '1979-Q4', '1980', '1980-Q1', '1980-Q2', '1980-Q3', '1980-Q4', '1981', '1981-Q1', '1981-Q2', '1981-Q3', '1981-Q4', '1982', '1982-Q1', '1982-Q2', '1982-Q3', '1982-Q4', '1983', '1983-Q1', '1983-Q2', '1983-Q3', '1983-Q4', '1984', '1984-Q1', '1984-Q2', '1984-Q3', '1984-Q4', '1985', '1985-Q1', '1985-Q2', '1985-Q3', '1985-Q4', '1986', '1986-Q1', '1986-Q2', '1986-Q3', '1986-Q4', '1987', '1987-Q1', '1987-Q2', '1987-Q3', '1987-Q4', '1988', '1988-Q1', '1988-Q2', '1988-Q3', '1988-Q4', '1989', '1989-Q1', '1989-Q2', '1989-Q3', '1989-Q4', '1990', '1990-Q1', '1990-Q2', '1990-Q3', '1990-Q4', '1991', '1991-Q1', '1991-Q2', '1991-Q3', '1991-Q4', '1992', '1992-Q1', '1992-Q2', '1992-Q3', '1992-Q4', '1993', '1993-Q1', '1993-Q2', '1993-Q3', '1993-Q4', '1994', '1994-Q1', '1994-Q2', '1994-Q3', '1994-Q4', '1995', '1995-Q1', '1995-Q2', '1995-Q3', '1995-Q4', '1996', '1996-Q1', '1996-Q2', '1996-Q3', '1996-Q4', '1997', '1997-Q1', '1997-Q2', '1997-Q3', '1997-Q4', '1998', '1998-Q1', '1998-Q2', '1998-Q3', '1998-Q4', '1999', '1999-Q1', '1999-Q2', '1999-Q3', '1999-Q4', '2000', '2000-Q1', '2000-Q2', '2000-Q3', '2000-Q4', '2001', '2001-Q1', '2001-Q2', '2001-Q3', '2001-Q4', '2002', '2002-Q1', '2002-Q2', '2002-Q3', '2002-Q4', '2003', '2003-Q1', '2003-Q2', '2003-Q3', '2003-Q4', '2004', '2004-Q1', '2004-Q2', '2004-Q3', '2004-Q4', '2005', '2005-Q1', '2005-Q2', '2005-Q3', '2005-Q4', '2006', '2006-Q1', '2006-Q2', '2006-Q3', '2006-Q4', '2007', '2007-Q1', '2007-Q2', '2007-Q3', '2007-Q4', '2008', '2008-Q1', '2008-Q2', '2008-Q3', '2008-Q4', '2009', '2009-Q1', '2009-Q2', '2009-Q3', '2009-Q4', '2010', '2010-Q1', '2010-Q2', '2010-Q3', '2010-Q4', '2011', '2011-Q1', '2011-Q2', '2011-Q3', '2011-Q4', '2012', '2012-Q1', '2012-Q2', '2012-Q3', '2012-Q4', '2013', '2013-Q1', '2013-Q2', '2013-Q3', '2013-Q4', '2014', '2014-Q1', '2014-Q2', '2014-Q3', '2014-Q4', '2015', '2015-Q1', '2015-Q2', '2015-Q3', '2015-Q4', '2016', '2016-Q1', '2016-Q2', '2016-Q3', '2016-Q4', '2017', '2017-Q1', '2017-Q2', '2017-Q3', '2017-Q4', '2018', '2018-Q1', '2018-Q2', '2018-Q3', '2018-Q4', '2019', '2019-Q1', '2019-Q2', '2019-Q3', '2019-Q4', '2020', '2020-Q1', '2020-Q2', '2020-Q3', '2020-Q4', '2021', '2021-Q1', '2021-Q2', '2021-Q3', '2021-Q4', '2022', '2022-Q1', '2022-Q2', '2022-Q3', '2022-Q4', '2023', '2023-Q1', '2023-Q2', '2023-Q3', '2023-Q4', '2024', '2024-Q1', '2024-Q2', '2024-Q3', '2024-Q4', '2025', '2025-Q1', '2025-Q2', '2025-Q3', '2025-Q4', '2026-Q1']

First 10 rows:

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,BOP_ACCOUNTING_ENTRY,INDICATOR,UNIT,FREQUENCY,SCALE,DECIMALS_DISPLAYED,...,2024-Q1,2024-Q2,2024-Q3,2024-Q4,2025,2025-Q1,2025-Q2,2025-Q3,2025-Q4,2026-Q1
0,IMF.STA:IIP(13.0.0),MLI.A_P.O_F4_S1X_NV.USD.A,OBS_VALUE,Mali,"Assets, Positions","Other investment, Loans, Monetary authorities",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IMF.STA:IIP(13.0.0),VEN.A_P.O_F4_S13_L_NV.USD.Q,OBS_VALUE,"Venezuela, República Bolivariana de","Assets, Positions","Other investment, Loans, General government, L...",US dollar,Quarterly,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IMF.STA:IIP(13.0.0),BGR.A_P.P_F511_MV.USD.A,OBS_VALUE,Bulgaria,"Assets, Positions","Portfolio investment, Listed shares",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IMF.STA:IIP(13.0.0),JOR.A_P.P_F51_MV.USD.A,OBS_VALUE,Jordan,"Assets, Positions","Portfolio investment, Equity",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IMF.STA:IIP(13.0.0),SUR.L_P.P_F5_MV.USD.Q,OBS_VALUE,Suriname,"Liabilities, Positions","Portfolio investment, Equity and investment fu...",US dollar,Quarterly,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,IMF.STA:IIP(13.0.0),VUT.L_P.O_FLAO_AFR.USD.A,OBS_VALUE,Vanuatu,"Liabilities, Positions","Other investment, Other debt instruments, Adju...",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,IMF.STA:IIP(13.0.0),ITA.L_P.P_F5_S1X_MV.USD.A,OBS_VALUE,Italy,"Liabilities, Positions","Portfolio investment, Equity and investment fu...",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,IMF.STA:IIP(13.0.0),TON.L_P.TL_AFR.USD.A,OBS_VALUE,Tonga,"Liabilities, Positions","Total liabilities, Adjusted using IMF accounti...",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,IMF.STA:IIP(13.0.0),TGO.L_P.P_F3_S1X_MV.USD.A,OBS_VALUE,Togo,"Liabilities, Positions","Portfolio investment, Debt securities, Monetar...",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,IMF.STA:IIP(13.0.0),MOZ.A_P.R_F11_MV.USD.A,OBS_VALUE,"Mozambique, Republic of","Assets, Positions","Reserve assets, Monetary gold",US dollar,Annual,Millions,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Data types:
DATASET                  object
SERIES_CODE              object
OBS_MEASURE              object
COUNTRY                  object
BOP_ACCOUNTING_ENTRY     object
                         ...
2025-Q1                 float64
2025-Q2                 float64
2025-Q3                 float64
2025-Q4                 float64
2026-Q1                 float64
Length: 437, dtype: object

Missing values:
DATASET                      0
SERIES_CODE                  0
OBS_MEASURE                  0
COUNTRY                      0
BOP_ACCOUNTING_ENTRY         0
                         ...
2025-Q1                 105664
2025-Q2                 106389
2025-Q3                 107666
2025-Q4                 108796
2026-Q1                 111008
Length: 437, dtype: int64

In [64]:
import os
import pandas as pd

# Direct historical archive reference for Table B6 (Movement of NPAs)
rbi_table_url = "https://rbi.org.in/scripts/PublicationsView.aspx?id=14708"

print("🔄 Directing engine to map RBI Table B6 matrix...")

try:
    # Read the data arrays off the page code structures
    raw_tables = pd.read_html(rbi_table_url)
    
    # Isolate the main multi-column movement table index
    npa_movement_df = raw_tables[0]
    
    # Define a clean saving location on your desktop
    output_filepath = os.path.expanduser("~/Desktop/rbi_movement_of_npas.xlsx")
    npa_movement_df.to_excel(output_filepath, index=False)
    
    print(f"\n🎉 Dataset successfully downloaded to your Mac Desktop!")
    print(f"👉 Path: {output_filepath}")

except Exception as e:
    print(f"❌ Pull sequence stopped: {e}")

🔄 Directing engine to map RBI Table B6 matrix...

🎉 Dataset successfully downloaded to your Mac Desktop!
👉 Path: /Users/shashankyadav/Desktop/rbi_movement_of_npas.xlsx

In [65]:
import os
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# ============================================================
# RBI FINANCIAL STABILITY REPORT DOWNLOADER
# ============================================================

# Your existing project folder
banking_stress_dir = "../01_Raw_Data/RBI/Banking_Stress"

# Create folder if it doesn't exist
os.makedirs(banking_stress_dir, exist_ok=True)

# RBI Financial Stability Report archive
rbi_url = "https://rbi.org.in/Scripts/FsReports.aspx"

# Request RBI page
headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(
    rbi_url,
    headers=headers,
    timeout=30
)

response.raise_for_status()

print("RBI page accessed successfully.")
print("Status code:", response.status_code)

# Parse page
soup = BeautifulSoup(response.text, "html.parser")

# Find all links
links = soup.find_all("a")

reports = []

for link in links:
    title = link.get_text(" ", strip=True)
    href = link.get("href")

    if not href:
        continue

    # Look for Financial Stability Report links
    if "Financial Stability Report" in title:
        full_url = urljoin(rbi_url, href)

        # Extract year from title
        year_match = re.search(r"(20\d{2})", title)

        if year_match:
            year = int(year_match.group(1))

            if 2019 <= year <= 2026:
                reports.append({
                    "year": year,
                    "title": title,
                    "url": full_url
                })

# Remove duplicates
unique_reports = {}

for report in reports:
    unique_reports[report["url"]] = report

reports = list(unique_reports.values())

# Sort newest to oldest
reports = sorted(
    reports,
    key=lambda x: (x["year"], x["title"]),
    reverse=True
)

print("\nReports found:")
for r in reports:
    print(f"{r['year']} | {r['title']}")
    print(r["url"])
    print()

print("Total reports found:", len(reports))

RBI page accessed successfully.
Status code: 200

Reports found:
2026 | RBI releases the Financial Stability Report, June 2026
https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050

2025 | RBI releases the Financial Stability Report, June 2025
https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739

2025 | RBI releases the Financial Stability Report, December 2025
https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922

2024 | RBI releases the Financial Stability Report, June 2024
https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169

2024 | RBI releases the Financial Stability Report, December 2024
https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409

2023 | RBI releases the Financial Stability Report, June 2023
https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943

2023 | RBI releases the Financial Stability Report, December 2023
https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005

Total reports found: 7

In [66]:
# ============================================================
# DOWNLOAD RBI FSR REPORTS
# ============================================================

downloaded = []
failed = []

for report in reports:

    year = report["year"]
    title = report["title"]
    url = report["url"]

    # Clean filename
    safe_title = re.sub(r'[\\/*?:"<>|]', "", title)
    filename = f"{safe_title}.pdf"

    filepath = os.path.join(
        banking_stress_dir,
        filename
    )

    print("=" * 70)
    print("Downloading:", title)
    print("URL:", url)

    try:

        pdf_response = requests.get(
            url,
            headers=headers,
            timeout=60
        )

        pdf_response.raise_for_status()

        # Check whether the response actually looks like a PDF
        content_type = pdf_response.headers.get(
            "Content-Type", ""
        ).lower()

        if (
            "pdf" not in content_type
            and not pdf_response.content.startswith(b"%PDF")
        ):
            raise ValueError(
                f"Response does not appear to be a PDF. "
                f"Content-Type: {content_type}"
            )

        with open(filepath, "wb") as f:
            f.write(pdf_response.content)

        size_mb = os.path.getsize(filepath) / (1024 * 1024)

        print(f"Saved: {filename}")
        print(f"Size: {size_mb:.2f} MB")

        downloaded.append(filepath)

    except Exception as e:

        print("FAILED:", e)

        failed.append({
            "title": title,
            "url": url,
            "error": str(e)
        })

print("\n" + "=" * 70)
print("DOWNLOAD COMPLETE")
print("=" * 70)

print("Successfully downloaded:", len(downloaded))
print("Failed:", len(failed))

if failed:
    print("\nFailed reports:")
    for item in failed:
        print(item["title"])
        print(item["error"])

======================================================================
Downloading: RBI releases the Financial Stability Report, June 2026
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
FAILED: Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
======================================================================
Downloading: RBI releases the Financial Stability Report, June 2025
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
FAILED: Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
======================================================================
Downloading: RBI releases the Financial Stability Report, December 2025
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
FAILED: Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
======================================================================
Downloading: RBI releases the Financial Stability Report, June 2024
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
FAILED: Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
======================================================================
Downloading: RBI releases the Financial Stability Report, December 2024
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
FAILED: Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
======================================================================
Downloading: RBI releases the Financial Stability Report, June 2023
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943
FAILED: Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
======================================================================
Downloading: RBI releases the Financial Stability Report, December 2023
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
FAILED: Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8

======================================================================
DOWNLOAD COMPLETE
======================================================================
Successfully downloaded: 0
Failed: 7

Failed reports:
RBI releases the Financial Stability Report, June 2026
Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
RBI releases the Financial Stability Report, June 2025
Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
RBI releases the Financial Stability Report, December 2025
Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
RBI releases the Financial Stability Report, June 2024
Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
RBI releases the Financial Stability Report, December 2024
Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
RBI releases the Financial Stability Report, June 2023
Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8
RBI releases the Financial Stability Report, December 2023
Response does not appear to be a PDF. Content-Type: text/html; charset=utf-8

In [67]:
print("\n===== BANKING STRESS FOLDER =====")

files = sorted(
    os.listdir(banking_stress_dir)
)

for file in files:
    print(file)

print("\nTotal files:", len(files))

===== BANKING STRESS FOLDER =====
.DS_Store
_6.Movement of Non Performing Assets (NPAs) of Scheduled Commercial Banks.xlsx

Total files: 2

In [68]:
# ============================================================
# RBI FSR - FIND ACTUAL PDF LINKS AND DOWNLOAD
# ============================================================

import os
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

banking_stress_dir = "../01_Raw_Data/RBI/Banking_Stress"

os.makedirs(banking_stress_dir, exist_ok=True)

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/139.0 Safari/537.36"
    )
}

downloaded = []
failed = []

for report in reports:

    title = report["title"]
    page_url = report["url"]

    print("\n" + "=" * 75)
    print("REPORT:", title)
    print("REPORT PAGE:", page_url)

    try:

        # ----------------------------------------------------
        # STEP 1: Open RBI report page
        # ----------------------------------------------------

        page_response = requests.get(
            page_url,
            headers=headers,
            timeout=60
        )

        page_response.raise_for_status()

        soup = BeautifulSoup(
            page_response.text,
            "html.parser"
        )

        # ----------------------------------------------------
        # STEP 2: Find PDF links
        # ----------------------------------------------------

        pdf_links = []

        for a in soup.find_all("a", href=True):

            href = a["href"]
            text = a.get_text(" ", strip=True)

            full_url = urljoin(
                page_url,
                href
            )

            combined = (
                str(href) + " " +
                str(text)
            ).lower()

            if (
                ".pdf" in combined
                or "pdf" in combined
                or "download" in combined
            ):
                pdf_links.append(
                    (text, full_url)
                )

        # Remove duplicates
        unique_pdf_links = []

        seen = set()

        for text, url in pdf_links:

            if url not in seen:
                unique_pdf_links.append(
                    (text, url)
                )
                seen.add(url)

        print(
            "Possible PDF/download links found:",
            len(unique_pdf_links)
        )

        if not unique_pdf_links:

            raise ValueError(
                "No PDF/download link found on RBI page."
            )

        # ----------------------------------------------------
        # STEP 3: Display links before downloading
        # ----------------------------------------------------

        for i, (text, url) in enumerate(
            unique_pdf_links,
            start=1
        ):
            print(f"{i}. {text}")
            print(f"   {url}")

        # ----------------------------------------------------
        # STEP 4: Try each candidate until actual PDF found
        # ----------------------------------------------------

        pdf_saved = False

        for text, pdf_url in unique_pdf_links:

            try:

                pdf_response = requests.get(
                    pdf_url,
                    headers=headers,
                    timeout=90
                )

                pdf_response.raise_for_status()

                content_type = (
                    pdf_response
                    .headers
                    .get("Content-Type", "")
                    .lower()
                )

                is_pdf = (
                    "application/pdf"
                    in content_type
                    or pdf_response.content.startswith(b"%PDF")
                )

                if not is_pdf:
                    continue

                # ------------------------------------------------
                # Filename
                # ------------------------------------------------

                safe_title = re.sub(
                    r'[\\/*?:"<>|]',
                    "",
                    title
                )

                filename = (
                    safe_title
                    .replace("RBI releases the ", "")
                    .strip()
                    + ".pdf"
                )

                filepath = os.path.join(
                    banking_stress_dir,
                    filename
                )

                # ------------------------------------------------
                # Save PDF
                # ------------------------------------------------

                with open(
                    filepath,
                    "wb"
                ) as f:
                    f.write(
                        pdf_response.content
                    )

                size_mb = (
                    os.path.getsize(filepath)
                    / (1024 * 1024)
                )

                print(
                    f"\nSUCCESS → {filename}"
                )

                print(
                    f"Size: {size_mb:.2f} MB"
                )

                downloaded.append(
                    filepath
                )

                pdf_saved = True

                break

            except Exception:
                continue

        if not pdf_saved:

            raise ValueError(
                "Found links, but none returned a valid PDF."
            )

    except Exception as e:

        print("FAILED:", e)

        failed.append({
            "title": title,
            "url": page_url,
            "error": str(e)
        })


# ============================================================
# FINAL RESULT
# ============================================================

print("\n" + "=" * 75)
print("FSR DOWNLOAD COMPLETE")
print("=" * 75)

print(
    "Successfully downloaded:",
    len(downloaded)
)

print(
    "Failed:",
    len(failed)
)

if failed:

    print("\nFAILED REPORTS:")

    for item in failed:

        print("\n", item["title"])
        print("Reason:", item["error"])

===========================================================================
REPORT: RBI releases the Financial Stability Report, June 2026
REPORT PAGE: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
Possible PDF/download links found: 3
1.
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR5720E56F0A4611A404EACBD71F2207673A2.PDF
2. RBI’s Vision and Values (652 kb)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
3. Accessibility Statement (133 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

SUCCESS → Financial Stability Report, June 2026.pdf
Size: 0.15 MB

===========================================================================
REPORT: RBI releases the Financial Stability Report, June 2025
REPORT PAGE: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
Possible PDF/download links found: 3
1.
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR62462AD650C8168481BAC17613CC54CFED8.PDF
2. RBI’s Vision and Values (652 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
3. Accessibility Statement (133 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

SUCCESS → Financial Stability Report, June 2025.pdf
Size: 0.29 MB

===========================================================================
REPORT: RBI releases the Financial Stability Report, December 2025
REPORT PAGE: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
Possible PDF/download links found: 3
1.
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR1806ADBB5E4E8B1E4BD3A83DFBE9FF8D4308.PDF
2. RBI’s Vision and Values (652 kb)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
3. Accessibility Statement (133 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

SUCCESS → Financial Stability Report, December 2025.pdf
Size: 0.35 MB

===========================================================================
REPORT: RBI releases the Financial Stability Report, June 2024
REPORT PAGE: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
Possible PDF/download links found: 3
1.
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR5729DB37EA29CDE456DAFFF4DAC3D7FAA20.PDF
2. RBI’s Vision and Values (652 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
3. Accessibility Statement (133 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

SUCCESS → Financial Stability Report, June 2024.pdf
Size: 0.32 MB

===========================================================================
REPORT: RBI releases the Financial Stability Report, December 2024
REPORT PAGE: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
Possible PDF/download links found: 3
1.
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR181199C5DE637D2248E7B6DE7FD092FA91D1.PDF
2. RBI’s Vision and Values (652 kb)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
3. Accessibility Statement (133 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

SUCCESS → Financial Stability Report, December 2024.pdf
Size: 0.32 MB

===========================================================================
REPORT: RBI releases the Financial Stability Report, June 2023
REPORT PAGE: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943
Possible PDF/download links found: 3
1.
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR493FSR27F6AB0B5CEA4F9AA39688FFC08B8D32.PDF
2. RBI’s Vision and Values (652 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
3. Accessibility Statement (133 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

SUCCESS → Financial Stability Report, June 2023.pdf
Size: 0.27 MB

===========================================================================
REPORT: RBI releases the Financial Stability Report, December 2023
REPORT PAGE: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
Possible PDF/download links found: 3
1.
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR1555FSR7F2F82BCFF6845918D16C49EAA6E7E89.PDF
2. RBI’s Vision and Values (652 kb)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
3. Accessibility Statement (133 KB)
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

SUCCESS → Financial Stability Report, December 2023.pdf
Size: 0.26 MB

===========================================================================
FSR DOWNLOAD COMPLETE
===========================================================================
Successfully downloaded: 7
Failed: 0

In [69]:
print("\n===== BANKING STRESS FILES =====\n")

for f in sorted(os.listdir(banking_stress_dir)):
    print(f)

===== BANKING STRESS FILES =====

.DS_Store
Financial Stability Report, December 2023.pdf
Financial Stability Report, December 2024.pdf
Financial Stability Report, December 2025.pdf
Financial Stability Report, June 2023.pdf
Financial Stability Report, June 2024.pdf
Financial Stability Report, June 2025.pdf
Financial Stability Report, June 2026.pdf
_6.Movement of Non Performing Assets (NPAs) of Scheduled Commercial Banks.xlsx

In [70]:
import os
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# ============================================================
# RBI FINANCIAL STABILITY REPORT DOWNLOADER
# 2010–2026
# ============================================================

# Your existing project folder
banking_stress_dir = "../01_Raw_Data/RBI/Banking_Stress"

os.makedirs(banking_stress_dir, exist_ok=True)

# RBI Financial Stability Reports page
url = "https://rbi.org.in/Scripts/FsReports.aspx"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/126.0 Safari/537.36"
    )
}

print("=" * 70)
print("RBI FINANCIAL STABILITY REPORT COLLECTION")
print("=" * 70)

response = requests.get(
    url,
    headers=headers,
    timeout=30
)

print("Status code:", response.status_code)
print("Content type:", response.headers.get("Content-Type"))

response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

# ------------------------------------------------------------
# Find all links containing Financial Stability Report / FSR
# ------------------------------------------------------------

links = []

for a in soup.find_all("a", href=True):

    text = a.get_text(" ", strip=True)
    href = a["href"]

    combined = f"{text} {href}".lower()

    if (
        "financial stability report" in combined
        or "financialstabilityreport" in combined
        or "fsr" in combined
    ):
        full_url = urljoin(url, href)

        links.append({
            "text": text,
            "url": full_url
        })

# Remove duplicates
unique_links = {}

for item in links:
    unique_links[item["url"]] = item

links = list(unique_links.values())

print("\nPotential FSR links found:", len(links))

for i, item in enumerate(links[:20], 1):
    print(f"{i}. {item['text']}")
    print(f"   {item['url']}")

# ------------------------------------------------------------
# Download reports
# ------------------------------------------------------------

downloaded = []
failed = []

for i, item in enumerate(links, 1):

    report_name = item["text"].strip()

    # Ignore obviously unrelated links
    if not any(
        word in report_name.lower()
        for word in ["financial", "stability", "fsr"]
    ):
        continue

    # Clean filename
    filename = re.sub(
        r'[<>:"/\\|?*]',
        "_",
        report_name
    )

    filename = re.sub(
        r"\s+",
        " ",
        filename
    ).strip()

    if not filename.lower().endswith(".pdf"):
        filename += ".pdf"

    filepath = os.path.join(
        banking_stress_dir,
        filename
    )

    # Don't download files already present
    if os.path.exists(filepath):
        print("Already exists:", filename)
        continue

    try:

        r = requests.get(
            item["url"],
            headers=headers,
            timeout=60
        )

        content_type = r.headers.get(
            "Content-Type",
            ""
        ).lower()

        # Accept PDFs even if RBI doesn't specify perfect MIME type
        if (
            "application/pdf" in content_type
            or r.content[:4] == b"%PDF"
        ):

            with open(filepath, "wb") as f:
                f.write(r.content)

            downloaded.append(filename)

            print("Downloaded:", filename)

        else:

            failed.append({
                "name": filename,
                "url": item["url"],
                "reason": f"Not PDF ({content_type})"
            })

            print("FAILED:", filename)
            print("URL:", item["url"])
            print("Content-Type:", content_type)

    except Exception as e:

        failed.append({
            "name": filename,
            "url": item["url"],
            "reason": str(e)
        })

        print("ERROR:", filename)
        print(e)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DOWNLOAD SUMMARY")
print("=" * 70)

print("Successfully downloaded:", len(downloaded))
print("Failed:", len(failed))

print("\nFolder:")
print(os.path.abspath(banking_stress_dir))

if downloaded:
    print("\nDownloaded files:")
    for x in downloaded:
        print("✓", x)

if failed:
    print("\nFailed files:")
    for x in failed:
        print("✗", x["name"])
        print("  Reason:", x["reason"])
        print("  URL:", x["url"])

======================================================================
RBI FINANCIAL STABILITY REPORT COLLECTION
======================================================================
Status code: 200
Content type: text/html; charset=utf-8

Potential FSR links found: 7
1. RBI releases the Financial Stability Report, June 2026
   https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
2. RBI releases the Financial Stability Report, December 2025
   https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
3. RBI releases the Financial Stability Report, June 2025
   https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
4. RBI releases the Financial Stability Report, December 2024
   https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
5. RBI releases the Financial Stability Report, June 2024
   https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
6. RBI releases the Financial Stability Report, December 2023
   https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
7. RBI releases the Financial Stability Report, June 2023
   https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943
FAILED: RBI releases the Financial Stability Report, June 2026.pdf
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
Content-Type: text/html; charset=utf-8
FAILED: RBI releases the Financial Stability Report, December 2025.pdf
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
Content-Type: text/html; charset=utf-8
FAILED: RBI releases the Financial Stability Report, June 2025.pdf
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
Content-Type: text/html; charset=utf-8
FAILED: RBI releases the Financial Stability Report, December 2024.pdf
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
Content-Type: text/html; charset=utf-8
FAILED: RBI releases the Financial Stability Report, June 2024.pdf
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
Content-Type: text/html; charset=utf-8
FAILED: RBI releases the Financial Stability Report, December 2023.pdf
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
Content-Type: text/html; charset=utf-8
FAILED: RBI releases the Financial Stability Report, June 2023.pdf
URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943
Content-Type: text/html; charset=utf-8

======================================================================
DOWNLOAD SUMMARY
======================================================================
Successfully downloaded: 0
Failed: 7

Folder:
/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/RBI/Banking_Stress

Failed files:
✗ RBI releases the Financial Stability Report, June 2026.pdf
  Reason: Not PDF (text/html; charset=utf-8)
  URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
✗ RBI releases the Financial Stability Report, December 2025.pdf
  Reason: Not PDF (text/html; charset=utf-8)
  URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
✗ RBI releases the Financial Stability Report, June 2025.pdf
  Reason: Not PDF (text/html; charset=utf-8)
  URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
✗ RBI releases the Financial Stability Report, December 2024.pdf
  Reason: Not PDF (text/html; charset=utf-8)
  URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
✗ RBI releases the Financial Stability Report, June 2024.pdf
  Reason: Not PDF (text/html; charset=utf-8)
  URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
✗ RBI releases the Financial Stability Report, December 2023.pdf
  Reason: Not PDF (text/html; charset=utf-8)
  URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
✗ RBI releases the Financial Stability Report, June 2023.pdf
  Reason: Not PDF (text/html; charset=utf-8)
  URL: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943

In [72]:
import os
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin, unquote

# ============================================================
# RBI FINANCIAL STABILITY REPORT
# PDF EXTRACTION FROM PRESS-RELEASE PAGES
# ============================================================

banking_stress_dir = "../01_Raw_Data/RBI/Banking_Stress"
os.makedirs(banking_stress_dir, exist_ok=True)

session = requests.Session()

session.headers.update({
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/126.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
})

# ------------------------------------------------------------
# PRESS RELEASE URLs FOUND PREVIOUSLY
# ------------------------------------------------------------

press_release_urls = [
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943",
]

print("=" * 70)
print("RBI FSR PDF EXTRACTION")
print("=" * 70)

downloaded = []
failed = []

# ------------------------------------------------------------
# PROCESS EACH PRESS RELEASE
# ------------------------------------------------------------

for press_url in press_release_urls:

    print("\n" + "-" * 70)
    print("Opening:")
    print(press_url)

    try:

        response = session.get(
            press_url,
            timeout=60
        )

        response.raise_for_status()

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # ----------------------------------------------------
        # FIND ALL LINKS
        # ----------------------------------------------------

        pdf_links = []

        for a in soup.find_all("a", href=True):

            href = a.get("href", "").strip()

            text = a.get_text(
                " ",
                strip=True
            )

            combined = (
                href + " " + text
            ).lower()

            if (
                ".pdf" in combined
                or "financial stability report" in combined
                or "fsr" in combined
                or "download" in combined
            ):

                full_url = urljoin(
                    press_url,
                    href
                )

                pdf_links.append(
                    full_url
                )

        # Remove duplicates
        pdf_links = list(dict.fromkeys(pdf_links))

        print(
            "Potential PDF links:",
            len(pdf_links)
        )

        # ----------------------------------------------------
        # TEST LINKS
        # ----------------------------------------------------

        actual_pdf = None

        for pdf_url in pdf_links:

            try:

                r = session.get(
                    pdf_url,
                    timeout=60
                )

                content_type = r.headers.get(
                    "Content-Type",
                    ""
                ).lower()

                # PDF magic number = %PDF
                if (
                    "application/pdf" in content_type
                    or r.content[:4] == b"%PDF"
                ):

                    actual_pdf = (
                        pdf_url,
                        r.content
                    )

                    break

            except Exception:
                continue

        # ----------------------------------------------------
        # SAVE PDF
        # ----------------------------------------------------

        if actual_pdf is None:

            failed.append({
                "press_release": press_url,
                "reason": "Could not locate actual PDF"
            })

            print(
                "❌ Actual PDF not found"
            )

            # Show discovered links for debugging
            for x in pdf_links:
                print("   ", x)

            continue

        pdf_url, pdf_content = actual_pdf

        # Try to determine report period from page text
        page_text = soup.get_text(
            " ",
            strip=True
        )

        match = re.search(
            r"(June|December)\s+20\d{2}",
            page_text,
            re.IGNORECASE
        )

        if match:

            period = match.group(
                0
            ).title()

        else:

            period = "Unknown_Period"

        filename = (
            f"RBI_Financial_Stability_Report_"
            f"{period.replace(' ', '_')}.pdf"
        )

        filepath = os.path.join(
            banking_stress_dir,
            filename
        )

        with open(
            filepath,
            "wb"
        ) as f:

            f.write(
                pdf_content
            )

        downloaded.append(
            filename
        )

        print(
            "✅ Downloaded:",
            filename
        )

        print(
            "PDF URL:",
            pdf_url
        )

# ------------------------------------------------------------
# SUMMARY
# ------------------------------------------------------------

print("\n")
print("=" * 70)
print("DOWNLOAD SUMMARY")
print("=" * 70)

print(
    "Successfully downloaded:",
    len(downloaded)
)

print(
    "Failed:",
    len(failed)
)

print(
    "\nSaved in:"
)

print(
    os.path.abspath(
        banking_stress_dir
    )
)

if downloaded:

    print("\nDownloaded files:")

    for f in downloaded:
        print(
            "✓",
            f
        )

if failed:

    print("\nFailed files:")

    for f in failed:
        print(
            "✗",
            f["press_release"]
        )

        print(
            "  Reason:",
            f["reason"]
        )

SyntaxError: expected 'except' or 'finally' block (12607140.py, line 232)

In [73]:
import os
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# ============================================================
# RBI FINANCIAL STABILITY REPORT DOWNLOADER
# ============================================================

banking_stress_dir = "../01_Raw_Data/RBI/Banking_Stress"

os.makedirs(banking_stress_dir, exist_ok=True)

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0"
})

# RBI FSR press-release pages
press_release_urls = [
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943",
]

downloaded = []
failed = []

print("=" * 70)
print("RBI FINANCIAL STABILITY REPORT COLLECTION")
print("=" * 70)

for press_url in press_release_urls:

    print("\nOpening:", press_url)

    try:

        # ----------------------------------------------------
        # STEP 1: OPEN RBI PRESS RELEASE
        # ----------------------------------------------------

        response = session.get(
            press_url,
            timeout=60
        )

        response.raise_for_status()

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # ----------------------------------------------------
        # STEP 2: FIND POSSIBLE PDF LINKS
        # ----------------------------------------------------

        possible_links = []

        for a in soup.find_all("a", href=True):

            href = a["href"].strip()

            text = a.get_text(
                " ",
                strip=True
            )

            combined = (
                href + " " + text
            ).lower()

            if ".pdf" in combined:

                full_url = urljoin(
                    press_url,
                    href
                )

                possible_links.append(
                    full_url
                )

        possible_links = list(
            dict.fromkeys(possible_links)
        )

        print(
            "PDF links found:",
            len(possible_links)
        )

        # ----------------------------------------------------
        # STEP 3: TEST EACH LINK
        # ----------------------------------------------------

        pdf_url = None
        pdf_data = None

        for link in possible_links:

            try:

                pdf_response = session.get(
                    link,
                    timeout=60
                )

                content_type = pdf_response.headers.get(
                    "Content-Type",
                    ""
                ).lower()

                if (
                    "application/pdf" in content_type
                    or pdf_response.content[:4] == b"%PDF"
                ):

                    pdf_url = link
                    pdf_data = pdf_response.content

                    break

            except Exception:
                pass

        # ----------------------------------------------------
        # STEP 4: IF PDF WAS NOT FOUND
        # ----------------------------------------------------

        if pdf_url is None:

            print("❌ PDF not found")

            failed.append(
                press_url
            )

            # Print links for debugging
            if possible_links:

                print(
                    "Links discovered:"
                )

                for link in possible_links:
                    print(
                        "  ",
                        link
                    )

            continue

        # ----------------------------------------------------
        # STEP 5: IDENTIFY REPORT YEAR
        # ----------------------------------------------------

        page_text = soup.get_text(
            " ",
            strip=True
        )

        match = re.search(
            r"(June|December)\s+20\d{2}",
            page_text,
            re.IGNORECASE
        )

        if match:

            period = match.group(
                0
            ).title()

        else:

            period = "Unknown"

        # ----------------------------------------------------
        # STEP 6: CREATE FILE NAME
        # ----------------------------------------------------

        filename = (
            "RBI_Financial_Stability_Report_"
            + period.replace(" ", "_")
            + ".pdf"
        )

        filepath = os.path.join(
            banking_stress_dir,
            filename
        )

        # ----------------------------------------------------
        # STEP 7: SAVE PDF
        # ----------------------------------------------------

        with open(
            filepath,
            "wb"
        ) as f:

            f.write(
                pdf_data
            )

        downloaded.append(
            filename
        )

        print(
            "✅ Downloaded:",
            filename
        )

        print(
            "   PDF URL:",
            pdf_url
        )

    except Exception as e:

        print(
            "❌ ERROR:",
            e
        )

        failed.append(
            press_url
        )


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("DOWNLOAD COMPLETE")
print("=" * 70)

print(
    "Successfully downloaded:",
    len(downloaded)
)

print(
    "Failed:",
    len(failed)
)

print("\nSaved to:")

print(
    os.path.abspath(
        banking_stress_dir
    )
)

if downloaded:

    print("\nDownloaded reports:")

    for filename in downloaded:

        print(
            "✓",
            filename
        )

if failed:

    print("\nFailed reports:")

    for url in failed:

        print(
            "✗",
            url
        )

======================================================================
RBI FINANCIAL STABILITY REPORT COLLECTION
======================================================================

Opening: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
PDF links found: 3
❌ PDF not found
Links discovered:
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR5720E56F0A4611A404EACBD71F2207673A2.PDF
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

Opening: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
PDF links found: 3
❌ PDF not found
Links discovered:
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR1806ADBB5E4E8B1E4BD3A83DFBE9FF8D4308.PDF
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

Opening: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
PDF links found: 3
❌ PDF not found
Links discovered:
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR62462AD650C8168481BAC17613CC54CFED8.PDF
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

Opening: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
PDF links found: 3
❌ PDF not found
Links discovered:
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR181199C5DE637D2248E7B6DE7FD092FA91D1.PDF
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

Opening: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
PDF links found: 3
❌ PDF not found
Links discovered:
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR5729DB37EA29CDE456DAFFF4DAC3D7FAA20.PDF
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

Opening: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
PDF links found: 3
❌ PDF not found
Links discovered:
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR1555FSR7F2F82BCFF6845918D16C49EAA6E7E89.PDF
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

Opening: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943
PDF links found: 3
❌ PDF not found
Links discovered:
   https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR493FSR27F6AB0B5CEA4F9AA39688FFC08B8D32.PDF
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf
   https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf


======================================================================
DOWNLOAD COMPLETE
======================================================================
Successfully downloaded: 0
Failed: 7

Saved to:
/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/RBI/Banking_Stress

Failed reports:
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943

In [74]:
import requests
from bs4 import BeautifulSoup

url = "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050"

r = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

print("Status:", r.status_code)
print("Length:", len(r.text))

soup = BeautifulSoup(r.text, "html.parser")

print("\nPAGE TITLE:")
print(soup.title.get_text(strip=True) if soup.title else "No title")

print("\nALL LINKS CONTAINING 'PDF', 'FSR' OR 'FINANCIAL':")

count = 0

for a in soup.find_all("a", href=True):

    text = a.get_text(" ", strip=True)
    href = a["href"]

    if any(
        x in (text + " " + href).lower()
        for x in ["pdf", "fsr", "financial"]
    ):

        print("\nTEXT:", text)
        print("HREF:", href)

        count += 1

print("\nTotal matching links:", count)

Status: 200
Length: 113501

PAGE TITLE:
Press Releases | Official Website of Reserve Bank of India

ALL LINKS CONTAINING 'PDF', 'FSR' OR 'FINANCIAL':

TEXT:
HREF: https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR5720E56F0A4611A404EACBD71F2207673A2.PDF

TEXT: Financial Stability Report (FSR)
HREF: https://www.rbi.org.in/Scripts/PublicationReportDetails.aspx?UrlPage=&ID=1319

TEXT: Financial Education
HREF: https://www.rbi.org.in/FinancialEducation/

TEXT: RBI’s Vision and Values (652 KB)
HREF: https://rbidocs.rbi.org.in/rdocs/content/pdfs/Utkarsh202910042026.pdf

TEXT: Accessibility Statement (133 KB)
HREF: https://rbidocs.rbi.org.in/rdocs/content/pdfs/Accessibility20012026.pdf

Total matching links: 5

In [75]:
import os
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# ============================================================
# RBI FINANCIAL STABILITY REPORT DOWNLOADER
# ============================================================

banking_stress_dir = "../01_Raw_Data/RBI/Banking_Stress"

os.makedirs(banking_stress_dir, exist_ok=True)

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0"
})

# RBI FSR press-release pages
press_release_urls = [
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005",
    "https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943",
]

downloaded = []
failed = []

print("=" * 70)
print("RBI FINANCIAL STABILITY REPORT COLLECTION")
print("=" * 70)

for press_url in press_release_urls:

    try:

        print("\nProcessing:", press_url)

        # ----------------------------------------------------
        # OPEN PRESS RELEASE
        # ----------------------------------------------------

        response = session.get(
            press_url,
            timeout=60
        )

        response.raise_for_status()

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # ----------------------------------------------------
        # FIND ACTUAL RBI PDF
        # ----------------------------------------------------

        pdf_url = None

        for a in soup.find_all("a", href=True):

            href = a["href"].strip()

            if ".pdf" in href.lower():

                pdf_url = href
                break

        if pdf_url is None:

            print("❌ PDF URL not found")

            failed.append(press_url)

            continue

        print("PDF found:")
        print(pdf_url)

        # ----------------------------------------------------
        # DOWNLOAD PDF
        # ----------------------------------------------------

        pdf_response = session.get(
            pdf_url,
            timeout=120
        )

        pdf_response.raise_for_status()

        # Verify PDF
        if pdf_response.content[:4] != b"%PDF":

            print("❌ Downloaded file is not a valid PDF")

            failed.append(press_url)

            continue

        # ----------------------------------------------------
        # IDENTIFY REPORT PERIOD
        # ----------------------------------------------------

        page_text = soup.get_text(
            " ",
            strip=True
        )

        match = re.search(
            r"(June|December)\s+20\d{2}",
            page_text,
            re.IGNORECASE
        )

        if match:

            period = match.group(0).title()

        else:

            period = "Unknown"

        # ----------------------------------------------------
        # FILE NAME
        # ----------------------------------------------------

        filename = (
            "RBI_Financial_Stability_Report_"
            + period.replace(" ", "_")
            + ".pdf"
        )

        filepath = os.path.join(
            banking_stress_dir,
            filename
        )

        # ----------------------------------------------------
        # SAVE
        # ----------------------------------------------------

        with open(
            filepath,
            "wb"
        ) as f:

            f.write(
                pdf_response.content
            )

        downloaded.append(filename)

        print(
            "✅ SAVED:",
            filename
        )

    except Exception as e:

        print(
            "❌ ERROR:",
            e
        )

        failed.append(press_url)


# ============================================================
# SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("DOWNLOAD COMPLETE")
print("=" * 70)

print(
    "Successfully downloaded:",
    len(downloaded)
)

print(
    "Failed:",
    len(failed)
)

print("\nFolder:")

print(
    os.path.abspath(
        banking_stress_dir
    )
)

print("\nDownloaded files:")

for f in downloaded:

    print(
        "✓",
        f
    )

if failed:

    print("\nFailed:")

    for f in failed:

        print(
            "✗",
            f
        )

======================================================================
RBI FINANCIAL STABILITY REPORT COLLECTION
======================================================================

Processing: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
PDF found:
https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR5720E56F0A4611A404EACBD71F2207673A2.PDF
❌ Downloaded file is not a valid PDF

Processing: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
PDF found:
https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR1806ADBB5E4E8B1E4BD3A83DFBE9FF8D4308.PDF
❌ Downloaded file is not a valid PDF

Processing: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
PDF found:
https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR62462AD650C8168481BAC17613CC54CFED8.PDF
❌ Downloaded file is not a valid PDF

Processing: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
PDF found:
https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR181199C5DE637D2248E7B6DE7FD092FA91D1.PDF
❌ Downloaded file is not a valid PDF

Processing: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
PDF found:
https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR5729DB37EA29CDE456DAFFF4DAC3D7FAA20.PDF
❌ Downloaded file is not a valid PDF

Processing: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
PDF found:
https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR1555FSR7F2F82BCFF6845918D16C49EAA6E7E89.PDF
❌ Downloaded file is not a valid PDF

Processing: https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943
PDF found:
https://rbidocs.rbi.org.in/rdocs/PressRelease/PDFs/PR493FSR27F6AB0B5CEA4F9AA39688FFC08B8D32.PDF
❌ Downloaded file is not a valid PDF


======================================================================
DOWNLOAD COMPLETE
======================================================================
Successfully downloaded: 0
Failed: 7

Folder:
/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/RBI/Banking_Stress

Downloaded files:

Failed:
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=63050
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=61922
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=60739
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=59409
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=58169
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=57005
✗ https://rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx?prid=55943

In [76]:
import os

base = "../01_Raw_Data/Semiconductor"

for root, dirs, files in os.walk(base):
    level = root.replace(base, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        if not file.startswith("."):
            print(f"{indent}    └── {file}")

Semiconductor/
    Semiconductor_Investment/
    ISM_Projects/
        └── ISM_Approved_Projects_Page3_Raw.txt
        └── ISM_Approved_Projects_Feb2026.pdf
    Semiconductor_Capacity/
    Policy/

In [77]:
import os
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urljoin

# ============================================================
# SEMICONDUCTOR INVESTMENT DATA COLLECTION
# Official Government Sources
# ============================================================

BASE_DIR = "../01_Raw_Data/Semiconductor/Semiconductor_Investment"

os.makedirs(BASE_DIR, exist_ok=True)

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/139.0 Safari/537.36"
    )
}

# Official MeitY pages to inspect
SOURCE_PAGES = [
    "https://www.meity.gov.in/india-semiconductor-mission",
    "https://www.meity.gov.in/offerings",
]

records = []

# ============================================================
# 1. DOWNLOAD AND SCAN OFFICIAL PAGES
# ============================================================

for page_url in SOURCE_PAGES:

    print("\n" + "=" * 70)
    print("Scanning:", page_url)
    print("=" * 70)

    try:
        response = requests.get(
            page_url,
            headers=HEADERS,
            timeout=30
        )

        print("Status:", response.status_code)

        if response.status_code != 200:
            print("Failed:", response.status_code)
            continue

        soup = BeautifulSoup(response.text, "html.parser")

        page_title = soup.title.get_text(strip=True) if soup.title else ""

        # Scan every link
        for link in soup.find_all("a", href=True):

            href = link["href"].strip()
            text = link.get_text(" ", strip=True)

            full_url = urljoin(page_url, href)

            combined_text = f"{text} {full_url}".lower()

            # Relevant semiconductor/investment keywords
            keywords = [
                "semiconductor",
                "investment",
                "fab",
                "osat",
                "atmp",
                "chip",
                "packaging",
                "display",
                "project",
                "ism"
            ]

            if any(keyword in combined_text for keyword in keywords):

                records.append({
                    "source_page": page_url,
                    "page_title": page_title,
                    "link_text": text,
                    "url": full_url
                })

    except Exception as e:
        print("ERROR:", e)


# ============================================================
# 2. REMOVE DUPLICATES
# ============================================================

links_df = pd.DataFrame(records)

if len(links_df) > 0:
    links_df = links_df.drop_duplicates(subset=["url"])

# ============================================================
# 3. SAVE SOURCE INDEX
# ============================================================

index_path = os.path.join(
    BASE_DIR,
    "Semiconductor_Investment_Source_Index.csv"
)

links_df.to_csv(index_path, index=False)

print("\n" + "=" * 70)
print("SOURCE COLLECTION COMPLETE")
print("=" * 70)

print("Sources found:", len(links_df))
print("Index saved to:")
print(index_path)

display(links_df.head(50))

======================================================================
Scanning: https://www.meity.gov.in/india-semiconductor-mission
======================================================================
Status: 200

======================================================================
Scanning: https://www.meity.gov.in/offerings
======================================================================
Status: 200

======================================================================
SOURCE COLLECTION COMPLETE
======================================================================
Sources found: 0
Index saved to:
../01_Raw_Data/Semiconductor/Semiconductor_Investment/Semiconductor_Investment_Source_Index.csv

Empty DataFrame
Columns: []
Index: []

In [78]:
# ============================================================
# DOWNLOAD RELEVANT PDF DOCUMENTS
# ============================================================

pdf_dir = os.path.join(BASE_DIR, "Official_PDFs")

os.makedirs(pdf_dir, exist_ok=True)

downloaded = 0
failed = 0

for _, row in links_df.iterrows():

    url = row["url"]

    # Only download obvious PDF links
    if ".pdf" not in url.lower():
        continue

    try:

        r = requests.get(
            url,
            headers=HEADERS,
            timeout=60
        )

        content_type = r.headers.get(
            "Content-Type",
            ""
        ).lower()

        if r.status_code != 200:
            print("FAILED:", url)
            failed += 1
            continue

        if "pdf" not in content_type and not r.content.startswith(b"%PDF"):
            print("NOT PDF:", url)
            failed += 1
            continue

        # Generate safe filename
        title = str(row["link_text"]).strip()

        if not title:
            title = "Semiconductor_Investment_Report"

        title = re.sub(
            r'[\\/*?:"<>|]',
            "_",
            title
        )

        filename = f"{title[:150]}.pdf"

        filepath = os.path.join(
            pdf_dir,
            filename
        )

        with open(filepath, "wb") as f:
            f.write(r.content)

        print("DOWNLOADED:", filename)

        downloaded += 1

    except Exception as e:

        print("ERROR:", url)
        print(e)

        failed += 1


print("\n" + "=" * 70)
print("PDF DOWNLOAD COMPLETE")
print("=" * 70)

print("Downloaded:", downloaded)
print("Failed:", failed)
print("Folder:", pdf_dir)

======================================================================
PDF DOWNLOAD COMPLETE
======================================================================
Downloaded: 0
Failed: 0
Folder: ../01_Raw_Data/Semiconductor/Semiconductor_Investment/Official_PDFs

In [79]:
import os

files_to_remove = [
    "../01_Raw_Data/Semiconductor/Semiconductor_Investment/Semiconductor_Investment_Source_Index.csv"
]

for file in files_to_remove:
    if os.path.exists(file):
        os.remove(file)

print("Empty generated files removed.")

Empty generated files removed.

In [80]:
import os

folder = "../01_Raw_Data/Semiconductor/Semiconductor_Investment"

print(os.listdir(folder))

['Official_PDFs']

In [81]:
import os
import requests

folder = "../01_Raw_Data/Semiconductor/Semiconductor_Investment"

os.makedirs(folder, exist_ok=True)

files = {
    "MeitY_Annual_Report_2025_26.pdf":
        "https://www.meity.gov.in/static/uploads/2026/04/46face7d48c8f6a97030f713ad5fdab4.pdf",

    "MeitY_Annual_Report_2024_25.pdf":
        "https://www.meity.gov.in/static/uploads/2024/12/10fcadec462c330211502fed3d24ea83.pdf"
}

headers = {
    "User-Agent": "Mozilla/5.0"
}

for filename, url in files.items():

    path = os.path.join(folder, filename)

    print("\nDownloading:", filename)

    try:
        r = requests.get(
            url,
            headers=headers,
            timeout=60
        )

        print("Status:", r.status_code)
        print("Size:", len(r.content), "bytes")

        if r.status_code == 200 and r.content.startswith(b"%PDF"):

            with open(path, "wb") as f:
                f.write(r.content)

            print("✓ Saved:", path)

        else:
            print("✗ Download failed or response isn't a PDF")

    except Exception as e:
        print("✗ ERROR:", e)

print("\n========================================")
print("DOWNLOAD CHECK")
print("========================================")

print(os.listdir(folder))

Downloading: MeitY_Annual_Report_2025_26.pdf
Status: 200
Size: 46695132 bytes
✓ Saved: ../01_Raw_Data/Semiconductor/Semiconductor_Investment/MeitY_Annual_Report_2025_26.pdf

Downloading: MeitY_Annual_Report_2024_25.pdf
Status: 200
Size: 17402013 bytes
✓ Saved: ../01_Raw_Data/Semiconductor/Semiconductor_Investment/MeitY_Annual_Report_2024_25.pdf

========================================
DOWNLOAD CHECK
========================================
['MeitY_Annual_Report_2025_26.pdf', 'Official_PDFs', 'MeitY_Annual_Report_2024_25.pdf']

In [82]:
import fitz
import os
import re

folder = "../01_Raw_Data/Semiconductor/Semiconductor_Investment"

pdf_files = [
    "MeitY_Annual_Report_2024_25.pdf",
    "MeitY_Annual_Report_2025_26.pdf"
]

for filename in pdf_files:

    path = os.path.join(folder, filename)

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)

    doc = fitz.open(path)

    print("Pages:", len(doc))

    # Search for semiconductor-related pages
    keywords = [
        "semiconductor",
        "India Semiconductor Mission",
        "ISM",
        "ATMP",
        "OSAT",
        "fabrication",
        "fab",
        "investment"
    ]

    matches = []

    for page_number, page in enumerate(doc):

        text = page.get_text("text")

        text_lower = text.lower()

        found = [
            keyword
            for keyword in keywords
            if keyword.lower() in text_lower
        ]

        if found:
            matches.append(
                (page_number + 1, found)
            )

    print("\nRelevant pages found:")

    for page, found in matches[:100]:
        print(
            f"Page {page}: {', '.join(found)}"
        )

ModuleNotFoundError: No module named 'fitz'

In [83]:
%pip install PyMuPDF

Collecting PyMuPDF
  Downloading pymupdf-1.28.2-cp310-abi3-macosx_11_0_arm64.whl.metadata (26 kB)
Downloading pymupdf-1.28.2-cp310-abi3-macosx_11_0_arm64.whl (23.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.9/23.9 MB 430.1 kB/s eta 0:00:00m eta 0:00:01[36m0:00:02
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.28.2
Note: you may need to restart the kernel to use updated packages.

In [84]:
import fitz

print("PyMuPDF installed successfully!")
print("Version:", fitz.version)

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
PyMuPDF installed successfully!
Version: ('1.28.2', '1.28.2', None)

In [85]:
import fitz
import os

folder = "../01_Raw_Data/Semiconductor/Semiconductor_Investment"

pdf_files = [
    "MeitY_Annual_Report_2024_25.pdf",
    "MeitY_Annual_Report_2025_26.pdf"
]

for filename in pdf_files:

    path = os.path.join(folder, filename)

    print("\n" + "=" * 80)
    print(filename)
    print("=" * 80)

    doc = fitz.open(path)

    print("Pages:", len(doc))

    keywords = [
        "semiconductor",
        "India Semiconductor Mission",
        "ISM",
        "ATMP",
        "OSAT",
        "fabrication",
        "fab",
        "investment"
    ]

    matches = []

    for page_number, page in enumerate(doc):

        text = page.get_text("text")
        text_lower = text.lower()

        found = [
            keyword
            for keyword in keywords
            if keyword.lower() in text_lower
        ]

        if found:
            matches.append(
                (page_number + 1, found)
            )

    print("\nRelevant pages found:")

    for page, found in matches:
        print(
            f"Page {page}: {', '.join(found)}"
        )

================================================================================
MeitY_Annual_Report_2024_25.pdf
================================================================================
Pages: 288

Relevant pages found:
Page 7: ISM, investment
Page 12: semiconductor
Page 13: semiconductor
Page 15: semiconductor, ISM
Page 16: semiconductor
Page 31: ISM
Page 32: ISM
Page 34: ISM
Page 44: semiconductor
Page 49: ISM
Page 53: investment
Page 60: ISM
Page 61: ISM
Page 68: semiconductor
Page 69: semiconductor, ATMP
Page 71: investment
Page 72: investment
Page 73: investment
Page 75: investment
Page 76: investment
Page 77: semiconductor, ATMP, OSAT, fabrication, fab, investment
Page 78: semiconductor, India Semiconductor Mission, ISM, ATMP, OSAT, fabrication, fab
Page 79: semiconductor, OSAT, fab, investment
Page 80: semiconductor
Page 81: semiconductor, investment
Page 82: semiconductor
Page 83: semiconductor, fab, investment
Page 84: semiconductor, ISM, investment
Page 86: fabrication, fab
Page 89: ISM
Page 90: semiconductor, investment
Page 91: semiconductor
Page 92: semiconductor, investment
Page 93: semiconductor, investment
Page 97: ISM
Page 102: semiconductor, fab
Page 104: fab
Page 107: fab
Page 108: ISM, investment
Page 113: ISM
Page 114: fabrication, fab
Page 116: fab
Page 119: fabrication, fab
Page 120: ISM
Page 123: semiconductor
Page 124: semiconductor
Page 129: semiconductor, fabrication, fab
Page 130: ISM, fab
Page 132: semiconductor
Page 133: semiconductor, India Semiconductor Mission, ISM, fabrication, fab
Page 134: investment
Page 137: fabrication, fab
Page 138: investment
Page 140: semiconductor, fabrication, fab
Page 141: fabrication, fab
Page 143: ISM
Page 144: ISM
Page 145: semiconductor
Page 149: ISM, fab
Page 151: ISM
Page 152: ISM
Page 160: ISM, investment
Page 163: ISM
Page 165: ISM
Page 166: ISM
Page 167: ISM
Page 168: ISM
Page 171: ISM
Page 173: semiconductor
Page 174: semiconductor
Page 175: ISM
Page 176: semiconductor, fabrication, fab
Page 178: semiconductor
Page 191: ISM
Page 194: ISM
Page 195: fab
Page 197: semiconductor, ISM
Page 198: ISM
Page 201: ISM
Page 205: ISM
Page 208: ISM
Page 213: ISM
Page 215: fabrication, fab
Page 216: semiconductor, fabrication, fab
Page 223: ISM
Page 226: ISM
Page 238: ISM
Page 240: ISM
Page 241: ISM
Page 242: ISM
Page 243: ISM
Page 247: ISM
Page 253: investment
Page 255: investment
Page 257: semiconductor, India Semiconductor Mission, ISM
Page 271: ISM
Page 273: semiconductor
Page 274: ISM
Page 275: semiconductor, fabrication, fab
Page 277: ISM
Page 278: ISM
Page 279: investment
Page 281: semiconductor, ATMP, OSAT, fab
Page 286: semiconductor

================================================================================
MeitY_Annual_Report_2025_26.pdf
================================================================================
Pages: 358

Relevant pages found:
Page 7: ISM
Page 8: semiconductor, investment
Page 10: semiconductor
Page 13: investment
Page 14: semiconductor
Page 17: ISM
Page 18: semiconductor, India Semiconductor Mission, ISM
Page 19: semiconductor, India Semiconductor Mission
Page 20: semiconductor, ISM
Page 36: ISM
Page 37: ISM
Page 38: ISM
Page 49: semiconductor, India Semiconductor Mission, ISM
Page 50: semiconductor, India Semiconductor Mission, fab
Page 54: semiconductor, fabrication, fab, investment
Page 55: ISM
Page 61: ISM
Page 65: ISM
Page 69: ISM
Page 72: ISM
Page 76: ISM
Page 78: ISM
Page 81: semiconductor
Page 83: semiconductor, investment
Page 85: semiconductor, ATMP, investment
Page 86: investment
Page 87: investment
Page 88: investment
Page 89: investment
Page 90: investment
Page 91: semiconductor, ATMP, fabrication, fab, investment
Page 92: semiconductor, India Semiconductor Mission, ISM, ATMP, OSAT, fabrication, fab, investment
Page 93: semiconductor, ATMP, OSAT, fab, investment
Page 94: semiconductor, investment
Page 95: semiconductor, ISM, fabrication, fab
Page 96: semiconductor, fab, investment
Page 97: semiconductor, fab, investment
Page 98: investment
Page 99: investment
Page 100: semiconductor, investment
Page 101: ISM
Page 103: fabrication, fab
Page 105: ISM
Page 106: semiconductor
Page 109: semiconductor
Page 110: semiconductor
Page 111: semiconductor
Page 113: ISM
Page 114: investment
Page 118: ISM
Page 120: fabrication, fab
Page 121: ISM
Page 125: ISM
Page 130: fab
Page 133: ISM
Page 136: fabrication, fab
Page 138: semiconductor
Page 140: fab
Page 146: semiconductor, fab
Page 147: semiconductor, fab
Page 149: semiconductor, fab
Page 151: ISM
Page 153: fabrication, fab
Page 154: fabrication, fab
Page 155: fabrication, fab
Page 156: fabrication, fab
Page 157: investment
Page 158: ISM, fabrication, fab
Page 162: semiconductor
Page 169: ISM
Page 170: ISM, fabrication, fab
Page 174: ISM
Page 180: ISM, investment
Page 181: ISM
Page 183: ISM
Page 185: ISM
Page 187: ISM
Page 188: ISM
Page 189: ISM
Page 190: ISM
Page 195: ISM
Page 197: semiconductor
Page 201: semiconductor, fabrication, fab
Page 202: semiconductor, fabrication, fab
Page 204: semiconductor
Page 206: semiconductor
Page 218: ISM
Page 220: ISM
Page 221: semiconductor
Page 222: semiconductor
Page 224: ISM
Page 226: investment
Page 231: ISM, investment
Page 235: ISM
Page 242: semiconductor, fabrication, fab
Page 247: ISM
Page 249: ISM
Page 255: ISM
Page 256: ISM
Page 257: ISM
Page 263: semiconductor, India Semiconductor Mission, ISM
Page 264: semiconductor, India Semiconductor Mission
Page 266: ISM
Page 269: ISM
Page 271: ISM
Page 278: ISM
Page 279: ISM
Page 280: ISM
Page 287: ISM
Page 288: ISM
Page 290: ISM
Page 291: semiconductor
Page 292: semiconductor, fabrication, fab
Page 294: semiconductor
Page 295: semiconductor
Page 297: ISM
Page 299: fabrication, fab
Page 300: ISM
Page 301: fabrication, fab
Page 302: semiconductor
Page 304: ISM
Page 306: semiconductor
Page 307: ISM
Page 308: semiconductor
Page 309: investment
Page 311: investment
Page 313: semiconductor, ISM
Page 316: semiconductor, ISM
Page 325: ISM
Page 328: ISM
Page 335: semiconductor
Page 336: semiconductor, fab
Page 337: semiconductor
Page 339: ISM
Page 340: semiconductor, fabrication, fab
Page 341: ISM
Page 344: ISM
Page 345: ISM, investment
Page 349: ISM, investment
Page 350: investment
Page 356: semiconductor

In [86]:
import fitz
import os

folder = "../01_Raw_Data/Semiconductor/Semiconductor_Investment"

pdf_files = [
    "MeitY_Annual_Report_2024_25.pdf",
    "MeitY_Annual_Report_2025_26.pdf"
]

# Pages most likely to contain project-level investment information
target_pages = {
    "MeitY_Annual_Report_2024_25.pdf": [
        77, 78, 79, 80, 81, 82, 83, 84,
        90, 91, 92, 93,
        102, 104, 107, 108,
        129, 130, 133, 134,
        137, 138, 140, 141,
        149, 160,
        275, 281
    ],

    "MeitY_Annual_Report_2025_26.pdf": [
        49, 50,
        54, 55,
        83, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
        103, 106, 109, 110, 111,
        120, 130,
        136, 140, 146, 147, 149,
        153, 154, 155, 156, 157, 158,
        170,
        201, 202,
        242,
        292, 299, 301,
        336, 337, 340,
        345, 349
    ]
}

output_file = os.path.join(
    folder,
    "Semiconductor_Investment_Relevant_Pages.txt"
)

with open(output_file, "w", encoding="utf-8") as out:

    for filename in pdf_files:

        path = os.path.join(folder, filename)

        doc = fitz.open(path)

        out.write("\n" + "=" * 100 + "\n")
        out.write(filename + "\n")
        out.write("=" * 100 + "\n")

        for page_number in target_pages[filename]:

            # PDF page numbers are zero-indexed
            page = doc[page_number - 1]

            text = page.get_text("text")

            out.write(
                f"\n\n{'-' * 80}\n"
            )
            out.write(
                f"PAGE {page_number}\n"
            )
            out.write(
                f"{'-' * 80}\n"
            )
            out.write(text)

        doc.close()

print("Extraction complete.")
print("Saved to:")
print(output_file)

Extraction complete.
Saved to:
../01_Raw_Data/Semiconductor/Semiconductor_Investment/Semiconductor_Investment_Relevant_Pages.txt

In [87]:
with open(
    "../01_Raw_Data/Semiconductor/Semiconductor_Investment/Semiconductor_Investment_Relevant_Pages.txt",
    "r",
    encoding="utf-8"
) as f:

    text = f.read()

print(text[:30000])

====================================================================================================
MeitY_Annual_Report_2024_25.pdf
====================================================================================================


--------------------------------------------------------------------------------
PAGE 77
--------------------------------------------------------------------------------
Make in India
REPORT
Ministry of Electronics & Information Technology
Annual
2024-2025
75
crore, total investment of ` 522.17 crore and total
employment of 3,879.
7.
Scheme for Promotion of Manufacturing of
Electronic Components and Semiconductors
(SPECS)

Notified vide Gazette Notification dated April 01,
2020, the Scheme provides financial incentive of
25% on capital expenditure for the identified list
of electronic goods that comprise downstream
value chain of electronic products, i.e., electronic
components, semiconductor/ display fabrication
units, ATMP units, specialized sub-assemblies
and capital goods for manufacture of aforesaid
goods. The scheme promotes development of
electronic components manufacturing ecosystem
in the country and deepening of electronics value
chain and is expected to bring new investments to
the tune of ` 20,000 crore with total employment
generation potential (Direct and Indirect) of
6,00,000. The scheme is closed to receive new
applications on 31.03.2024.

Progress under the scheme till December, 2024
as per latest Quarterly Progress Report

58 applications have been approved with total
proposed investment of Rs.22,081 crore. As per
the Quarterly Progress report submitted by the
applicant total investment done by the approved
applications is ` 9,481.56 crore. Total production
done by the approved applications is ` 25,571.59
crore. Total employment generated by the
approved applications is 39,092 persons.
8.
Modified Programme for Development of
Semiconductors and Display Manufacturing
Ecosystem in India

In furtherance of the vision of AatmaNirbhar Bharat
and positioning India as the global hub for ESDM,
a comprehensive program for the development
of semiconductors and display manufacturing
ecosystem in India was approved by Government of
India with an outlay of ` 76,000 crore (>$10 billion).
The Programme contained various schemes to
attract investments in the field of semiconductors
and display manufacturing. The following four
schemes have been notified under the Semicon
India Programme: -
8.1
Modified Scheme for setting up Semiconductor
Fabs in India

•
The scheme is aimed at attracting large
investments for setting up semiconductor
wafer fabrication facilities in the country to
strengthen the electronics manufacturing
ecosystem and help establish a trusted val-
ue chain.

•
The Scheme extends a fiscal support of 50%
of the project cost across the technologyn-
odes for setting up of Silicon based Semi-
conductor Fabs in India.

The fiscal support under the scheme shall be
provided on pari-passu basis for a period of six
years from the date of approval.
8.2
Modified Scheme for setting up of Display Fabs
in India

The scheme is aimed at attracting large investments
for manufacturing TFT LCD or AMOLED based
display panels in the country to strengthen
the electronics manufacturing ecosystem. The
Scheme extends fiscal support of 50% of Project
Cost for setting up of Display Fabs in India. The
fiscal support under the scheme shall be provided
on pari-passu basis for a period of six years from
the date of approval.
8.3
Modified Scheme for setting up of Compound
Semiconductors / Silicon Photonics / Sensors Fab/
Discrete Semiconductors Fab and Semiconductor
Assembly, Testing, Marking and Packaging
(ATMP) / OSAT facilities in India

The scheme extends a fiscal support of 50%
of the Capital Expenditure for setting up of
Compound Semiconductors / Silicon Photonics
(SiPh) / Sensors (including MEMS) Fab/ Discrete
Semiconductor Fab and Semiconductor ATMP /
OSAT facilities in India.
8.4
Design Linked Incentive (DLI) Scheme

•
‘Design Linked Incentive Scheme’ has been
notified on 21.12.2021. It shall offer financial


--------------------------------------------------------------------------------
PAGE 78
--------------------------------------------------------------------------------
REPORT
Ministry of Electronics & Information Technology
Make in India
Annual
2024-2025
76
incentives as well as design infrastructure
support across various stages of develop-
ment and deployment of semiconductor de-
sign for Integrated Circuits (ICs), Chipsets,
System on Chips (SoCs), Systems & IP
Cores and semiconductor linked design.

•
Under the “Product Design Linked Incen-
tive” component of the scheme, reimburse-
ment of up to 50% of the eligible expenditure
subject to a ceiling of Rs15 crore per appli-
cation will be provided as fiscal support to
the approved applicants. This shall include
expenditure relating to design, development,
testing, fabrication, validation, prototype de-
velopment, product development, filing of
Intellectual Property Rights etc. It will also
include manpower costs.

•
Under the “Deployment Linked Incentive”
component of the scheme, incentive of 6%
to 4% of net sales turnover over 5 years sub-
ject to a ceiling of ` 30 crore per application
will be provided to the approved applicants
whose semiconductor design for Integrated
Circuits (ICs), Chipsets, System on Chips
(SoCs), Systems & IP Cores and semicon-
ductor linked design are deployed in elec-
tronic products.

•
C-DAC is the Nodal Agency to implement
the scheme and establish the semiconduc-
tor design infrastructure such as EDA Tool
Grid, repository of IP Cores, hardware and
software licenses, patents and trademarks
etc.
8.5
India Semiconductor Mission (ISM)

•
India Semiconductor Mission (ISM) imple-
ments the schemes for Semiconductor and
Display Fabs, Compound Semiconductor
Fabs, Silicon Photonics Fabs, MEMS Sen-
sors Fabs, Discrete Semiconductor Fabs
and Semiconductor Packaging Units (ATMP
/ OSAT). It drives the long-term strategies for
the development of semiconductor and dis-
play ecosystem in the country.

•
The India Semiconductor Mission acts as
the nodal agency for efficient and smooth
implementation of the schemes for setting
up of Semiconductor, Display Fabs and
Compound
Semiconductors/ATMP/OSAT
facilities in India.
8.6
Semi-Conductor Laboratory (SCL)

The Union Cabinet has also approved that
Ministry of Electronics and Information Technology
will take requisite steps for modernization and
commercialization of Semi-conductor Laboratory
(SCL), Mohali. Semi-conductor Laboratory (SCL),
Mohali has been brought under the administrative
control of Ministry of Electronics and Information
Technology from Department of Space.

SCL is an Integrated Device Manufacturer
which undertakes activities pertaining to design,
development, fabrication, assembly & packaging,
testing and quality assurance of Silicon CMOS and
MEMS Devices for various applications. Presently,
SCL has two wafer fabrication lines, i.e., 200 mm
wafer line operating in 180nm CMOS technology
and 150 mm wafer line for MEMS technology. SCL
predominantly caters to low volume requirements
for various applications.

Boston Consulting Group (BCG) has been
engaged for providing consultancy services for
Modernization of Semi-Conductor Laboratory,
Mohali.
8.7
Projects approved under the Programme:

The Government has approved following projects:

i.
Micron Technology Inc.’s proposal for set-
ting up an ATMP facility in India with an in-
vestment of ` 22,516 crore was approved
in June 2023. Micron’s facility in India will
enable assembly and test manufacturing
for both DRAM and NAND products and ad-
dress demand from domestic and interna-
tional markets with a production capacity of
around 40 million per week.

ii.
Tata Electronics Private Limited (TEPL)’s
proposal for setting up a Semiconductor Fab


--------------------------------------------------------------------------------
PAGE 79
--------------------------------------------------------------------------------
Make in India
REPORT
Ministry of Electronics & Information Technology
Annual
2024-2025
77
facility in India with an investment of ` 91,526
crore was approved in February 2024. The
fab facility will be set up in technology part-
nership with PSMC, Taiwan. PSMC is an
established semiconductor company hav-
ing 6 semiconductor foundries in Taiwan.
The production capacity of the project would
be around 50,000 wafer starts per month
(WSPM).

iii.
Tata Electronics Private Limited (TEPL)’s
proposal for setting up of OSAT facility in
India with an investment of ` 27,120 crores
was approved in February 2024. The facility
will use indigenous semiconductor packag-
ing technologies with a production capacity
of 48 million per day.

iv.
CG Power and Industrial Solutions Limited’s
proposal for setting up OSAT facility in India
with an investment of ` 7,584 crore was also
approved in February 2024. The facility will
be set up as joint venture partnership with
Renesas Electronics America Inc., USA,
and STARS Microelectronic, Thailand. The
technology would be provided for this facil-
ity by Renesas Electronics Corporation, Ja-
pan and STARS Microelectronic, Thailand.
The production capacity would be around
15.07Million Units per day.

v.
Kaynes Technology India Limited (KTIL)
proposal of for setting up of Outsourced
Semiconductor Assembly and Test (OSAT)
facility at Sanand, Gujarat for Wire bond In-
terconnect, Substrate Based Packages was
approved in September, 2024. The Technol-
ogy would be provided by ISO Technology
Sdn. Bhd. and Aptos Technology Inc. This
facility will be setup with an investment of `
3,307 crore. The facility will have the capac-
ity to produce more than 6.33 Million chips
per day.

vi.
51 start-ups and MSMEs companies have
been approved for design infrastructure sup-
port under the DLI Scheme made available
by ChipIN Centre at C-DAC Bengaluru. Out
of these, 17 companies have also been ap-
proved for financial support for developing
semiconductor chip/ SoCs for applications in
sectors such as automotive, mobility, com-
puting, communications etc namely - DV2JS
Innovation LLP­, Vervesemi Microelectron-
ics, Fermionic Design, Morphing Machines,
Calligo Technologies, Sensesemi Technolo-
gies, Saankhya Labs, Aryabhata Circuits and
Research Labs, BigEndian Semiconductors,
C2i Semiconductors, Aheesa Digital Innova-
tions, Mindgrove Technologies, InCore Sem-
iconductors, Netrasemi, Green PMU Semi,
WiSig Networks, MosChip Technologies.
8.8
Employment: The semiconductor manufacturing
facilities will generate direct employment of about
25 thousand advanced technology jobs and about
60 thousand indirect jobs.
3.4
Investment Promotion to Attract Investment in
ESDM Sector
3.4.1	 Promotion of PLI, SPECS, EMC 2.0 and
Schemes for Development of Semiconductors and
Display Manufacturing Ecosystem in India
To stimulate more investment in the Electronics
System Design and Manufacturing (ESDM) sector in
India, several investment promotion initiatives have
been launched. In addition, these initiatives are aimed
at creating a world-class semiconductor and display
manufacturing ecosystem, these efforts also include the
introduction of significant schemes like the PLI Scheme
2.0 for IT Hardware. Further, thorough outreach plan that
includes online meetings with possible investors and in-
depth presentations outlining the advantages of these
programs were conducted. To address the concerns and
establish a clear investment path, high-level discussions
were arranged, including direct interactions between
company representatives and senior officials from MeitY.
As a result of these promotional efforts, India is now
seen as a potential ESDM destination and have greatly
increased awareness and interest in the international
industry.


--------------------------------------------------------------------------------
PAGE 80
--------------------------------------------------------------------------------
REPORT
Ministry of Electronics & Information Technology
Make in India
Annual
2024-2025
78
3.4.2	 Advocacy and Outreach Programmes
A stakeholder Meeting on “Empowering Industries:
Unlocking Tomorrow’s Potential with PLI Schemes”
was held at Bharat Mandapam in February 2024 in the
presence of Hon’ble Commerce and Industries Minister
(CIM). This event highlighted Electronics PLI Scheme’s
insights and achievements. The gathering shed light on
the insights and accomplishments of the Electronics PLI
Scheme, showcasing its significant contributions and
promising prospects for the future.
The 4th Electronics Supply Chain Summit was, held in
Noida in collaboration with ELCINA. The B2B forum
had participation of over 200 delegates from 100+
companies. This business development program aimed
to strengthen local manufacturing of Components, EMS,
Semiconductor Products & Modules,  and product
segments including  Mobiles &  Accessories, Consumer
Electronics, Lighting Equipment, Auto Electronics/
EVs, Security Products, IT products among others.
ICEA organised the conference on “Sub-Assemblies
& Components
The Next Phase of Growth in India’s Electronics
Manufacturing” in New Delhi to chart out the roadmap
for increasing Domestic Value Addition (DVA) in Indian
Electronics.
Semicon India Conference 2024 (11-13 September
2024)
SEMICON India 2024, held from September 11-13 at the
India Exposition Mart Ltd. (IEML) in Greater Noida, Delhi
NCR, was a pivotal event spotlighting the rapid growth of
India’s semiconductor ecosystem and emerging industry
trends. Inaugurated by Prime Minister Narendra Modi,
it brought together global leaders, industry experts,
academia, and government officials to explore cutting-
edge innovations in areas such as smart manufacturing,
supply chain optimization, sustainability, and workforce
development.


--------------------------------------------------------------------------------
PAGE 81
--------------------------------------------------------------------------------
Make in India
REPORT
Ministry of Electronics & Information Technology
Annual
2024-2025
79
With over 263 exhibitors and 45,000 in-person
attendees, it established itself as one of Southeast
Asia’s premier platforms for showcasing advancements
in semiconductors and electronics. Representatives
from Applied Materials, Cadence, CG Power, KLA, Lam
Research, Micron, NXP, Renesas, TATA Electronics,
Tokyo Electron, SiLT, KAS Technologies, Western
Digital, DISCO, Merck, Jacobs, and many other industry
leaders attended the event.
3.4.3	 Outreach Activities for Shifting Global Value
Chain
As part of MeitY’s ongoing outreach efforts, several
interactions were organized with industry stakeholders
to raise awareness about the PLI Scheme 2.0 for IT
Hardware. These engagements aimed to encourage
companies to localize their manufacturing processes
in alignment with the newly introduced scheme, with a
focus on boosting domestic production and creating
employment opportunities within the IT hardware
sector. Meetings with the applicants of PLI Scheme
(IT Hardware & LSEM) to discuss investment plans,
progress and challenges were conducted time to time by
senior officials of MeitY
International Collaborations and Business Delegation
Visits
A Taiwan Electrical and Electronic Manufacturers’
Association (TEEMA) delegation called-on Secretary on
8th August, 2024. The discussions during the meeting
focused on the way forward for India-Taiwan collaboration,
fostering innovation and support technological growth in
the electronics sector.
MeitY officials held discussion with delegation from
Foxconn led by Dr. Young Liu, Chairman, Foxconn about
Foxconn’s plan for development of electronics ecosystem
including Semiconductors in India on 14th August, 2024.
•
3rd India-Taiwan CEOs Roundtable Meeting & 2024
India-Taiwan Industrial Collaboration Summit was
held along with FICCI in partnership with TAITRA,
TEEMA & CNFI at New Delhi. Joint Secretary
(Electronics) Shri Sushil Pal addressed the session
wherein he highlighted that the global winds of
trade dynamics present an opportune window for
leapfrogging India-Taiwan industrial partnership
to the next level.


--------------------------------------------------------------------------------
PAGE 82
--------------------------------------------------------------------------------
REPORT
Ministry of Electronics & Information Technology
Make in India
Annual
2024-2025
80
•
Indo-US Task Force for Electronics – 2nd
Roundtable of Indo-US Task force was held on 4th
October 2024 in association with ICEA comprising
Industry leaders in the sector to boost and elevate
electronics trade between India and USA to approx.
$100 Bn within a decade from the current $13 Bn
figure.
3.4.4	 National Level Events & Facilitations
Task Force on Making India an Electronics &
Semiconductor Product Nation
Ministry of Electronics and Information Technology,
Government of India constituted a Task Force under the
chairmanship of Prof. Ajay K. Sood, Principal Scientific
Advisor to the Govt. of India to achieve the objectives
of making India a product developer and manufacturer
nation. The Task Force, consisting of members from both
Industry and Government, had detailed deliberations
and identified following potential areas where strategic
initiatives are required to make India an Electronics &
Semiconductor Product Nation:
(i)
identification of products (with B2B and B2C
perspectives)
(ii)
Components and sub-systems other than chips
(iii)
Chip requirement for India (Chips for All)
(iv)
Policy, Regulations, Taxation and Tariffs, EoDB,
Competitiveness
Numerous other Industry consultation sessions and
one-to one meeting with ESDM companies were also
conducted to understand the issues being faced by them.


--------------------------------------------------------------------------------
PAGE 83
--------------------------------------------------------------------------------
Make in India
REPORT
Ministry of Electronics & Information Technology
Annual
2024-2025
81
3.4.5	 International Events & Facilitations
•
Outreach
engagements
held
with
Indian
Consulates/
Embassies/
High
Commissions
in other countries for promoting the schemes
launched by MeitY.
•
MeitY participated in various Investment Promotion
Roadshows organized by other Ministries like
DPIIT to Taiwan, Korea, Japan, Singapore etc.
•
MeitY also contributed to international engagements
like G20, India-EU TTC, India-Taiwan Cooperation
Forum,
World
Economic
Forum,
Industrial
Collaboration Working Group (ICWG) between
India and Taiwan (ICWG), India-Japan Industrial
Competitiveness Partnership (IJICP)
3.4.6	 Social Media Participation
To reach out to all ESDM stakeholders, all the events,
webinars were widely promoted on X (erstwhile Twitter)
through the official handle (Electronics Gol) of the IPHW
Division of MeitY.
3.4.6.1 International Collaborations in the field of
Semiconductors
MoU with Singapore: Government of India has recently
signed an MoU with Singapore to establish an “India-
Singapore Semiconductor Ecosystem Policy Dialogue”.
The Policy Dialogue will be used as a platform to:
•
Discuss semiconductor supply chain related
issues;
•
Exchange best practices to leverage opportunities
for growth in the global semiconductor industry;
•
Explore areas for mutually beneficial semiconductor
R&D collaboration;
•
Encourage collaboration between Singapore-
based
and
India-based
companies
towards
mutually beneficial semiconductor related business
opportunities and partnerships;
•
Consider initiatives to enhance semiconductor
supply chain resilience, based on areas of
mutual strength such as fabs, packaging, design,
equipment,
specialty
chemicals
and
gases,
semiconductor grade materials;
•
Promote
Industrial
Parks
and
workforce
development for mutual benefit.
Building on the Semiconductor MoU, the first India-
Singapore Semiconductor Ecosystem Policy Dialogue,
co-chaired by Secretary, MeitY, Shri S Krishnan &

In [88]:
from pathlib import Path

BASE = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML"
)

CAPACITY = BASE / "01_Raw_Data" / "Semiconductor" / "Semiconductor_Capacity"

(CAPACITY / "Official_PDFs").mkdir(parents=True, exist_ok=True)
(CAPACITY / "Source_Index").mkdir(parents=True, exist_ok=True)

print("Capacity folder:", CAPACITY)
print("Created:")
print("✓ Official_PDFs")
print("✓ Source_Index")

Capacity folder: /Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/Semiconductor/Semiconductor_Capacity
Created:
✓ Official_PDFs
✓ Source_Index

In [89]:
!pip install requests beautifulsoup4 pandas openpyxl lxml

Requirement already satisfied: requests in /opt/miniconda3/lib/python3.13/site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in /opt/miniconda3/lib/python3.13/site-packages (4.15.0)
Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (3.0.5)
Requirement already satisfied: openpyxl in /opt/miniconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: lxml in /opt/miniconda3/lib/python3.13/site-packages (6.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/lib/python3.13/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/lib/python3.13/site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/miniconda3/lib/python3.13/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /opt/miniconda3/lib/python3.13/site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in /opt/miniconda3/lib/python3.13/site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/miniconda3/lib/python3.13/site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /opt/miniconda3/lib/python3.13/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [90]:
import requests
import pandas as pd
import re
import time
from bs4 import BeautifulSoup
from pathlib import Path
from urllib.parse import quote, urljoin

# ============================================================
# CONFIGURATION
# ============================================================

BASE = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML"
)

CAPACITY = BASE / "01_Raw_Data" / "Semiconductor" / "Semiconductor_Capacity"
PDF_DIR = CAPACITY / "Official_PDFs"
INDEX_DIR = CAPACITY / "Source_Index"

PDF_DIR.mkdir(parents=True, exist_ok=True)
INDEX_DIR.mkdir(parents=True, exist_ok=True)

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/139.0 Safari/537.36"
    )
}

# ============================================================
# SEARCH QUERIES
# ============================================================

queries = [
    "semiconductor projects approved India capacity",
    "semiconductor fabrication capacity India ISM",
    "semiconductor fab investment capacity India",
    "ATMP OSAT capacity India semiconductor",
    "semiconductor packaging capacity India ISM",
    "semiconductor projects investment capacity MeitY",
    "India Semiconductor Mission approved projects capacity",
    "semiconductor manufacturing units capacity India",
    "Silicon Carbide semiconductor capacity India ISM",
    "semiconductor projects 2025 India capacity",
    "semiconductor projects 2026 India capacity"
]

# ============================================================
# OFFICIAL DOMAINS ONLY
# ============================================================

domains = [
    "pib.gov.in",
    "meity.gov.in",
    "ism.gov.in"
]

# ============================================================
# SEARCH USING BING HTML
# ============================================================

def search_bing(query, max_results=10):

    url = "https://www.bing.com/search?q=" + quote(query)

    try:
        response = requests.get(
            url,
            headers=HEADERS,
            timeout=30
        )

        response.raise_for_status()

        soup = BeautifulSoup(response.text, "html.parser")

        results = []

        for item in soup.select("li.b_algo")[:max_results]:

            a = item.select_one("h2 a")

            if not a:
                continue

            title = a.get_text(" ", strip=True)
            link = a.get("href")

            snippet = ""

            p = item.select_one(".b_caption p")

            if p:
                snippet = p.get_text(" ", strip=True)

            if link:
                results.append({
                    "query": query,
                    "title": title,
                    "url": link,
                    "snippet": snippet
                })

        return results

    except Exception as e:

        print("Search failed:", query)
        print(e)

        return []


# ============================================================
# COLLECT RESULTS
# ============================================================

all_results = []

for query in queries:

    print("\nSearching:", query)

    results = search_bing(query)

    for result in results:

        url = result["url"].lower()

        if any(domain in url for domain in domains):

            all_results.append(result)

    time.sleep(1)


# ============================================================
# REMOVE DUPLICATES
# ============================================================

df = pd.DataFrame(all_results)

if len(df) > 0:

    df = df.drop_duplicates(subset=["url"])

    df = df.reset_index(drop=True)

else:

    df = pd.DataFrame(
        columns=[
            "query",
            "title",
            "url",
            "snippet"
        ]
    )


print("\n" + "=" * 70)
print("OFFICIAL SEMICONDUCTOR CAPACITY SOURCES")
print("=" * 70)

print("Sources found:", len(df))

display(df)

Searching: semiconductor projects approved India capacity

Searching: semiconductor fabrication capacity India ISM

Searching: semiconductor fab investment capacity India

Searching: ATMP OSAT capacity India semiconductor

Searching: semiconductor packaging capacity India ISM

Searching: semiconductor projects investment capacity MeitY

Searching: India Semiconductor Mission approved projects capacity

Searching: semiconductor manufacturing units capacity India

Searching: Silicon Carbide semiconductor capacity India ISM

Searching: semiconductor projects 2025 India capacity

Searching: semiconductor projects 2026 India capacity

======================================================================
OFFICIAL SEMICONDUCTOR CAPACITY SOURCES
======================================================================
Sources found: 0

Empty DataFrame
Columns: [query, title, url, snippet]
Index: []

In [91]:
index_file = INDEX_DIR / "Semiconductor_Capacity_Source_Index.csv"

df.to_csv(
    index_file,
    index=False,
    encoding="utf-8-sig"
)

print("Saved:")
print(index_file)

Saved:
/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/Semiconductor/Semiconductor_Capacity/Source_Index/Semiconductor_Capacity_Source_Index.csv

In [92]:
def download_file(url, output_path):

    try:

        r = requests.get(
            url,
            headers=HEADERS,
            timeout=60
        )

        r.raise_for_status()

        content_type = r.headers.get(
            "Content-Type",
            ""
        ).lower()

        data = r.content

        # Accept PDFs even if server sends incorrect MIME type
        if data[:4] == b"%PDF" or "pdf" in content_type:

            output_path.write_bytes(data)

            return True, len(data), content_type

        return False, len(data), content_type

    except Exception as e:

        return False, 0, str(e)


downloaded = []
failed = []

for i, row in df.iterrows():

    url = row["url"]

    title = row["title"]

    # Clean filename
    filename = re.sub(
        r'[\\/*?:"<>|]',
        "",
        title
    )

    filename = filename[:150]

    if not filename.lower().endswith(".pdf"):
        filename += ".pdf"

    output = PDF_DIR / filename

    print("\nDownloading:")
    print(title)
    print(url)

    success, size, content_type = download_file(
        url,
        output
    )

    if success:

        print(
            f"✓ Saved ({size:,} bytes)"
        )

        downloaded.append({
            "title": title,
            "url": url,
            "file": str(output),
            "size_bytes": size
        })

    else:

        print(
            "✗ Not a direct PDF:",
            content_type
        )

        failed.append({
            "title": title,
            "url": url,
            "reason": content_type
        })

    time.sleep(1)


print("\n" + "=" * 70)
print("DOWNLOAD COMPLETE")
print("=" * 70)

print("Downloaded:", len(downloaded))
print("Failed:", len(failed))

======================================================================
DOWNLOAD COMPLETE
======================================================================
Downloaded: 0
Failed: 0

In [93]:
from pathlib import Path

capacity_folder = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML/"
    "01_Raw_Data/Semiconductor/Semiconductor_Capacity"
)

print("=" * 70)
print("SEMICONDUCTOR CAPACITY FILES")
print("=" * 70)

for p in capacity_folder.rglob("*"):
    if p.is_file():
        print(p.relative_to(capacity_folder))

======================================================================
SEMICONDUCTOR CAPACITY FILES
======================================================================
.DS_Store
Source_Index/Semiconductor_Capacity_Source_Index.csv

In [94]:
!pip install pymupdf pandas openpyxl

Collecting pymupdf
  Using cached pymupdf-1.28.2-cp310-abi3-macosx_11_0_arm64.whl.metadata (26 kB)
Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (3.0.5)
Requirement already satisfied: openpyxl in /opt/miniconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /opt/miniconda3/lib/python3.13/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pymupdf-1.28.2-cp310-abi3-macosx_11_0_arm64.whl (23.9 MB)
Installing collected packages: pymupdf
Successfully installed pymupdf-1.28.2

In [95]:
import fitz
import pandas as pd
import re
from pathlib import Path

In [96]:
BASE = Path(
    "/Users/shashankyadav/Library/CloudStorage/"
    "OneDrive-WOXSENUNIVERSITY/"
    "Semiconductor_Credit_Risk_ML"
)

SEMICON = BASE / "01_Raw_Data" / "Semiconductor"

INVESTMENT = SEMICON / "Semiconductor_Investment"

CAPACITY = SEMICON / "Semiconductor_Capacity"

CAPACITY.mkdir(parents=True, exist_ok=True)

print("Investment folder:", INVESTMENT)
print("Capacity folder:", CAPACITY)

Investment folder: /Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/Semiconductor/Semiconductor_Investment
Capacity folder: /Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/Semiconductor/Semiconductor_Capacity

In [97]:
reports = list(INVESTMENT.glob("MeitY_Annual_Report_*.pdf"))

print("Reports found:", len(reports))

for r in reports:
    print("✓", r.name)

Reports found: 2
✓ MeitY_Annual_Report_2025_26.pdf
✓ MeitY_Annual_Report_2024_25.pdf

In [98]:
KEYWORDS = [
    "semiconductor",
    "India Semiconductor Mission",
    "ISM",
    "semiconductor fab",
    "fabrication",
    "ATMP",
    "OSAT",
    "assembly",
    "testing",
    "packaging",
    "wafer",
    "chip",
    "integrated circuit"
]

page_records = []

for pdf_path in reports:

    print("\n" + "=" * 80)
    print(pdf_path.name)
    print("=" * 80)

    doc = fitz.open(pdf_path)

    for page_number in range(len(doc)):

        text = doc[page_number].get_text("text")

        text_lower = text.lower()

        matched = []

        for keyword in KEYWORDS:

            if keyword.lower() in text_lower:
                matched.append(keyword)

        if matched:

            page_records.append({
                "document": pdf_path.name,
                "page": page_number + 1,
                "keywords": ", ".join(sorted(set(matched))),
                "text": text
            })

    doc.close()

pages_df = pd.DataFrame(page_records)

print("\n" + "=" * 80)
print("RELEVANT PAGES")
print("=" * 80)

print("Pages found:", len(pages_df))

display(
    pages_df[
        ["document", "page", "keywords"]
    ].head(50)
)

================================================================================
MeitY_Annual_Report_2025_26.pdf
================================================================================

================================================================================
MeitY_Annual_Report_2024_25.pdf
================================================================================

================================================================================
RELEVANT PAGES
================================================================================
Pages found: 329

,document,page,keywords
0,MeitY_Annual_Report_2025_26.pdf,7,ISM
1,MeitY_Annual_Report_2025_26.pdf,8,semiconductor
2,MeitY_Annual_Report_2025_26.pdf,9,"chip, integrated circuit"
3,MeitY_Annual_Report_2025_26.pdf,10,"chip, semiconductor"
4,MeitY_Annual_Report_2025_26.pdf,11,testing
5,MeitY_Annual_Report_2025_26.pdf,14,"chip, semiconductor"
6,MeitY_Annual_Report_2025_26.pdf,15,chip
7,MeitY_Annual_Report_2025_26.pdf,17,ISM
8,MeitY_Annual_Report_2025_26.pdf,18,"ISM, India Semiconductor Mission, semiconducto..."
9,MeitY_Annual_Report_2025_26.pdf,19,"India Semiconductor Mission, semiconductor"
10,MeitY_Annual_Report_2025_26.pdf,20,"ISM, semiconductor"
11,MeitY_Annual_Report_2025_26.pdf,26,testing
12,MeitY_Annual_Report_2025_26.pdf,36,ISM
13,MeitY_Annual_Report_2025_26.pdf,37,"ISM, testing"
14,MeitY_Annual_Report_2025_26.pdf,38,"ISM, testing"
15,MeitY_Annual_Report_2025_26.pdf,40,testing
16,MeitY_Annual_Report_2025_26.pdf,49,"ISM, India Semiconductor Mission, semiconductor"
17,MeitY_Annual_Report_2025_26.pdf,50,"India Semiconductor Mission, semiconductor"
18,MeitY_Annual_Report_2025_26.pdf,54,"assembly, fabrication, semiconductor, testing"
19,MeitY_Annual_Report_2025_26.pdf,55,ISM
20,MeitY_Annual_Report_2025_26.pdf,60,testing
21,MeitY_Annual_Report_2025_26.pdf,61,ISM
22,MeitY_Annual_Report_2025_26.pdf,63,testing
23,MeitY_Annual_Report_2025_26.pdf,65,ISM
24,MeitY_Annual_Report_2025_26.pdf,68,testing
25,MeitY_Annual_Report_2025_26.pdf,69,ISM
26,MeitY_Annual_Report_2025_26.pdf,72,ISM
27,MeitY_Annual_Report_2025_26.pdf,76,ISM
28,MeitY_Annual_Report_2025_26.pdf,78,ISM
29,MeitY_Annual_Report_2025_26.pdf,80,chip
30,MeitY_Annual_Report_2025_26.pdf,81,"chip, semiconductor"
31,MeitY_Annual_Report_2025_26.pdf,83,semiconductor
32,MeitY_Annual_Report_2025_26.pdf,85,"ATMP, assembly, semiconductor"
33,MeitY_Annual_Report_2025_26.pdf,86,assembly
34,MeitY_Annual_Report_2025_26.pdf,87,"assembly, chip, packaging, testing"
35,MeitY_Annual_Report_2025_26.pdf,88,testing
36,MeitY_Annual_Report_2025_26.pdf,91,"ATMP, fabrication, semiconductor, semiconducto..."
37,MeitY_Annual_Report_2025_26.pdf,92,"ATMP, ISM, India Semiconductor Mission, OSAT, ..."
38,MeitY_Annual_Report_2025_26.pdf,93,"ATMP, OSAT, assembly, chip, packaging, semicon..."
39,MeitY_Annual_Report_2025_26.pdf,94,"chip, semiconductor"
40,MeitY_Annual_Report_2025_26.pdf,95,"ISM, assembly, fabrication, packaging, semicon..."
41,MeitY_Annual_Report_2025_26.pdf,96,"chip, semiconductor"
42,MeitY_Annual_Report_2025_26.pdf,97,"chip, packaging, semiconductor"
43,MeitY_Annual_Report_2025_26.pdf,99,assembly
44,MeitY_Annual_Report_2025_26.pdf,100,semiconductor
45,MeitY_Annual_Report_2025_26.pdf,101,"ISM, testing"
46,MeitY_Annual_Report_2025_26.pdf,103,"fabrication, packaging"
47,MeitY_Annual_Report_2025_26.pdf,105,ISM
48,MeitY_Annual_Report_2025_26.pdf,106,semiconductor
49,MeitY_Annual_Report_2025_26.pdf,109,semiconductor

In [99]:
extracted_pages = CAPACITY / "Extracted_Relevant_Pages"

extracted_pages.mkdir(
    parents=True,
    exist_ok=True
)

for document in pages_df["document"].unique():

    doc_pages = pages_df[
        pages_df["document"] == document
    ]

    output_file = (
        extracted_pages /
        document.replace(".pdf", "_relevant_pages.txt")
    )

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as f:

        for _, row in doc_pages.iterrows():

            f.write(
                "\n" +
                "=" * 100 +
                "\n"
            )

            f.write(
                f"PAGE {row['page']}\n"
            )

            f.write(
                f"KEYWORDS: {row['keywords']}\n"
            )

            f.write(
                "=" * 100 +
                "\n\n"
            )

            f.write(row["text"])

            f.write("\n\n")

    print("✓ Saved:", output_file.name)

✓ Saved: MeitY_Annual_Report_2025_26_relevant_pages.txt
✓ Saved: MeitY_Annual_Report_2024_25_relevant_pages.txt

In [100]:
PROJECT_TERMS = [
    "Tata Electronics",
    "Tata Semiconductor",
    "CG Power",
    "Micron",
    "Kaynes",
    "SiCSem",
    "HCL",
    "Foxconn",
    "Renesas",
    "Powerchip",
    "ISM",
    "ATMP",
    "OSAT",
    "fab",
    "fabrication"
]

project_pages = []

for _, row in pages_df.iterrows():

    text = row["text"]

    matches = []

    for term in PROJECT_TERMS:

        if term.lower() in text.lower():
            matches.append(term)

    if matches:

        project_pages.append({
            "document": row["document"],
            "page": row["page"],
            "matched_terms": ", ".join(matches),
            "text": text
        })

project_df = pd.DataFrame(project_pages)

print(
    "Project-related pages:",
    len(project_df)
)

display(
    project_df[
        [
            "document",
            "page",
            "matched_terms"
        ]
    ]
)

Project-related pages: 175

                            document  page     matched_terms
0    MeitY_Annual_Report_2025_26.pdf     7               ISM
1    MeitY_Annual_Report_2025_26.pdf    17               ISM
2    MeitY_Annual_Report_2025_26.pdf    18               ISM
3    MeitY_Annual_Report_2025_26.pdf    20               ISM
4    MeitY_Annual_Report_2025_26.pdf    36               ISM
..                               ...   ...               ...
170  MeitY_Annual_Report_2024_25.pdf   274               ISM
171  MeitY_Annual_Report_2024_25.pdf   275  fab, fabrication
172  MeitY_Annual_Report_2024_25.pdf   277               ISM
173  MeitY_Annual_Report_2024_25.pdf   278               ISM
174  MeitY_Annual_Report_2024_25.pdf   281   ATMP, OSAT, fab

[175 rows x 3 columns]

In [ ]:
page_index = (
    CAPACITY /
    "Source_Index" /
    "MeitY_Semiconductor_Capacity_Page_Index.csv"
)

pages_df[
    [
        "document",
        "page",
        "keywords"
    ]
].to_csv(
    page_index,
    index=False,
    encoding="utf-8-sig"
)

print("✓ Saved:")
print(page_index)

In [101]:
capacity_columns = [
    "project_name",
    "company",
    "project_type",
    "location",
    "investment_crore",
    "government_support_crore",
    "capacity",
    "capacity_unit",
    "technology",
    "approval_date",
    "status",
    "expected_operation",
    "employment",
    "source_document",
    "source_page",
    "source_url"
]

capacity_master = pd.DataFrame(
    columns=capacity_columns
)

capacity_file = (
    CAPACITY /
    "Semiconductor_Capacity_Master.csv"
)

capacity_master.to_csv(
    capacity_file,
    index=False,
    encoding="utf-8-sig"
)

print("✓ Created:")
print(capacity_file)

✓ Created:
/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/01_Raw_Data/Semiconductor/Semiconductor_Capacity/Semiconductor_Capacity_Master.csv

In [ ]:
# ============================================================
# PRINT PROJECT-RELATED MEITY PAGES
# ============================================================

for _, row in project_df.iterrows():

    print("\n" + "=" * 100)
    print(
        f"{row['document']}  |  PAGE {row['page']}"
    )
    print(
        f"MATCHED TERMS: {row['matched_terms']}"
    )
    print("=" * 100)

    # Clean excessive blank lines
    text = re.sub(
        r'\n{3,}',
        '\n\n',
        row["text"]
    )

    print(text[:12000])