In [1]:
import pandas as pd
import os

print(os.getcwd())

/Users/shashankyadav/Library/CloudStorage/OneDrive-WOXSENUNIVERSITY/Semiconductor_Credit_Risk_ML/03_Notebooks
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [2]:
iip_path = "../01_Raw_Data/Industrial_Production/IIP_Dashboard Data_Jun2026-28.07.2026.xlsx"

xls = pd.ExcelFile(iip_path)

print(xls.sheet_names)

['UBC-Monthly', 'Sectoral-Monthly', 'UBC-Annual', 'Sectoral-Annual', 'Sectoral Weights']

In [3]:
import os

print(os.listdir("../01_Raw_Data/Industrial_Production"))

['.DS_Store', 'IIP_Dashboard Data_Jun2026-28.07.2026.xlsx']

In [4]:
iip = pd.read_excel(
    iip_path,
    sheet_name=0,
    header=None
)

print("Shape:", iip.shape)
display(iip.head(15))

Shape: (7, 41)

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,Use-based category,Weight,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,...,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00,2026-06-01 00:00:00
1,Primary goods,31.136,1.3,5.8,5.4,-0.9,1.3,-1.9,5,0.8,...,6.6,0.4,1.1,2.4,1.9,0,0.2,0.8,2.7,4.9
2,Capital goods,8.082,-4.7,1.6,8.8,4.1,12.8,16.3,7.6,1.2,...,13.2,5.4,16.6,12.9,12.4,16.5,8.5,12,15.5,14.2
3,Intermediate goods,22.416,0.6,5.5,1.7,4.8,8.2,5.6,6.3,1.2,...,6.4,1.2,8.2,7.7,5.6,4.7,6,10.3,5.8,9.3
4,Infrastructure/ construction goods,10.908,5.7,7.9,7.4,7.3,11.8,9.1,10.3,3.2,...,9.8,5.1,12,12.3,12.9,10.1,5.2,6,6.6,7.5
5,Consumer durables,11.311,-4,-1.2,-1.2,2.4,7.9,8.3,12.6,-3.3,...,4.6,-6,13,7.4,-0.2,4.2,2.4,5.6,8,7.7
6,Consumer non-durables,16.147,0.6,8.4,6.9,5,8.7,6.4,3.3,2.9,...,-0.5,-9.4,3.9,5.9,-1.2,1.6,-0.6,0.2,-0.4,4.9

In [5]:
display(iip.tail(10))

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,Use-based category,Weight,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,...,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00,2026-06-01 00:00:00
1,Primary goods,31.136,1.3,5.8,5.4,-0.9,1.3,-1.9,5,0.8,...,6.6,0.4,1.1,2.4,1.9,0,0.2,0.8,2.7,4.9
2,Capital goods,8.082,-4.7,1.6,8.8,4.1,12.8,16.3,7.6,1.2,...,13.2,5.4,16.6,12.9,12.4,16.5,8.5,12,15.5,14.2
3,Intermediate goods,22.416,0.6,5.5,1.7,4.8,8.2,5.6,6.3,1.2,...,6.4,1.2,8.2,7.7,5.6,4.7,6,10.3,5.8,9.3
4,Infrastructure/ construction goods,10.908,5.7,7.9,7.4,7.3,11.8,9.1,10.3,3.2,...,9.8,5.1,12,12.3,12.9,10.1,5.2,6,6.6,7.5
5,Consumer durables,11.311,-4,-1.2,-1.2,2.4,7.9,8.3,12.6,-3.3,...,4.6,-6,13,7.4,-0.2,4.2,2.4,5.6,8,7.7
6,Consumer non-durables,16.147,0.6,8.4,6.9,5,8.7,6.4,3.3,2.9,...,-0.5,-9.4,3.9,5.9,-1.2,1.6,-0.6,0.2,-0.4,4.9

In [6]:
print(iip.dtypes)

0     object
1     object
2     object
3     object
4     object
5     object
6     object
7     object
8     object
9     object
10    object
11    object
12    object
13    object
14    object
15    object
16    object
17    object
18    object
19    object
20    object
21    object
22    object
23    object
24    object
25    object
26    object
27    object
28    object
29    object
30    object
31    object
32    object
33    object
34    object
35    object
36    object
37    object
38    object
39    object
40    object
dtype: object

In [7]:
import os

print(os.listdir("../01_Raw_Data/Industrial_Production"))

['.DS_Store', 'IIP_Dashboard Data_Jun2026-28.07.2026.xlsx']

In [8]:
import pandas as pd
import os

iip_path = "../01_Raw_Data/Industrial_Production/IIP_Dashboard Data_Jun2026-28.07.2026.xlsx"

xls = pd.ExcelFile(iip_path)

print("Sheets available:")
print(xls.sheet_names)

Sheets available:
['UBC-Monthly', 'Sectoral-Monthly', 'UBC-Annual', 'Sectoral-Annual', 'Sectoral Weights']

In [9]:
for sheet in xls.sheet_names:
    temp = pd.read_excel(iip_path, sheet_name=sheet, header=None)
    
    print("\n" + "="*60)
    print("SHEET:", sheet)
    print("SHAPE:", temp.shape)
    print("="*60)
    
    display(temp.head(10))

============================================================
SHEET: UBC-Monthly
SHAPE: (7, 41)
============================================================

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,Use-based category,Weight,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,...,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00,2026-06-01 00:00:00
1,Primary goods,31.136,1.3,5.8,5.4,-0.9,1.3,-1.9,5,0.8,...,6.6,0.4,1.1,2.4,1.9,0,0.2,0.8,2.7,4.9
2,Capital goods,8.082,-4.7,1.6,8.8,4.1,12.8,16.3,7.6,1.2,...,13.2,5.4,16.6,12.9,12.4,16.5,8.5,12,15.5,14.2
3,Intermediate goods,22.416,0.6,5.5,1.7,4.8,8.2,5.6,6.3,1.2,...,6.4,1.2,8.2,7.7,5.6,4.7,6,10.3,5.8,9.3
4,Infrastructure/ construction goods,10.908,5.7,7.9,7.4,7.3,11.8,9.1,10.3,3.2,...,9.8,5.1,12,12.3,12.9,10.1,5.2,6,6.6,7.5
5,Consumer durables,11.311,-4,-1.2,-1.2,2.4,7.9,8.3,12.6,-3.3,...,4.6,-6,13,7.4,-0.2,4.2,2.4,5.6,8,7.7
6,Consumer non-durables,16.147,0.6,8.4,6.9,5,8.7,6.4,3.3,2.9,...,-0.5,-9.4,3.9,5.9,-1.2,1.6,-0.6,0.2,-0.4,4.9

============================================================
SHEET: Sectoral-Monthly
SHAPE: (6, 41)
============================================================

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,Description,Weights,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,...,2025-09-01 00:00:00,2025-10-01 00:00:00,2025-11-01 00:00:00,2025-12-01 00:00:00,2026-01-01 00:00:00,2026-02-01 00:00:00,2026-03-01 00:00:00,2026-04-01 00:00:00,2026-05-01 00:00:00,2026-06-01 00:00:00
1,Mining & Quarrying,11.053,-2.6,0.7,-0.1,-17.2,-17.5,-17,1.6,-0.4,...,15.7,2.8,3.3,0.8,-0.5,-2.4,-2.6,-3.8,-1.4,1
2,Manufacturing,76.062,0.1,5.2,4.2,4.7,8.5,6.9,6.5,1.5,...,5.5,-0.7,8.8,7.7,4.6,5.7,4,6.1,5.2,7.8
3,Electricity & Gas Supply,10.865,3.8,9.1,10.4,10,19,11.1,10.3,-4,...,3.3,-7,-1.6,5.9,5.6,1.9,1.2,4.6,10.3,10.6
4,"Water Supply, Sewerage & Waste Management",2.02,9.6,11,13.1,13.7,15.7,17,18.6,20.5,...,6.2,6,4.3,4.4,5.1,5.6,6.4,6.6,5.5,6.1
5,General,100,0.4,5.2,4.6,3,6.9,4.9,6.6,1.1,...,6.1,-0.9,7,6.7,4.1,4.4,3,4.9,5,7.3

============================================================
SHEET: UBC-Annual
SHAPE: (7, 5)
============================================================

                                    0       1        2        3        4
0                  Use-based category  Weight  2023-24  2024-25  2025-26
1                       Primary goods  31.136      5.4      4.7      2.3
2                       Capital goods   8.082     10.1      7.9     10.4
3                  Intermediate goods  22.416      6.1      5.9      5.2
4  Infrastructure/ construction goods  10.908     10.4      6.8      8.8
5                   Consumer durables  11.311        5      8.4      3.1
6               Consumer non-durables  16.147      7.7      3.6      0.8

============================================================
SHEET: Sectoral-Annual
SHAPE: (6, 5)
============================================================

,0,1,2,3,4
0,Description,Weights,2023-24,2024-25,2025-26
1,Mining & Quarrying,11.053,2.2,2.8,3.7
2,Manufacturing,76.062,7.1,6,4.8
3,Electricity & Gas Supply,10.865,7.4,5.2,0.8
4,"Water Supply, Sewerage & Waste Management",2.02,17.8,11.9,6.4
5,General,100,6.8,5.7,4.3

============================================================
SHEET: Sectoral Weights
SHAPE: (38, 3)
============================================================

                    0                                           1        2
0            NIC 2025                                 Description  Weights
1               05-06                               Fuel Minerals    5.647
2                  07  Metallic Minerals incl. Rare Earth Mineral    1.995
3                  08   Non-Metallic Minerals incl. Minor Mineral    3.411
4  Mining & Quarrying                                         NaN   11.053
5                  10                Manufacture of food products    5.679
6                  11                    Manufacture of beverages    1.113
7                  12             Manufacture of tobacco products    0.774
8                  13                     Manufacture of textiles    3.275
9                  14              Manufacture of wearing apparel     1.97

In [10]:
import os

iip_clean_dir = "../02_Clean_Data/IIP"

os.makedirs(iip_clean_dir, exist_ok=True)

print("Created:", iip_clean_dir)

Created: ../02_Clean_Data/IIP

In [11]:
weights = pd.read_excel(
    iip_path,
    sheet_name="Sectoral Weights"
)

display(weights)

,NIC 2025,Description,Weights
0,05-06,Fuel Minerals,5.647
1,07,Metallic Minerals incl. Rare Earth Mineral,1.995
2,08,Non-Metallic Minerals incl. Minor Mineral,3.411
3,Mining & Quarrying,NaN,11.053
4,10,Manufacture of food products,5.679
5,11,Manufacture of beverages,1.113
6,12,Manufacture of tobacco products,0.774
7,13,Manufacture of textiles,3.275
8,14,Manufacture of wearing apparel,1.970
9,15,Manufacture of leather and related products,0.607
10,16,Manufacture of wood and products of wood and c...,0.239
11,17,Manufacture of paper and paper products,1.375
12,18,Printing and reproduction of recorded media,0.506
13,19,Manufacture of coke and refined petroleum prod...,7.721
14,20,Manufacture of chemicals and chemical products,7.813
15,21,Manufacture of basic pharmaceutical products a...,5.833
16,22,Manufacture of rubber and plastics products,3.384
17,23,Manufacture of other non-metallic mineral prod...,3.519
18,24,Manufacture of basic metals,9.198
19,25,"Manufacture of fabricated metal products, exce...",2.481
20,26,"Manufacture of computer, electronic and optica...",2.085
21,27,Manufacture of electrical equipment,3.175
22,28,Manufacture of machinery and equipment n.e.c.,5.020
23,29,"Manufacture of motor vehicles, trailers and se...",6.417
24,30,Manufacture of other transport equipment,2.089
25,31,Manufacture of furniture,0.283
26,32,Other manufacturing,1.509
27,Manufacturing,NaN,76.062
28,3512,Renewable Electricity,1.629
29,3511,Non-Renewable Electricity,8.542
30,351,Electricity,10.171
31,3512,Gas Supply,0.694
32,Electricity & Gas Supply,NaN,10.865
33,36,Water Supply,1.059
34,37-38,Sewerage & Waste Management,0.961
35,"Water Supply, Sewerage & Waste Management",NaN,2.020
36,General,NaN,100.000

In [12]:
sectoral = pd.read_excel(
    iip_path,
    sheet_name="Sectoral-Monthly"
)

print(sectoral.columns.tolist())
print(sectoral.shape)

['Description', 'Weights', datetime.datetime(2023, 4, 1, 0, 0), datetime.datetime(2023, 5, 1, 0, 0), datetime.datetime(2023, 6, 1, 0, 0), datetime.datetime(2023, 7, 1, 0, 0), datetime.datetime(2023, 8, 1, 0, 0), datetime.datetime(2023, 9, 1, 0, 0), datetime.datetime(2023, 10, 1, 0, 0), datetime.datetime(2023, 11, 1, 0, 0), datetime.datetime(2023, 12, 1, 0, 0), datetime.datetime(2024, 1, 1, 0, 0), datetime.datetime(2024, 2, 1, 0, 0), datetime.datetime(2024, 3, 1, 0, 0), datetime.datetime(2024, 4, 1, 0, 0), datetime.datetime(2024, 5, 1, 0, 0), datetime.datetime(2024, 6, 1, 0, 0), datetime.datetime(2024, 7, 1, 0, 0), datetime.datetime(2024, 8, 1, 0, 0), nan, 'nan.1', 'nan.2', datetime.datetime(2024, 12, 1, 0, 0), datetime.datetime(2025, 1, 1, 0, 0), datetime.datetime(2025, 2, 1, 0, 0), datetime.datetime(2025, 3, 1, 0, 0), datetime.datetime(2025, 4, 1, 0, 0), datetime.datetime(2025, 5, 1, 0, 0), datetime.datetime(2025, 6, 1, 0, 0), datetime.datetime(2025, 7, 1, 0, 0), datetime.datetime(2025, 8, 1, 0, 0), datetime.datetime(2025, 9, 1, 0, 0), datetime.datetime(2025, 10, 1, 0, 0), datetime.datetime(2025, 11, 1, 0, 0), datetime.datetime(2025, 12, 1, 0, 0), datetime.datetime(2026, 1, 1, 0, 0), datetime.datetime(2026, 2, 1, 0, 0), datetime.datetime(2026, 3, 1, 0, 0), datetime.datetime(2026, 4, 1, 0, 0), datetime.datetime(2026, 5, 1, 0, 0), datetime.datetime(2026, 6, 1, 0, 0)]
(5, 41)

In [13]:
sectoral = pd.read_excel(
    iip_path,
    sheet_name="Sectoral-Monthly"
)

display(
    sectoral.iloc[:, 15:25]
)

,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,NaN,nan.1,nan.2,2024-12-01 00:00:00,2025-01-01 00:00:00,2025-02-01 00:00:00
0,7.6,4.7,4.0,-5.0,0.4,1.4,3.9,3.9,3.3,0.5
1,6.0,7.2,7.8,3.4,5.5,6.4,6.2,6.4,7.2,3.1
2,13.9,9.4,9.0,-3.4,0.7,3.0,4.5,6.1,1.6,3.0
3,14.2,12.5,13.1,12.2,11.4,12.3,11.8,11.6,10.7,9.8
4,7.3,7.3,7.8,2.1,4.7,5.6,5.9,6.1,6.3,2.9

In [14]:
print(xls.sheet_names)

['UBC-Monthly', 'Sectoral-Monthly', 'UBC-Annual', 'Sectoral-Annual', 'Sectoral Weights']

In [15]:
iloc[:, 15:25]

NameError: name 'iloc' is not defined

In [16]:
sectoral = pd.read_excel(
    iip_path,
    sheet_name="Sectoral-Monthly"
)

display(sectoral.iloc[:, 15:25])

,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,NaN,nan.1,nan.2,2024-12-01 00:00:00,2025-01-01 00:00:00,2025-02-01 00:00:00
0,7.6,4.7,4.0,-5.0,0.4,1.4,3.9,3.9,3.3,0.5
1,6.0,7.2,7.8,3.4,5.5,6.4,6.2,6.4,7.2,3.1
2,13.9,9.4,9.0,-3.4,0.7,3.0,4.5,6.1,1.6,3.0
3,14.2,12.5,13.1,12.2,11.4,12.3,11.8,11.6,10.7,9.8
4,7.3,7.3,7.8,2.1,4.7,5.6,5.9,6.1,6.3,2.9

In [18]:
os.listdir("../01_Raw_Data/Interest_Rates")

['Weighted Average Lending Rate.xlsx',
 'Major Monetary Policy Rates and Reserve Requirements - Bank Rate, LAF (Repo, Reverse Repo, SDF and MSF) Rates, CRR & SLR.xlsx',
 'Other STRBI Table No 18. Bank Group-Wise and Occupation-Wise Weighted Average Lending Rate and Deposit Rate.xlsx']